### ISSUE TITLE
`digdag push` doesn't include dot files

### ISSUE THREAD

**Issue by pdelagrave** [treasure-data/digdag#1050]
https://github.com/treasure-data/digdag/blob/614c4330acbe6c6a5bf4be4ffd9ccfce1c5996c2/digdag-core/src/main/java/io/digdag/core/archive/ProjectArchive.java#L96

Dotfiles are skipped and not added to the project being pushed; which is a problem for tasks requiring such files. Many applications and libraries are expecting files with default filename starting with a dot.

Is there a reason to ignore such files? I would expect the user to be responsible for choosing what's going to be pushed in the project.

Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @pdelagrave 

I'm not the original developer, So I can't answer 'why'.
Some users are managing secrets and project related files using like `.secrets` or `.xxx`.

Do those files have to begin dot?

**Comment by muga** [comment]
Hi @pdelagrave I agree with @hiroyuki-sato's thought. dot files sometimes have special meaning, for example, local machine settings, credentials included. We don't want to upload such files on digdag server as project archive accidentally.

> which is a problem for tasks requiring such files. Many applications and libraries are expecting files with default filename starting with a dot.

I got your point. Can you give us your use case more details if possible? Not sure but we can help or suggest something to you.

**Comment by pdelagrave** [comment]
Hi
It was to use specific ruby environment per directory using rbenv, so the `.ruby-version` file was important.
We have a relatively satisfying workaround now using the new feature to specify the path to the ruby executable in the rb operator.

Thanks

Pierre
