### ISSUE TITLE
ParamServer returns empty values

### ISSUE THREAD

**Issue by jaymed** [treasure-data/digdag#1053]
digdag version: 0.9.32

I'm getting inconsistent results using the paramstore. After 1 day I get empty values returned. I'm using a postgres database to store the values. The values look good in the database.

The problem seems to be a wrong TTL setting in file `ParamServerClient.java` (https://github.com/treasure-data/digdag/commit/7b6b91d59ec1f7494d1ef472f6d4e47e86962d32). It should be 90 days but it's actually calculated incorrectly and it ends up being 1.5 days. 

The documentation does not mention any reference to this TTL, which seems very important. This should definitely be added.

Aside from getting the correct TTL calculated, we should be able to configure the TTL outside of the code. For my own purposes, I'd like the param store to serve as a permanent storage for system-wide configurations. Currently there is no way to set system-wide values.

**Comment by hiroyuki-sato** [comment]
Hello, @jaymed 

Thank you for reporting this issue.
It seems that `DEFAULT_TTL` values are wrong.  It seems that the unit is seconds.
If so, correct value(90days) is `60 * 60 * 24 * 90`.

**Comment by jaymed** [comment]
I appreciate the response. Thanks!
