### ISSUE TITLE
[question] how to start a new session attempt of a workflow over the REST API

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1055]
How do you start a new session attempt of a workflow over the REST API?

I am looking for the equivalent of:

`
$ digdag start myproj mywf --session now -P ./my_input.yml
`

I've studied the available REST API calls that are exposed by swagger but couldn't find the corresponding option.

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

I've never tried it. but It may `PUT /api/atttempts`.

https://github.com/treasure-data/digdag/blob/master/digdag-cli/src/main/java/io/digdag/cli/client/Start.java#L175

https://github.com/treasure-data/digdag/blob/master/digdag-client/src/main/java/io/digdag/client/DigdagClient.java#L718-L724

![api_attempts](https://user-images.githubusercontent.com/767650/54608493-2a7d9800-4a94-11e9-919b-e364fde4b532.png)

**Comment by ehaupt** [comment]
Thank you @hiroyuki-sato. I'll test it. I'm currently trying to integrate a workflow in a self-care portal.

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

JFYI, Here is 3rd party digdag clients.
* [mog](http://iroilog.net/2017/06/release-mog/) Digdag Client (golang)
* [digdag_client](https://github.com/saicologic/digdag_client) Ruby

**Comment by ehaupt** [comment]
Hello @hiroyuki-sato, thank you again. This is very helpful.

**Comment by ehaupt** [comment]
@hiroyuki-sato: I can confirm that `PUT /api/atttempts` works for my purpose.

It wouldn't accept `"sessionTime": "now"` but using ISO 8601 date format worked like a charm.

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

Congratulation! 
JFYI `now` create current time with ISO8601 format. So maybe you made the same implementation.

https://github.com/treasure-data/digdag/blob/master/digdag-cli/src/main/java/io/digdag/cli/client/Start.java#L125

**Comment by ehaupt** [comment]
Hello, @hiroyuki-sato

I've seen that someone else had a similar question and I was wondering if I should submit a quick [example](https://github.com/treasure-data/digdag/tree/master/examples) workflow with instructions on how to launch it over the REST API via curl.
