### ISSUE TITLE
Params life cycle

### ISSUE THREAD

**Issue by IlyaGazman** [treasure-data/digdag#1056]
It is not clear to me from the docs what is the lifecycle of the params. For example if one of my tasks failed, will it have access to exported params? What about retries? What if my server goes offline and restarts?

**Comment by hiroyuki-sato** [comment]
Hello, @IlyaGazman 

Below table may help. Please let me know if you need more detail specific parameter. 

| parameters / command | user          | scope             | lifecycle                |
|---------------------|---------------|-------------------|--------------------------|
| digdag server -P/-p | administrator | server wide       | server running           |
| digdag start -P/-p  | workflow user | workflow          | Same session(keep retry) |
| digdag secrets      | workflow user | projects          | persistent               |
| [Export and store](https://docs.digdag.io/concepts.html#export-and-store-parameters)    | workflow user | project           | attempts                 |
| param_set>          | workflow user | same project      | TTL(90days) (Bug)#1053        |

Those parameters which except `digdag server -P/-p` keep accessible if a server goes offline.
(If you use `server.type = postgresql` and `server.type = h2` with `database.path` setting)

And this comment also may help

https://github.com/treasure-data/digdag/issues/990#issuecomment-463544061
