### ISSUE TITLE
[feature request] Send parameters to a workflow by REST API

### ISSUE THREAD

**Issue by jojoke13** [treasure-data/digdag#1074]
I see that you can call a workflow with PUT by sending {"params":{},"sessionTime":"2019-04-05T15:58:59+01:00","workflowId": 1} for workflow 1.

However I don't know (or there isn't a way) how to pass parameters with a REST API

Thanks again ! 

P.S.: I would be glad to help in the documentation of Digdag, but don't know who to ask

**Comment by hiroyuki-sato** [comment]
Hello, @jojoke13 

What digdag command do you want to send in REST API?
(`digdag start`?)

This following links may help. 
* https://github.com/treasure-data/digdag#check-digdag-rest-api
* #1055

**Comment by jojoke13** [comment]
I would like to send the equivalent of : digdag run -p my_var1=foo -p my_var2=abc
(my_var1 and myvar2)

Sorry, for the incovinience - i had troubles to launch the gradle ( the cli build failed because it can't find the javax annotation, and I haven't figured out yet why) and i opened the feature request in the meantime

**Comment by hiroyuki-sato** [comment]
Hello, @jojoke13 

`digdag run` doesn't server command. You need to use `digdag start` command.
 #1055 may help. 

What Java version are you using? Digdag requires Java8 environment.
https://github.com/treasure-data/digdag#development

**Comment by hiroyuki-sato** [comment]
Hello, @jojoke13 

Could you take a look at this example
https://github.com/treasure-data/digdag/pull/1075/files

`msg` is a parameter.

Thank you @ehaupt

**Comment by jojoke13** [comment]
Works like a charm ! 
Thanks a lot :)
