### ISSUE TITLE
[info-request]  Launch several instances with different parameters

### ISSUE THREAD

**Issue by jojoke13** [treasure-data/digdag#1078]
Is it possible to have several instances of  a same workflow but different parameters ?
(it may be linked to #1056 )

Because when I launch two workflows (one with DUSER268, the other DUSER267) : 
curl -X PUT "http://localhost:65432/api/attempts" -H "accept:application/json" -H "Content-type: application/json" -d "{\"params\" : {\"msg\": \"DUSER268\"}, \"sessionTime\": \"2019-04-08T13:16:14+01:00\", \"workflowId\": \"2\"}"
curl -X PUT "http://localhost:65432/api/attempts" -H "accept:application/json" -H "Content-type: application/json" -d "{\"params\" : {\"msg\": \"DUSER267\"}, \"sessionTime\": \"2019-04-08T13:16:14+01:00\", \"workflowId\": \"2\"}"

They both answer with the DUSER268 :  
{"id":"7","index":1,"project":{"id":"2","name":"new"},"workflow":{"name":"new","id":"2"},"sessionId":"2","sessionUuid":"e320608b-8ea9-4482-8aa5-d4e51a7f92c5","sessionTime":"2019-04-08T13:16:14+02:00","retryAttemptName":null,"done":true,"success":true,"cancelRequested":false,"params":{"msg":"DUSER268"},"createdAt":"2019-04-08T13:16:35Z","finishedAt":"2019-04-08T13:16:43Z"}

**Comment by hiroyuki-sato** [comment]
Hello, @jojoke13 

You can't run a workflow using another parameter with the same session.
You may use the following ways.

* Change session value.
* Register two project. (`digdag push DUSER268` , `digdag push DUSER267`)
