### ISSUE TITLE
Authenticator as a System Plugin

### ISSUE THREAD

**Issue by pdelagrave** [treasure-data/digdag#1079]
Hi,

We need to integrate Digdag within a system using oAuth2.

Before starting working on a PR we'd like to have feedback on our plans:
1. Making the Authenticator interface a system plugin and move it to the SPIs.
2. Make the JwtAuthenticator the default plugin to keep things as they are.
3. Create an oAuth2 "Authenticator" plugin that could be enabled and configured by properties.
4. Make the WebUI able to do oAuth2 Implicit Grant auth when configured to do so.

1 and 2 would be one PR while 3 and 4 another one.

Let me know of any issue with this plan.

Thanks,

Pierre

**Comment by TakahikoKawasaki** [comment]
Some notes.

"3.1.2. Implicit Grant" in "[OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/draft-ietf-oauth-security-topics/?include_text=1)" says as follows.

> _In order to avoid these issues, clients **SHOULD NOT use the implicit grant** (response type "token") or any other response type issuing access tokens in the authorization response, such as "token id_token" and "code token id_token", unless the issued access tokens are sender-constrained and access token injection in the authorization response is prevented._

OAuth should not be used for authentication. OpenID Connect is a better option for the purpose. See "[The problem with OAuth for Authentication](http://www.thread-safe.com/2012/01/problem-with-oauth-for-authentication.html)".

**Comment by muga** [comment]
Hi @pdelagrave, I'm not 100% sure what you want to design and impl. But at least for your 1st and 2nd items, it's ok for us to make extension point for authenticator as system plugin. And can you take a look @TakahikoKawasaki's comment and any thoughts? 

@TakahikoKawasaki thank you for your comment.

**Comment by pdelagrave** [comment]
@TakahikoKawasaki 
> Some notes.
> 
> "3.1.2. Implicit Grant" in "[OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/draft-ietf-oauth-security-topics/?include_text=1)" says as follows.
> 
> > _In order to avoid these issues, clients **SHOULD NOT use the implicit grant** (response type "token") or any other response type issuing access tokens in the authorization response, such as "token id_token" and "code token id_token", unless the issued access tokens are sender-constrained and access token injection in the authorization response is prevented._
> 
> OAuth should not be used for authentication. OpenID Connect is a better option for the purpose. See "[The problem with OAuth for Authentication](http://www.thread-safe.com/2012/01/problem-with-oauth-for-authentication.html)".

Can't argue with that, thanks for providing links to documents.
The usage of implicit grant was proposed because given specific circumstances, it can be secure enough while being the simplest grant type. Though I agree that the point 4 I suggested isn't the most secure by default.
To your points, it would better to use OpenID Connect on top of the auth code grant. That seems to be the best that can be done for a Single Page Application like Digdag UI.
https://tools.ietf.org/id/draft-parecki-oauth-browser-based-apps-00.html

@muga 
We can start with a PR for point 1 and 2 and discuss a UI patch later.

Thanks

Pierre

**Comment by pdelagrave** [comment]
Hi @muga,
I've submitted 2 PRs related to this issue:
https://github.com/treasure-data/digdag/pull/1098
https://github.com/treasure-data/digdag/pull/1099

The first one is only about extracting the Authenticator interface into an SPI and making the existing `JwtAuthenticator` into a plugin.

The second one is a new Authenticator plugin that does basic auth. This is useful for many situations where a user deploys Digdag in a lesser than prod environment but still require some sort of auth.

In either cases, the `JwtAuthenticator` plugin is the default one and the PRs don't introduce any breaking changes.

Thanks,

Pierre

**Comment by yoyama** [comment]
Already merged. Close.
