### ISSUE TITLE
[Q] Workload distribution in multi-agent setup

### ISSUE THREAD

**Issue by kulmam92** [treasure-data/digdag#1084]
digdag version: 0.9.35
OS: windows 2016
setup: 2 executors, 2 agents
Workflow:
```
+execute_channel:
  for_each>: {j: [0,1,2,3,4,5]}
  _do:
    +get_pipeline_config:
      py>: scripts.main.get_pipeline_config_channel
      require: 'scripts/main'  

    +execute_pipeline:
      for_each>:
        i: ${TOTAL_NUMBER}
      _parallel: true
      _do:
        +step1:
          _export:
            EMBULK_SQL_STRING: ${SQL_STRING[i]}
            EMBULK_BLOB_CONTAINER: ${BLOB_CONTAINER[i]}
            EMBULK_BLOB_FULPATH: ${BLOB_FULLPATH[i]}
            EMBULK_BLOB_FILENAME: ${BLOB_FILENAME[i]}
            EMBULK_BLOB_FORMAT: ${BLOB_FORMAT[i]}
            EMBULK_BLOB_PIPE_ID: ${PIPE_ID[i]}
          sh>: embulk '"-J-O"' run .\scripts\config.yml.liquid
```

This workflow will start 10 embulk tasks 6 times. I was expecting digdag to use both agent severs for this workflow but it seems like it's using only server. There is very low activity-close to nothing- in the other sever. Do you have any advise on what to do to distribute the workload?

**Comment by yoyama** [comment]
@muga any idea?  In my understand, there is no way to distribute tasks to agents fairly.

**Comment by yoyama** [comment]
By discussion with @muga, 
I guess if you set **--max-task-threads** to small one, 
one server's running task will be restricted and as result both servers will be used. 
But we don't confirm this workaround really works well.

**Comment by yoyama** [comment]
I close this issue because of no response.
