### ISSUE TITLE
Badge for displaying packaging status

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1089]
[Repology](https://repology.org/project/digdag/versions) is a great website for comparing package versions over different GNU/Linux distros and the various BSDs.

There is also an API that that provides nice [badges](https://repology.org/project/digdag/badges) to show versions in all known repositories like so:

[![Packaging status](https://repology.org/badge/vertical-allrepos/digdag.svg)](https://repology.org/project/digdag/versions)

I think this might be a nice addition to [README.md](https://github.com/treasure-data/digdag/blob/master/README.md).

**Comment by yoyama** [comment]
@ehaupt Thanks for your proposal. It is nice for me.
@muga How about it?

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt,

What status do you want to know about Digdag?
If you want to know the latest version, just add the following link in README.md
This URL provided by Bintray. 

[![](https://api.bintray.com/packages/digdag/maven/digdag/images/download.svg)](https://bintray.com/digdag/maven/digdag/_latestVersion)


```
[![](https://api.bintray.com/packages/digdag/maven/digdag/images/download.svg)](https://bintray.com/digdag/maven/digdag/_latestVersion)
```

**Comment by ehaupt** [comment]
I propose to display the overview badge that shows the versions in all known repositories. That way users know what version to expect if they install digdag from their preferred repository. Also, as digdag becomes available in more repositories it will display those as well.

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt Oh, I got. repositories mean Homebrew, LinuxBrew, AUR ...

**Comment by muga** [comment]
@ehaupt @yoyama @hiroyuki-sato Looks good! Can we create new PR to add those badges in README.md??

**Comment by ehaupt** [comment]
Hello @muga, which file did you have in mind? Maybe [digdag-docs/src/getting_started.md](https://github.com/treasure-data/digdag/blob/master/digdag-docs/src/getting_started.md)? We could always keep it an option for later when digdag has been packaged for more distros/repositories.

**Comment by muga** [comment]
@ehaupt Yes, agree, good to have in getting_started.md I think:-)
