### ISSUE TITLE
[feature request] ignore file configuration like .gitignore

### ISSUE THREAD

**Issue by chezou** [treasure-data/digdag#1092]
This is a feature request to have a ignore file for a project.

**Expected use case:**
When developing a workflow with Python, Python generates `__pycache__` files. In Python development, it is a popular way to create a virtual environment under the project directory and sometimes it could be pushed to digdag server or could fail to push due to the large size of library dirs.

It is a usual way to develop workflow locally and push to server for production. So I'd be happy if we could have a ignore file configuration.

**Comment by szyn** [comment]
This feature was released in v0.10.3. Please see also here: https://docs.digdag.io/releases/release-0.10.3.html
I will close this issue.
