### ISSUE TITLE
/api/projects does not support pagination

### ISSUE THREAD

**Issue by kiyoto** [treasure-data/digdag#1106]
Without pagination (or filter, or something...) it's not possible to retrieve the list of all projects. When Digdag is set up to create many projects automatically (say, in the case of Treasure Data), it becomes difficult to get the full list of projects.

c.f. https://github.com/treasure-data/digdag/blob/eb44c91fbee3bc38f869c088814a2a623b831b3d/digdag-server/src/main/java/io/digdag/server/rs/ProjectResource.java#L264

**Comment by yoyama** [comment]
@kiyoto Thank you for your proposal and sorry for late reply.
I agree with requirement of pagination. But I don't know there are something reasons for it or not.
So I will discuss with @muga and make decision to accept this requet or not.

**Comment by yoyama** [comment]
The PR #1697 has supported it.
