### ISSUE TITLE
Add more examples to documentation

### ISSUE THREAD

**Issue by Vanuan** [treasure-data/digdag#1133]
It would be awesome to have more ready to use recipes for common tasks, such as starting a server with scheduled tasks. E.g.

1. Create `digdag.conf` file with a secret:
```
digdag.secret-encryption-key = MDEyMzQ1Njc4OTAxMjM0NQ==
# example
echo -n '16_bytes_phrase!' | openssl base64
MTZfYnl0ZXNfcGhyYXNlIQ==
```
2.  Start server
```
digdag server -o data -b 0.0.0.0 -c digdag.conf
```
Make sure the `data` folder is backed up
3. Create/update project:
```
digdag push --project workflows scheduled-transactions
```
4. Create secret for project's pg datbase:
```
secrets --project scheduled-transactions --set pg.password
```

**Comment by hiroyuki-sato** [comment]
Thank you for your feedback!

It seems that it is good receipts for beginners.
I'll a take a look it later.
You are welcome to contribute as well.

The default configuration path is `~/.config/digdag/config` by the way.
You will find this path `digdag` usage for example.
