### ISSUE TITLE
Looping in parent and child workflow returns unexpected values for variable ${i}

### ISSUE THREAD

**Issue by ctlbui88** [treasure-data/digdag#1151]
[test1.zip](https://github.com/treasure-data/digdag/files/3299329/test1.zip)

Hi,
Attached is a digdag project folder with the following workflows and what they do:

Workflow Name: "test4-1.dig"
1. Do 2 loops. For each loop, export variable ${var1}: ${i+1}
2. Call workflow "test2-2.dig".

Workflow Name: "test2-2.dig"
1. Do 3 loops.  For each loop, echo>: ${var1}.

Problem:
When I run "test4-1.dig", I expected that it will print the following values in order:
1
1
1
2
2
2

However, the actual values that I saw, in order, are:
1
2
3
1
2
3

My understanding was that ${var1} was assigned a static value in the parent workflow (test3-1.dig seems to support this assumption) and the child workflow will just read that static value.  However, in this case, it seems that the variable ${i} created by the loop command in the child workflow dictates what value ${var1} is.

Can you please explain the behavior if I'm misunderstanding?  And if I am misunderstanding, can you provide an example of how I can produce the result I expected?

**Comment by hiroyuki-sato** [comment]
Hello, @ctlbui88 

I don't recommend to use `${}` syntax in `_export` section.
It causes an unexpected result.

Digdag evaluates `${}` syntax in each task even if you write in `_export` part.
So, `echo> ${var1}` means `echo> ${i+1}` and ${i} value is used loop> operator value in test2-2.dig

That's why the output is the following.

```
echo> ${first_loop_i_value_in_test2-2.dig  = 0 + 1} -> 1
echo> ${second_loop_i_value_in_test2-2.dig = 1 + 1} -> 2
echo> ${third_i_value_in_test2-2.dig       = 2 + 1} -> 3
```

**Comment by hiroyuki-sato** [comment]
Hello, @ctlbui88 
This [comment](https://github.com/treasure-data/digdag/issues/351#issuecomment-253313664) may help too.

**Comment by ctlbui88** [comment]
understood.  Thanks!
