### ISSUE TITLE
how to configure mysql as database for digdag scheduler 

### ISSUE THREAD

**Issue by nsurisetti** [treasure-data/digdag#1161]
If we want to use mysql as backend database for the dig-dag scheduler what we need to change it let me know.

**Comment by hiroyuki-sato** [comment]
Hello, @nsurisetti. Could you check #963? In short, MySQL backend doesn't support yet.

**Comment by nsurisetti** [comment]
Can you support me what and where code changes need to customize back end database to MySQL.

**Comment by hiroyuki-sato** [comment]
Hello, @nsurisetti 

I'm not familiar database extension.
But, maybe [digdag-core/src/main/java/io/digdag/core/database](https://github.com/treasure-data/digdag/tree/master/digdag-core/src/main/java/io/digdag/core/database) is a one of the starting place.

You will find PostgreSQL specific codes in these files.

```
grep -irl 'postgresql' digdag-core/src/main/java/io/digdag/core/database
digdag-core/src/main/java/io/digdag/core/database/DatabaseConfig.java
digdag-core/src/main/java/io/digdag/core/database/DatabaseScheduleStoreManager.java
digdag-core/src/main/java/io/digdag/core/database/DatabaseSessionStoreManager.java
digdag-core/src/main/java/io/digdag/core/database/DatabaseMigrator.java
digdag-core/src/main/java/io/digdag/core/database/DatabaseSecretControlStore.java
digdag-core/src/main/java/io/digdag/core/database/BasicDatabaseStoreManager.java
digdag-core/src/main/java/io/digdag/core/database/DatabaseProjectStoreManager.java
digdag-core/src/main/java/io/digdag/core/database/ThreadLocalTransactionManager.java
```

Digdag depends on [uuid-ossp](https://www.postgresql.org/docs/11/uuid-ossp.html) extension for generating unique UUID on the PostgreSQL data store.
You may need to find an alternative solution for MySQL.

Finally, this ER also may help. ( Almost the same latest version but It's a little old)

![](https://camo.qiitausercontent.com/11fc5df20e0fe71fe2b28a254ca00440de12e2c7/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f36313436342f64323636333130662d623766302d643733622d383961632d6330323532366363646462322e706e67)
* [PDF](https://gist.githubusercontent.com/hiroyuki-sato/d6a343a4716ec35359f7afac9b275c04/raw/f88637fd4716f2863f4d322929cc0d813241ef78/digdag_er.pdf)

@muga, @yoyama, Could you comment if you have any information?

**Comment by nsurisetti** [comment]
For database connectivity you are using jdbc are another process which are you used??

**Comment by hiroyuki-sato** [comment]
Hello, @nsurisetti 

> For database connectivity you are using jdbc are another process which are you used??

Could you tell me more detail, I don't understand what are you asking.

> And digdag-plugin-mysql plugin is completely developed or any of the functionality is miising(Which means create, insert, delete, update quires all are working or not)

Maybe insert/delete/update works.
But I don't test well, (I developed this plugin, but not use in my deployment environment yet).
please let me know when you have any problem.

Just in case,`digdag-plugin-mysql` is the operator for MySQL.
It does not manage a schedule.

Best regards.

**Comment by nsurisetti** [comment]
Thank you,

what are the dependency jars you are used to connect postgresql database as you backend db for dig dag

for example you are using the JDBC driver for postgressql to connect database or odbc or any other else

**Comment by hiroyuki-sato** [comment]
Hello, @nsurisetti 

This file may help.

https://github.com/treasure-data/digdag/blob/d91df00327eac1a3caeb060b6f76931bd1ffc3af/digdag-core/build.gradle#L18-L21

**Comment by nsurisetti** [comment]
Thank you for your support,

I have small question in which class we are maintaining the connection open details for application code to database.

**Comment by hiroyuki-sato** [comment]
Hello, @nsurisetti 

As I told you before, I'm not familiar around this area.
So, Could you read source code by yourself?

It _seems_ that JDBC connection config builds in this part.

https://github.com/treasure-data/digdag/blob/dbcd311a380dfdf0b34a6ea5680d3aa2275e05dd/digdag-core/src/main/java/io/digdag/core/database/DatabaseConfig.java#L62-L92

`DatabaseConfigProvider` call above method.

https://github.com/treasure-data/digdag/blob/dbcd311a380dfdf0b34a6ea5680d3aa2275e05dd/digdag-core/src/main/java/io/digdag/core/database/DatabaseConfigProvider.java#L15-L18


`DatabaseModule` probably call this method using Google Guice injection.

https://github.com/treasure-data/digdag/blob/dbcd311a380dfdf0b34a6ea5680d3aa2275e05dd/digdag-core/src/main/java/io/digdag/core/database/DatabaseModule.java#L16-L22

**Comment by nsurisetti** [comment]
Thank you!!

I need small clarification regarding workflow execution, while executing the pipeline with schedule mode i.e, using cron expression sessions are created automatically for these sessions creation is started in which class and flow of the sessions creation.

**Comment by yoyama** [comment]
I would like to close this issue.
We don't have a plan to support another DB and this is not issue or question about using Digdag.
