### ISSUE TITLE
log doesn't refresh until task end

### ISSUE THREAD

**Issue by juncaofish** [treasure-data/digdag#1193]
I'm running digdag server with the following script
`nohup digdag server -b 0.0.0.0 -n 9876 -o ~/digdag/db -O ~/digdag/log &`
while my workflow has a single task (long time)

But I noticed the digdag UI doesn't refresh log for the task until it's completed. Could I see the real time log from the web just like less +F command?
![屏幕快照 2019-07-30 下午9 55 35](https://user-images.githubusercontent.com/3062715/62135735-50099080-b315-11e9-9e29-5bed6e82fade.png)

**Comment by hiroyuki-sato** [comment]
Hello, @juncaofish. I think this issue is the same request #992.

**Comment by juncaofish** [comment]
> Hello, @juncaofish. I think this issue is the same request #992.

I was using sh command. Is there a workaround for this requirement?

**Comment by hiroyuki-sato** [comment]
Hello, @juncaofish. I don't know an alternative way on UI. Have you ever tried `digdag log <attempt-id> -f`?

**Comment by yoyama** [comment]
Please check #1209 
This is under development but you can show the log of long task.
I will close #700 because it is obsolete and did not get enough agreement from the committers at that time.
