### ISSUE TITLE
[Question] Target agents in a HA setup

### ISSUE THREAD

**Issue by yanivyalda** [treasure-data/digdag#1233]
We have multiple agents across different environments/countries. Can we target the agent to perform the workflow execution?

**Comment by hiroyuki-sato** [comment]
Hello, @yanivyalda 

Do you want to assign a workflow execution to the specific host? Unfortunately, that feature doesn't support yet.  Please see #1031, #727 and #521.

**Comment by yanivyalda** [comment]
okay thank you @hiroyuki-sato. I will update our architecture
