### ISSUE TITLE
[feature-request] embulk extra args options.

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#126]
Hello.

I would like to execute `embulk run -c diff.yml config.yml` command. 
But I can't add `-c diff.yml` option in embulk operator. 

So Now I'm using sh operator. It's not smart way.

Please add extra args option for embulk operator.

Digdag version: 0.8.1

Thanks.

**Comment by komamitsu** [comment]
How about adding `config_diff` command like this?
```
+load:
  embulk>: data/load.yml
  config_diff: true
```

If this feature is enabled, embulk operator
- Reads a config diff stored in the database (h2/PostgreSQL) and generates a temporary config diff file if it exists
- Executes embulk command with `-c` option specifying the config diff file
- Reads a generated config diff file and stores it in database (h2 / PostgreSQL)

**Comment by hiroyuki-sato** [comment]
@komamitsu Thank you for the reply.

I think `config_diff` option is useful. 
Someone want to use needs more options. 
(ex. Now I'm using `-r` option)
How about those options?
I'll ask another Embulk user about this option.

```yaml
embulk>:
config_diff:   # -c option
bundle:        # -b option
log_level:     # -l 
system_config: # -X
- page_size: 
jvm_opts:      # -J 
resume_state:  # -r (Don't needs?)
```

`-J` option support `file path`. It's simple. But It does not work on Windows platform.


```
Usage: embulk run <config.yml>
  Options:
    -r, --resume-state PATH          Path to a file to write or read resume state
    -o, --output PATH                (deprecated)
    -c, --config-diff PATH           Path to a file to read & write the next configuration diff

  Plugin load options:
    -L, --load PATH                  Add a local plugin path
    -I, --load-path PATH             Add ruby script directory path ($LOAD_PATH)
    -C, --classpath PATH             Add java classpath separated by : (CLASSPATH)
    -b, --bundle BUNDLE_DIR          Path to a Gemfile directory (create one using "embulk mkbundle" command)

  Other options:
        --log PATH                   Output log messages to a file (default: -)
    -l, --log-level LEVEL            Log level (error, warn, info, debug or trace)
    -X KEY=VALUE                     Add a performance system config
```

**Comment by hiroyuki-sato** [comment]
I asked the Embulk users about this option. 
This is the summary.

I think it is better to discuss `embulk>` operator feature before implement `config_diff`

The reason is the following.

* An Embulk user use `sh>` operator instead of `embulk>` operator. 
  * A) It support all of the embulk options. (Include `config_diff`)
  * B) It support Liquid template engine.

`config_diff` option solve problem A). But It does not solve the problem B). 
So If this option implement, those of users can't use `embulk>` operator. 

I asked Mr. Furuhashi about this issue at Embulk meetup. 
(I created this issue before the meetup.)
He wants to implement `${}` syntax in Embulk. But this feature has not implemented yet. 


Reference [Twitter](https://twitter.com/hiroysato/status/787974576600780800) (Japanese text).

**Comment by yoyama** [comment]
embulk operator had been deprecated. So close.
