### ISSUE TITLE
Support Github Packages for dynamic plugin loading

### ISSUE THREAD

**Issue by civitaspo** [treasure-data/digdag#1274]
Hi maintainers, I want Github Packages Support for dynamic plugin loading.

In our cases, we use jitpack.io for plugins package registry, but jitpack.io sometimes become unstable, so we want to use Github Packages as a fallback registry. However, digdag does not support registries that require authentications. That's why I created this issue.

ref. similar issue: https://github.com/treasure-data/digdag/issues/762

**Comment by yoyama** [comment]
Sorry for late response.
Thank you for your proposal. It may be valuable idea.
We don't have capacity to implement now, but PR is welcome.
