### ISSUE TITLE
selfupdate authentication

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#128]
Releated #119 

need authentication?

```
digdag selfupdate
2016-06-17 22:14:49 +0900: Digdag v0.8.1
Password of 'beta': 
```

**Comment by frsyuki** [comment]
It's a bug. Will be fixed at the next release (https://github.com/treasure-data/digdag/commit/bf0ce8031c6e1511b54f3eaef651cb84afa855f4).
You can enter one character (any character) to avoid the issue.

**Comment by hiroyuki-sato** [comment]
Thanks!
