### ISSUE TITLE
Github shows latest release v0.9.39 but there is v0.9.40 available

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1291]
Github shows latest release v0.9.39 but there is v0.9.40 available:

![screenshot](https://i.imgur.com/d0Sxkvy.png)

**Comment by yoyama** [comment]
Thank you for your notification.
I created it.
https://github.com/treasure-data/digdag/releases/tag/v0.9.40

**Comment by ehaupt** [comment]
Thank you!
