### ISSUE TITLE
[question] How to define an endless loop task for always ETL processing?

### ISSUE THREAD

**Issue by skokado** [treasure-data/digdag#1296]
Hi, I recently started using digdag and very impressed with this great tool.

I am trying to build a data platform using digdag and embulk.
What I want to do is near-realtime processing always watching data source and loads data when a trigger occurs.

I understand that in a DAG, the path must not be infinite.
Currently I am calling from the outside. Thus `while true; digdag run etl.dig; done`.

Can digdag do this with cool declarative workflows?

I thought about using cron scheduling every minute, but I get into trouble when the execution time of the workflow exceeds 1 minute.
If another process is started before the data acquisition for a specific trigger is completed, the consistency of the target data cannot manage.
(I use queuing to manage triggers).

**Comment by hiroyuki-sato** [comment]
Hello, @skokado 

I don't completely understand your use case yet, 
but what do you think to use `--session yyyy-MM-dd HH:mm:ss` in `digdag run`(local) or `digdag start`(server)?
It expects that input filename has time data (ex. file-2020-01-08T14:00:00).
Digdag doesn't run with the same session.

Another idea, use `digdag-operator-pg_lock` plugin.
Could you check [this page](https://dev.to/hiroysato/digdag-workflow-engine-link-collection-13hf) link if you interest this plugin?

**Comment by toru-takahashi** [comment]
You can use `skip_on_overtime` option when you use a longer session more than cron interval.
https://docs.digdag.io/scheduling_workflow.html#skipping-a-next-workflow-session

(not sure it is your encountered problem)

**Comment by skokado** [comment]
Thank you @hiroyuki-sato @toru-takahashi 

I'll try it.

**Comment by skokado** [comment]
Sorry for late reply.

Setting `skip_on_overtime`  option to `true` exactly fitted my usecase.

Thank you.

**Comment by toru-takahashi** [comment]
Good to hear!
Let me close this issue.
