### ISSUE TITLE
example of jdbc operator usage

### ISSUE THREAD

**Issue by fabrice-etanchaud** [treasure-data/digdag#1318]
Hi, I read there is an undocumented jdbc operator.
Could you please provide us with an example ?
What are the parameters, and where to copy the jdbc driver ?

Thank you for your great tool !

**Comment by hiroyuki-sato** [comment]
Hello, @fabrice-etanchaud 

What document(or source) did you read?
IIUC, digdag-core provides two database operators (PostgreSQL/Redshift) and doesn't provide JDBC operator.

As far as I know, a third-party developer provide a custom JDBC operator called [digdag-plugin-myjdbc](https://github.com/katsuyan/digdag-plugin-myjdbc)

I'm listing third party plugin on [this page](https://dev.to/hiroysato/digdag-workflow-engine-link-collection-13hf).

**Comment by fabrice-etanchaud** [comment]
Thank you @hiroyuki-sato, that's exactly what I was looking for !
Best regards from France,
