### ISSUE TITLE
"password_override" option in redshift operator

### ISSUE THREAD

**Issue by skokado** [treasure-data/digdag#1328]
I found an issue in document, `password_override` option of `redshift` operator.

[redshift>: Redshift operations](http://docs.digdag.io/operators/redshift.html#options)

- Name of the secret key used by default

-> `aws.redshift.password`, not `redshift.password`

- Description of how to specify `password_override` value in option document

-> In case below, 

```
password_override: another_password
```

it will be used `aws.redshift.another_password` secret key actually. (I checked this in v0.9.40)
In document, it is written as `redshift.another_password`.

**Comment by yoyama** [comment]
The PR has been already merged. I close.
