### ISSUE TITLE
[Feature Request] Support rollbacking in migration

### ISSUE THREAD

**Issue by hiro-o918** [treasure-data/digdag#1433]
Currently, [Migration](https://github.com/treasure-data/digdag/blob/6f753b9b11bdddc3c214c66c1da201ae283bc2af/digdag-core/src/main/java/io/digdag/core/database/migrate/Migration.java) interface does not have a rollback method.
[DatabaseMigrator](https://github.com/treasure-data/digdag/blob/6f753b9b11bdddc3c214c66c1da201ae283bc2af/digdag-core/src/main/java/io/digdag/core/database/DatabaseMigrator.java) also dose not check if the conducted migrations are valid for the version of digdag.

As a result, if some problems are occurred in deployment and the deployment is rollbacked, 
the DB state will not be suitable for the rollbacked version.
So, rollbacking in migration is very important for safe development.

**Comment by yoyama** [comment]
I can understand your request. 
But I recommend do backup before running migration.
I close this ticket but if you still need, pls re-open again.
