### ISSUE TITLE
After setting basic authentication I get empty web UI

### ISSUE THREAD

**Issue by scotty3005** [treasure-data/digdag#1479]
Hi all, 

after setting the basic authentication configuration in the server property file, I can successfully user the digdag cli, but I cannot operate through the web UI anymore. 
In particular when I try to access the endpoint with my browser I get an empty UI and no prompt for the authentication. I have tried as well to embed the username and password in the HTTP address but I get the same out come.
I would be glad if anyone could advice me on this. Thanks!

**Comment by hiroyuki-sato** [comment]
Hello, @scotty3005 

Could you try this example?
https://gist.github.com/hiroyuki-sato/229302a1867025876de7fd1d8ffa2bf1

**Comment by scotty3005** [comment]
Hi @hiroyuki-sato,

that fixed the issue. Thank you very much!
