### ISSUE TITLE
integration tests should run using postgresql

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#151]
Currently the `TemporaryDigdagServer` used by integration/acceptance tests in `digdag-tests` use the default in-memory DB. This is convenient as the DB is isolated per test by definition so tests can trivially run in parallel and there's no DB cleanup that needs to be done. However, for the integration/acceptance tests to provide more confidence in digdag functioning in an actual production setup with a postgres backend the tests should ideally utilize a real postgres instance.

We're already spinning up a postgres instance when running tests, we just need to make use of it. `TemporaryDigdagServer` should generate a new empty database for every run to provide the same isolation properties as the in-memory DB. After the test run is completed, the DB can simply be dropped.

**Comment by yoyama** [comment]
I think this issue had been alreday resolved because digdag-tests are executed with postgresql.
I close this, but feel free to re-open if there is something requirement .
