### ISSUE TITLE
【Feature request】!include ${variable}

### ISSUE THREAD

**Issue by t-kazu** [treasure-data/digdag#1529]
# Details
error when run !include ${variable}.
I want you to be able to run it.

## run
```
!include : ${file_path}
```

## error
```
error: ${filepath} (no such file)
```

**Comment by hiroyuki-sato** [comment]
Hello, @t-kazu 

Maybe, you can use some alternative ways.
Please take a look https://github.com/treasure-data/digdag/issues/990#issuecomment-463544061

**Comment by t-kazu** [comment]
@hiroyuki-sato 

Thanks for the reply.
I think pattern. That is digdag secrets with _env.

## For example
```
+task1:
  if>: ${pattarn='A'}
  _do:
    _env:
       HOGE: ${secrets:hoge}
   sh>: hogehoge
  _else_do:
    if>: ${pattarn='B'}
    _do:
      _env:
         HOGE: ${secrets:hoge2}
      sh>: hogehoge
 ```
 
 I want to put a different value in HOGE.
 What should I do?

**Comment by hiroyuki-sato** [comment]
Hello, @t-kazu 

Maybe I don't understand your use case completely.
What do you think the following?

```
digdag secrets --project hoge --set foo1=FOO1
digdag secrets --project hoge --set foo2=FOO2
```

```yaml
+task1:
  sh>: ./test.sh
  _env:
    FOO: ${secret:foo${val}}
```

```bash
#!/bin/sh

echo "FOO ==> $FOO"
```

```
digdag start hoge hoge --session now -p val=2

FOO ==> FOO2
```

```
digdag start hoge hoge --session now -p val=1

FOO ==> FOO1
```

I tested it in digdag 0.10.0

**Comment by t-kazu** [comment]
thank you. this is good idea. 
I can use variables when call secrets,  solve it.
