### ISSUE TITLE
digdag on window; sh> doesn't work

### ISSUE THREAD

**Issue by seanxz1124** [treasure-data/digdag#1540]
Hi,

Is it possible for someone taking a look at my issue here?
https://stackoverflow.com/questions/66415245/digdag-shell-script-tasks-complete-instantaneously

To provide another example:

_export:
  sh:
    shell: ["powershell.exe"]

+setup:
  sh>: step1.ps1

+finish:
  echo>: finish ${session_time}

In step1.ps1, I just sleep for 5 seconds. But the second task starts immediately without waiting. I do not know what is wrong with my workflow. Could someone please adivse?

Thanks,
Sean

**Comment by hiroyuki-sato** [comment]
Hello, @seanxz1124 

* Have you ever tried the following? [sh operator options](http://docs.digdag.io/operators/sh.html#options)
* What digdag version are you using? 

I saw a user can't work `sh>` operator with PowerShell properly using digdag 0.10.X. It worked 0.9.23. If you use digdag 0.10.X, could you try 0.9.23? 

```yaml
_export:
  sh:
    shell: ["powershell.exe", "-"]

+step1:
  sh>: step1.exe

+step2:
  sh>: step2.ps1
Next  Previous
```

**Comment by seanxz1124** [comment]
> Hello, @seanxz1124
> 
> * Have you ever tried the following? [sh operator options](http://docs.digdag.io/operators/sh.html#options)
> * What digdag version are you using?
> 
> I saw a user can't work `sh>` operator with PowerShell properly using digdag 0.10.X. It worked 0.9.23. If you use digdag 0.10.X, could you try 0.9.23?
> 
> ```yaml
> _export:
>   sh:
>     shell: ["powershell.exe", "-"]
> 
> +step1:
>   sh>: step1.exe
> 
> +step2:
>   sh>: step2.ps1
> Next  Previous
> ```

The example in documentation will crash: shell: ["powershell.exe", "-"]
I need change it to shell: ["powershell.exe"]

I'm running 0.10.0

How to download 0.9.23?
I downloaded the latest version by following this page: http://docs.digdag.io/getting_started.html
PowerShell -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::TLS12; mkdir -Force $env:USERPROFILE\bin; Invoke-WebRequest http://dl.digdag.io/digdag-latest.jar -OutFile $env:USERPROFILE\bin\digdag.bat}"

**Comment by hiroyuki-sato** [comment]
You can download the latest digdag from this page. `digdag` supports `selfupdate` command. but AFAIK, It doesn't work correctly on windows environment.
https://dl.bintray.com/digdag/maven/

First question answer.
Does your Python script exist status non-zero?
Digdag will fail if a command returns non-zero.

**Comment by seanxz1124** [comment]
Thanks. I should not download the latest version, right? You suggested that I should try 0.9.23.

I modified my Python script (first task) to just raise ValueError, and the second task still runs immediately after the first task runs. So I think the problem is with sh>.

**Comment by seanxz1124** [comment]
I downloaded 0.9.42 and it's working for me now.

Thanks!

**Comment by hiroyuki-sato** [comment]
Yes. `0.9.23`  incorrect. `0.9.42` correct version number. 

Could you write the detail the problem on (ex. sample script and stack trace) 0.10.0?
