### ISSUE TITLE
Scheduler error : Resource already exists

### ISSUE THREAD

**Issue by LorisDeBiasi** [treasure-data/digdag#1542]
Hi, I'm trying to setup digdag so that it stores the workflows execution.

The first time I run the scheduler while saving to an h2 database everything is fine, but if I stop the scheduler and start it again, I get this:
```
Caused by: io.digdag.core.repository.ResourceConflictException: Resource already exists: revision=1 in project id=1
```

Someone had the same issue #150, but it was closed without having an answer.

Isn't it possible to load the files if they exist ?

I just want to be able to reload them in case digdag or my server crashed.

--------

If you want to reproduce the error, those are the test file I'm using:

server.properties
```
server.task-log = ./logs
database.type = h2
database.path = ./digdag_db
```

test.dig
```
timezone: UTC

schedule:
  minutes_interval>: 1

+step0:
  sh>: echo "test"
```

I run everything with the scheduler:
```
digdag scheduler --config server.properties
```

**Comment by hiroyuki-sato** [comment]
Hello, @LorisDeBiasi. Thank you for your comment.

I recommend you use 

* server mode instead of the scheduler. (Because It does not well maintain. )
  * Please see the mode compare table. (https://github.com/treasure-data/digdag/issues/150#issuecomment-235552988)
* PostgreSQL instead of H2 DB.

**Comment by LorisDeBiasi** [comment]
Hello @hiroyuki-sato. Thank you for your response.

Everything seems to work fine with the server mode and PostgreSQL as database.
