### ISSUE TITLE
[Question] Support for APM java Agent  with a JVM argument

### ISSUE THREAD

**Issue by t-kazu** [treasure-data/digdag#1612]
I want to add javaagent when starting digdag server.

How can I adapt javaagent option?
```
-javaagent:/full/path/to/hoge.jar
```

**Comment by hiroyuki-sato** [comment]
Hello, @t-kazu 

As far as I know, nobody ever tried for that.
Let's hack the code.

**Comment by t-kazu** [comment]
I solved the problem using the following method.

```
$ digdag -J-javaagent:/full/path/to/hoge.jar server --disable-executor-loop --disable-local-agent --disable-scheduler --config /etc/digdag/server-rest.properties
```

I installed APM java Agent with `-J` option when I started the digdag server.

**Comment by hiroyuki-sato** [comment]
@t-kazu Thank you for sharing your TIPS!
