### ISSUE TITLE
Can't read logs on Firefox

### ISSUE THREAD

**Issue by seiyab** [treasure-data/digdag#1623]
# Description
Cannot read logs on Firefox.
It shows strange texts.

# Actual behavior
## Workflow definition
```yaml
timezone: UTC

+step1:
  echo>: foo

+step2:
  echo>: bar

+step3:
  echo>: bar
```

## Firefox
<img width="1019" alt="Screen Shot 2021-08-05 at 22 01 36" src="https://user-images.githubusercontent.com/20365512/128354233-b298c90e-6038-4a86-8548-c351f6c0abea.png">

## Chrome

<img width="968" alt="Screen Shot 2021-08-05 at 22 02 14" src="https://user-images.githubusercontent.com/20365512/128354290-597b6d76-8cd4-4ea8-922d-918f9352dc2f.png">

# Version
- digdag: current master branch 99c38452cfe1dd62042e6e4 (0.10.2)
- Firefox: 88.0 (64-bit)

# Other information
Error message in console
> Uncaught (in promise) Error: offset is outside the bounds of the DataView
    onmessage untar.js:1
    r untar.js:1
    i untar.js:1
    e untar.js:1
    r untar.js:1
    value model.js:338
    promise callback*value/< model.js:337
    promise callback*value model.js:333
    value console.jsx:935
    callback console.jsx:1025
    callback Component.js:38
    setTimeout handler*t/r.start Component.js:43
    callback Component.js:39
    setTimeout handler*t/r.start Component.js:43
    value Component.js:56
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 7
    value console.jsx:2185
    promise callback*value console.jsx:2183
    value console.jsx:2168
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 7
untar.js:1:1120

**Comment by hiroyuki-sato** [comment]
Hello, @seiyab 

Thank you for your report.
I reproduced this issue in my environment.

* Digdag: 0.10.2
* OS: macOS 11.4
* Java: 1.8.0_291
* Firefox: 89.0.2
* Google Chrome: 92.0.4515.131

```
mkdir /tmp/digdag
digdag server -O /tmp/digdag -m
```

```
digdag init test
cd test
digdag push
digdag start test test --session now
```

And access http://localhost:65432/sessions/1#logs-+test+repeat1

**Comment by seiyab** [comment]
I bisected and it happens since this commit https://github.com/treasure-data/digdag/pull/591

**Comment by ehaupt** [comment]
In Firefox 94.0.2 this seems to be no longer an issue.

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt 

Thank you for your report!! I also confirmed In Firefox 94.0.2 resolve this issue.
@seiyab Could you test in your environment?

**Comment by seiyab** [comment]
It works fine upgrading Firefox to 94.0.2.
Thank you for notifying!
