### ISSUE TITLE
How to continue rest tasks on a task error

### ISSUE THREAD

**Issue by mattp0123** [treasure-data/digdag#1625]
```
+task_1:
  ......
  
+task_2:
  ......
```
  
How to make sure the execution of task_2 will continue if task_1 failed?

**Comment by hiroyuki-sato** [comment]
Could you tell me more detail your issue. I don't understand your question?
Maybe, fix `task_1` and rerun the same digdag command.

**Comment by mattp0123** [comment]
@hiroyuki-sato Is there a workflow option like `continue-on-error` in GitHub Action? https://qmacro.org/autodidactics/2020/07/21/continue-on-error/

**Comment by hiroyuki-sato** [comment]
As far as I know, no such option in Digdag.
If you use `sh>` operator, probably you can use `|| :`

**Comment by mattp0123** [comment]
@hiroyuki-sato It works! Thank you!

More question: Is there any way I can achieve this:
```
_export:
  has_error: false
  failed_tasks: _
  
+task_1:
  sh>: ..... || mutate has_error to true and add task_1 to failed_tasks
  
+task_2:
  sh>: ..... || mutate has_error to true and add task_2 to failed_tasks

+error_check:
  if>: ${has_error}
    _do:
      fail>: ${failed_tasks}
      
_error:
  sh>: send error notification with ${failed_tasks}
```

**Comment by hiroyuki-sato** [comment]
`|| :` means always success in previous `sh` command even the script failed.
It is impossible to set the parameter in the `sh>` operator. Instead(At least), you have two choices

1. Use built-in `py>` or `rb>` operator.
2. Use 3rd party [`sh_result>`](https://github.com/takemikami/digdag-plugin-shresult)

Those operators support set variables like `${failed_tasks}`
