### ISSUE TITLE
How to set working directory for entire dig?

### ISSUE THREAD

**Issue by vnktsh** [treasure-data/digdag#1634]
Hello right now, the default working directory is at `/tmp/digdag-tempdirxxx/workspace/`.

Is there an easy and quick way to change this?

Setting `_workdir: <work-path>` gives me model validation error
```
2021-09-03 05:01:38 +0000: Digdag v0.9.40
Creating .digdag/tmp/archive-6621367414052580682.tar.gz...
error: Validating project failed
workflow /home/ubuntu/example.dig Workflow 'example' includes unknown keys: [_workdir] (model validation)
```

**Comment by hiroyuki-sato** [comment]
Hello, @vnktsh 

Digdag isolates the working directory intentionally.
So, basically, you can't change a directory except for some operators (ie.`sh>`).

Ref: #785

**Comment by vnktsh** [comment]
@hiroyuki-sato Thank you Hiro for the clarification. I have made workaround by doing `cd ${workspace}` for every `sh>:` operator.

Example:

```
_export:
  workdir: "/home/ubuntu/project/"

+run:
  +update-git:
    sh>: cd ${workdir} && git checkout master && git pull origin master

  +task:
    sh>: cd ${workdir} && python parser.py
```
