### ISSUE TITLE
digdag disable - Cannot build RestScheduleSummary, some of required attributes are not set [project]

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [treasure-data/digdag#1650]
When trying to run the `digdag disable` command (`digdag disable my-project -e $HOST:$PORT`) I am running into the following error:

```
error: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.digdag.client.api.ImmutableRestScheduleSummary`, problem: Cannot build RestScheduleSummary, some of required attributes are not set [project]
 at [Source: (org.jboss.resteasy.client.jaxrs.internal.ClientResponse$InputStreamWrapper); line: 1, column: 258] (response processing)
```

**Current DigDag version:** 0.10.3
**Java version:** JDK 11.0.12+0
**OS:** MacOS Catalina

This is pretty important to me, as I want to automatically disable my `dev` project for cost reduction. 

Any feedback would be much appreciated.
Cheers

**Comment by FredericoCoelhoNunes** [comment]
The error message seems to indicate that the "project" attribute is missing; perhaps there was some change in the way the arguments are parsed for this command, and it is not detecting the first argument as the project?

If there's any additional information I can provide, please let me know!

**Comment by hiroyuki-sato** [comment]
Hello, @FredericoCoelhoNunes Could you tell us more reproduction steps.

In my environment.

* macOS: 11.6
* digdag: 0.10.3
* Java: 11.0.12


test.dig

```yaml
schedule:
  minutes_interval>: 1

+task1:
  echo>: ${session_time}
```

```
% digdag server -m
```

```
digdag push disable_test
2021-10-04 20:06:14 +0900: Digdag v0.10.3
Creating .digdag/tmp/archive-8053323234080642508.tar.gz...
  Archiving test.dig
Workflows:
  test.dig
Uploaded:
  id: 1
  name: disable_test
  revision: f16c262f-766b-4ae7-b7c2-7139b368c198
  archive type: db
  project created at: 2021-10-04T11:06:17Z
  revision updated at: 2021-10-04T11:06:17Z

Use `digdag workflows` to show all workflows.
```


```
digdag disable disable_test
2021-10-04 20:07:04 +0900: Digdag v0.10.3
Disabled schedule id: 1
```

```
digdag disable disable_test -e localhost:65432
2021-10-04 20:12:12 +0900: Digdag v0.10.3
Disabled schedule id: 1
```

**Comment by FredericoCoelhoNunes** [comment]
Hi @hiroyuki-sato , my apologies for wasting your time.
I just noticed that I updated my client version to 0.10.3 but my server was still running 0.9.42, which is most likely where the error was coming from. Tested with a local Docker deployment (both 0.10.3) and it worked.

Can close the issue. Thanks a lot for your quick reply

**Comment by hiroyuki-sato** [comment]
Hello, @FredericoCoelhoNunes 
I'm glad it was resolved! Could you close this issue by yourself? Thanks.
