### ISSUE TITLE
[digdag-ui] Task RESUME button does not work properly

### ISSUE THREAD

**Issue by shoot16625** [treasure-data/digdag#1666]
`RESUME` button does not work properly since `digdag version : 0.10.*` 
(`command: digdag enable` works fine.)

<img width="1243" alt="スクリーンショット 2021-10-22 1 02 21" src="https://user-images.githubusercontent.com/24419610/138315920-51efb316-5ffb-430d-a821-58c2dc5ab89c.png">

**Comment by hiroyuki-sato** [comment]
Hello, @shoot16625 It seems that the issue is duplicate #1648. Could you check the error message? If the same output, it will fix in 0.10.4.

**Comment by shoot16625** [comment]
Thank you for your contact!!
