### ISSUE TITLE
Digdagignore disables digdag run

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [treasure-data/digdag#1670]
I had been waiting for the .digdagignore functionality for a while, so that I could have DAGs in my repository that wouldn't be pushed to the production server (in my case, test DAGs that I only want to run locally and on my CI/CD pipeline).

However, I am now testing the .digdagignore file, and even thought it does in fact prevent the DAGs from being pished, it also makes it so that I cannot run the DAGs locally (`error: Workflow <...> does not exist in current directory. You may need to change directory first, or set --project option. (resource not found)`)

Is there any way to go around this issue? Otherwise, I will have to implement some hack to delete the test .dig files dynamically before pushing to the production server!

Thanks

**Comment by seiyab** [comment]
NOTE: Though it is intended, the message might be confusing and can be improved.
```
% digdag run test.dig
2021-10-25 22:17:10 +0900: Digdag v0.10.3
error: Workflow 'test' does not exist in current directory. You may need to change directory first, or set --project option. (resource not found)
```
