### ISSUE TITLE
BUG: /api/projects does not support pagination

### ISSUE THREAD

**Issue by ehaupt** [treasure-data/digdag#1672]
I'm using an instance that has many projects pushed to. When I was trying to cleanup old projects I noticed that `/api/projects` lacks pagination. I cannot list more than 100 projects. In my case there are way more projects (at least by the factor 3) and I have no way of listing them.

I noticed an old issue (https://github.com/treasure-data/digdag/issues/1106) that was deferred to (https://github.com/treasure-data/digdag/pull/1173) which was also closed without resolution.

I think pagination support is essential for all endpoints that limit the output.

**Comment by ehaupt** [comment]
Friendly ping @hiroyuki-sato.

We are operating with many projects that require periodic cleanups. Not having pagination with `/api/projects` leaves us no choice than to query the db. Just to give an idea:

```
digdag=> select count(*) from projects where deleted_name is null;
 count
-------
  2706
(1 row)
```

**Comment by hiroyuki-sato** [comment]
Hello, @ehaupt. Have you ever checked #1697? It merged a few days ago.  And It contains the following change.

> * GET /api/projects supports count and last_id to change number of return and pagination like /api/workflows.

**Comment by ehaupt** [comment]
@hiroyuki-sato, thank you for the reference. This is fantastic news.

**Comment by toru-takahashi** [comment]
Hello @ehaupt 
thank you for your feedback.
Just in case, Hiroyuki-sato is not a maintainer of this project and any contracts with this project.
He helps digdag users with his truly kindness at his private time. Please do not mention a specific person in the next time.

Thank you,

**Comment by hiroyuki-sato** [comment]
Hello, @toru-takahashi and @ehaupt 

Don't worry about that. As @toru-takahashi  told @ehaupt , I'm not a maintainer of this project. But I'll support this project as much as possible. 😄
