### ISSUE TITLE
How to pass the args to the python constructor?

### ISSUE THREAD

**Issue by tommarute** [treasure-data/digdag#1675]
Hi team,

I'd like to pass the args to the python constructor without using the args of any instance method.
Is it possible?

Here is simple python code for sample (sample.py):

```python
class MyClass:
    def __init__(self, version=2):
        self.version = version

    def print_version(self):
        if self.version == 1:
            print('Called with v1.')
        elif self.version == 2:
            print('Called with v2.')
        else:
            print('Unknown version.')
```

How can I write `.dig` file If I need to instantiate with setting version 1? (i.e. `MyClass(version=1)`)

I only know basic syntax of `.dig` file like below. Of course I can not pass any args to the constructor by this way.

```
+python:
  py>: sample.MyClass.print_version
```

I appreciate if you could give me any hints.

Thanks,

**Comment by hiroyuki-sato** [comment]
Hello, @tommarute 

Have you ever tried `digdag init -t python foo` as an example?
It passes some arguments to Python.

**Comment by tommarute** [comment]
Hi @hiroyuki-sato,

Thank you for your reply. :smile:

I checked the files generated by `digdag init -t python foo`.
As you said, We can pass some args to the instance method of python. 
But in my case, I need to pass the args to the constructor directly when the class is instantiated.

**Comment by hiroyuki-sato** [comment]
Hello, @tommarute 

I'm not familiar with Python. I hope you will understand what digdag do inside `py>` operator.

Digdag executes `runner.py` with the following arguments if you use `py>` operator.

https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/resources/digdag/standards/py/runner.py

sys.argv 

* `sys.argv[0]`: `.digdag/tmp/digdag-py-11-319525413459438877/runner.py`
* `sys.argv[1]`: `scripts.myclass.MyClass.say_something`
* `sys.argv[2]`: `digdag/tmp/digdag-py-11-319525413459438877/input.json`
* `sys.argv[3]`: `.digdag/tmp/digdag-py-11-319525413459438877/output.json`

**Comment by ehaupt** [comment]
Hello @tommarute

You may pass keyword arguments like this:

```yml
+python:
  py>: sample.MyClass.print_version
  version: "3"
```

**Comment by tommarute** [comment]
@hiroyuki-sato 

Thank you for your information. :)

**Comment by tommarute** [comment]
@ehaupt 

Thank you for the comment.
I confirmed I can pass `version` to the constructor of `MyClass` by using the code you mentioned.

I completely thought that there is difference of the way to pass the args to the constructor or the instance method...

Thanks again!
