### ISSUE TITLE
[BUG] Concurrent update in table "QUEUED_TASK_LOCKS": another transaction has updated or deleted the same row

### ISSUE THREAD

**Issue by hankkuu** [treasure-data/digdag#1686]
![image](https://user-images.githubusercontent.com/7829802/148708170-7753d92c-0f70-4c3c-82df-71c9ee03b1fb.png)

**An error occurs in digdag core**

An error occurs in digdag core, The point of occurrence occurs when the data transfer is finished and This is the point at which the task should end normally.

at io.digdag.core.database.DatabaseTaskQueueServer.deleteTask(DatabaseTaskQueueServer.java:217)
at io.digdag.core.queue.QueueTaskQueueDispatcher.taskFinished(QueueTaskQueueDispatcher.java:59)
at io.digdag.core.workflow.WorkflowExecutor.taskSucceeded(WorkflowExecutor.java:1217)

The expected reason is that I wonder if this can happen when there are many tables that need to be migrated in the workflow.

**Comment by hiroyuki-sato** [comment]
Hello, @hankkuu 

Thank you for reporting this issue.

I'm not sure the root cause, but you would better use PostgreSQL instead of H2 DB.

* What Digdag version are you using?
* What workflow did you use?
* Could you provide reproduce steps?
