### ISSUE TITLE
Shell script added in the out section of embulk task invoking multiple times.

### ISSUE THREAD

**Issue by revanna7226** [treasure-data/digdag#1687]
Hi All,

Hope you are doing great! and Thank you all for reading this issue!
My intension is to delete the older sessions stored in digdag database() and task logs and access logs file created on the server.
The Workflow added in the Digdag Project has a embulk task which has a input and output sections as below.
in:
{% include 'in_postgres' %}
  query:
    "SELECT 1"
  after_select:
    "DELETE FROM task_archives WHERE id IN (SELECT id FROM session_attempts WHERE created_at < '{{env.OFFSET_DATE}}');
     DELETE FROM session_attempts WHERE created_at < '{{env.OFFSET_DATE}}';
     DELETE FROM sessions WHERE last_attempt_created_at < '{{env.OFFSET_DATE}}';"
out:
 type: command
 command: cat -|./removing_etl_logs.sh {{env.OFFSET_DATE}}
 formatter:
  type: csv
And the digdag workflow definition is as below,
timezone:
 Asia/Hong_Kong

schedule:
 skip_on_overtime: true
 cron>: "0 1 * * *"

_export:
 !include : 'now.yml'
 OFFSET_DATE: ${moment(DATE_OFFSET).add(0, 'minutes').format("YYYY-MM-DD")}

+removing_old_sessions_and_logfiles:
 _env:
  PGS_PASSWORD: ${secret:PGS_PASSWORD}
 sh>: embulk run removing_etl_logs.yml.liquid

And removing_etl_logs.sh file contains the necessary logic to delete the log files from access and task directory based on the offset date set.

But, When I run the Workflow, The shell script in the out section is invoking multiple times, first control flow deletes the target file. and second and subsequent execution controls will fails to delete the file and stoping the task stating the error. No file or directory found.
Sample logs messages are as below,

2022-01-10 01:00:05.227 +0800 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-01-10 01:00:05.240 +0800 [INFO] (0018:task-0000): Using command [sh, -c, cat -|./removing_etl_logs.sh 2021-12-11] <-- 1st trigger
++ offset_date=2021-12-11
+++ date -d 2021-12-11 +%s
++ offset_seconds=1639152000
++ server_config=/opt/digdag/server.properties
+++ cat /opt/digdag/server.properties
+++ cut -d= -f2
2022-01-10 01:00:05.265 +0800 [INFO] (0018:task-0000): Using command [sh, -c, cat -|./removing_etl_logs.sh 2021-12-11]  <-- second trigger
+++ grep log-server.local.path
++ task_log_path=/opt/digdag/logs/task
2022-01-10 01:00:05.267 +0800 [INFO] (0018:task-0000): Using command [sh, -c, cat -|./removing_etl_logs.sh 2021-12-11] <-- third trigger
+++ cut -d= -f2
+++ cat /opt/digdag/server.properties
+++ grep server.access-log.path
++ offset_date=2021-12-11
+++ date -d 2021-12-11 +%s
++ offset_seconds=1639152000
++ server_config=/opt/digdag/server.properties
2022-01-10 01:00:05.270 +0800 [INFO] (0018:task-0000): Using command [sh, -c, cat -|./removing_etl_logs.sh 2021-12-11] <-- fourth trigger

error message logs are as below,
++ rm /opt/digdag/logs/access/access.2021-12-11.log
+++ date -d 2022-01-09 +%s
++ access_log_seconds=1639152000
++ '[' 1639152000 -le 1639152000 ']'
++ rm /opt/digdag/logs/access/access.2021-12-11.log
++ access_log_seconds=1639152000
++ '[' 1639152000 -le 1639152000 ']'
++ rm /opt/digdag/logs/access/access.2021-12-11.log
rm: cannot remove ‘/opt/digdag/logs/access/access.2021-12-11.log’: No such file or directory
++ access_log_seconds=1639152000
++ '[' 1639152000 -le 1639152000 ']'
++ rm /opt/digdag/logs/access/access.2021-12-11.log
++ ret=1
++ '[' 1 -ne 0 ']'
++ echo 'Failed to remove file /opt/digdag/logs/access/access.2021-12-11.log'
Failed to remove file /opt/digdag/logs/access/access.2021-12-11.log
++ exit 1
rm: cannot remove ‘/opt/digdag/logs/access/access.2021-12-11.log’: No such file or directory
++ ret=1
++ '[' 1 -ne 0 ']'
++ echo 'Failed to remove file /opt/digdag/logs/access/access.2021-12-11.log'
Failed to remove file /opt/digdag/logs/access/access.2021-12-11.log
++ exit 1

Could you please have look at the above and suggest me? What is causing the issue? What should be the countermeasure?

Thansk and Regards,
Revs

**Comment by hiroyuki-sato** [comment]
I'm not sure whether complete understand your issue, But
you'd better break down the problem.
Have you ever tried to execute Embulk without Digdag?

If the problem doesn't solve in that case, I suppose you need to add the following into the Embulk config.

```yaml
exec:
  min_output_tasks: 1
```

https://www.embulk.org/docs/built-in.html#local-executor-plugin

**Comment by revanna7226** [comment]
Hi @hiroyuki-sato ,

Great!
Thanks for your suggestion. 
I will check it by executing embulk and adding min_output_tasks: 1.
I will write the results here soon.

Thanks,
Revs

**Comment by revanna7226** [comment]
Yes, @hiroyuki-sato, You guessed it right.

This issue is related to Embulk.
Multiple execution of output task is because of multi-core CPU Environment.
We set the below flag as you suggested, to limit the no of execution threads.

exec:
  min_output_tasks: 1

And close the issue.

Thank you!
