### ISSUE TITLE
Cannot reference variables when using if> operator when retry failed

### ISSUE THREAD

**Issue by jon20** [treasure-data/digdag#1704]
## overview

After setting the parameters using the if> operator, the following error will occur when retry failed is executed.
``` Failed to evaluate a variable ${test_env_store} (ReferenceError: "test_env_store" is not defined) (config) ```

I'd like to ask you if this is the expected result.

Thanks.

## example
https://github.com/jon20/test-digdag

## enviroment
Digdag: 0.10.4
Python: 3.7.9

## Execution result
The screenshot below shows the result of the run.
![run](https://user-images.githubusercontent.com/21301977/153127002-8c3cd4c8-5501-48e2-b86e-65521573749c.png)

The screenshot below shows the result of the retry failed. If you check on the UI, the ```+sample+load_environment^sub+do_statement``` task has disappeared

![retry_failed](https://user-images.githubusercontent.com/21301977/153127024-0368caba-ec5f-449d-ba94-0f5503df016b.png)

**Comment by hiroyuki-sato** [comment]
Hello, @jon20 

I don't understand your requirements completely. But have you ever tried the following?
It seems that you don't need to use `_export` in that part.

```yaml
+load_environment:
  if>: true
  _do:
    +do_statement:
      py>: sample.save

+test_task:
#  _export:
#    test_env: ${test_env_store}
  py>: sample.test_task

+test_task2:
  echo>: ${test_env_store}
```

```python
import digdag

def save():
  digdag.env.store({'test_env_store': 'hoge'})

def test_task():
  print("test_env_store: %s\n" % digdag.env.params["test_env_store"])
#  raise Exception("Test Error")
```

```
2022-02-09 17:08:29 +0900 [INFO] (0017@[0:default]+sample+test_task): py>: sample.test_task
test_env_store: hoge

2022-02-09 17:08:30 +0900 [INFO] (0017@[0:default]+sample+test_task2): echo>: hoge
hoge
Success. Task state is saved at /private/tmp/test-digdag/.digdag/status/20220209T000000+0000 directory.
```

**Comment by jon20** [comment]
@hiroyuki-sato  Thanks for the workaround suggestion.
I didn't share the background of using the if operator, so I will share it.

I would like to set different parameters for ```local, development, staging, production``` environments to determine the docker image to be used for subsequent tasks. Also, we want to use docker to execute the task on different images. The implementation image is as follows

```
+load_environment:
  if>: ${environment == 'dev' || environment == 'stg' || environment == 'prd'}
  _do:
    +do_statement:
      _export:
        docker:
          image: ecr_image
          pull_always: true
      py>: sample.set_docker_env
  _else_do:
    +else_statemant:
      _export:
        docker:
          image: self_build_python_image
          pull_always: false
      py>: sample.set_another_docker_env

+test_task:
  _export:
    docker:
      image: ${docker_env.image}
      pull_always: ${docker_env.pull_always}
  py>: sample.test_task

```

Pass parameters when starting the digdag server
```
digdag server --param environment={dev, stg, prd, local}
```

In this implementation, the ```_export``` part cannot be commented out and the error shown in the title will occur

**Comment by hiroyuki-sato** [comment]
IIUC `${}` doesn't evaluate in `_export` part.
It evaluates in each operator (i.e: `sh>` operator.)

These docs may help.

https://github.com/treasure-data/digdag/issues/990#issuecomment-463544061

https://github.com/treasure-data/digdag/issues/1203
