### ISSUE TITLE
Got errors when I try to show logs on the web client

### ISSUE THREAD

**Issue by mattp0123** [treasure-data/digdag#1709]
I got a bunch of network errors when I click on the "REFRESH LOGS" in the Digdag web client.
These errors only occur on task using the "for each loop" and I'm not able to see the logs.
Please help.

![Screen Shot 2022-02-17 at 10 05 57 AM](https://user-images.githubusercontent.com/68014351/154391280-0b8e8449-859e-498c-b0ff-3b453b6fc3e0.png)

**Comment by mattp0123** [comment]
@hiroyuki-sato Thanks for your reply!
### What Digdag version are you using?
I'm using 0.10.4.

### Have you ever tried `digdag log` command?
`digdag log <attemp_id>` works correctly.

### Could you provide reproduced example?
I'm using the following .dig file:
```digdag=
+task:
  for_each>:
    item: [hello, world, foo, bar]
  _parallel: true
  _do:
    sh>: ts-node /path/to/my/task.ts ${item}
```
And my task.ts file:
```javascript=
const [,, item] = process.argv
console.log(item)
process.exit(1)
```

### Could you provide the error log (a stacktrace for example.)
Where can I find Digdag web server logs?

### Does **network errors** mean corrupted the error log file?
No. Log files (.log.gz) are not corrupt.

**Comment by hiroyuki-sato** [comment]
You need to specify a task log path. Launch digdag server with `-O dir` option.

**Comment by mattp0123** [comment]
@hiroyuki-sato

I did specify the task log path when I launch the Digdag server (I'm using supervisord).
There is only one line of log showed up when I click the "REFRESH LOGS" button. (The one http request got 200 OK response instead of 400 Bad Request)

<img width="1314" alt="Screen Shot 2022-02-18 at 11 02 09 AM" src="https://user-images.githubusercontent.com/68014351/154609587-9813a2ee-ef48-4bb1-83f0-e36b0f714700.png">

**Comment by hiroyuki-sato** [comment]
It seems that digdag works correctly in my environment.

```
digdag server -m -O /tmp/log
```

setup digdag client.

```
mkdir foo
cd foo
```

create `bar.dig`

```yaml
timezone: UTC

+task:
  for_each>:
    item: [hello, world, foo, bar]
  _parallel: true
  _do:
    sh>: echo "${item}"
```

```
digdag push foo
digdag start foo bar --session now
```


* digdag server 0.10.4
* OS: macOS 12.2.1
* Java8
* Safari: 15.3

<img width="1212" alt="digdag" src="https://user-images.githubusercontent.com/767650/154621540-050eb4b5-98ad-423a-911e-bdecb9096ea7.png">

**Comment by mattp0123** [comment]
@hiroyuki-sato

I should specify the access log path (-A) if I want to see the error logs from the Digdag server, right?

**Comment by mattp0123** [comment]
> Does refresh log work correctly using my test case?

No, it doesn't 🥲
Only one line of log still.

> Have you ever tried -L option?

I will try this. BTW, the `-L` option is not in the [offical docs](http://docs.digdag.io/command_reference.html#server-mode-commands).

Thank you @hiroyuki-sato

**Comment by mattp0123** [comment]
@hiroyuki-sato

The error from the server:
```
io.undertow.util.BadRequestException: UT000165: Invalid character ^ in request-target
  at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:376)
  at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:242)
  at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
  at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
  at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:148)
  at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
  at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:51)
  at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
  at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
  at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
  at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
  at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
  at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
  at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
```
Looks like the problem is the server does not handle the up arrowhead `^` in the log.gz filename?

**Comment by hiroyuki-sato** [comment]
Hello, @mattp0123 

Did you follow the [this step](https://github.com/treasure-data/digdag/issues/1709?t=1645452143507#issuecomment-1043908536)?
If not, You need to describe the details. What OS(macOS/Linux) did you use? What command did you execute?
Digdag version and so on. We need to find the difference you and my environment.

It seems that you use invalid characters (ex. Non alphabetical path). But I don't know your environment.

Best regards

**Comment by mattp0123** [comment]
@hiroyuki-sato 

I use this command to start digdag server:
```shell=
digdag server -c $HOME/digdag/config.properties -O $HOME/digdag/task-log -L $HOME/digdag/server.log --log-level debug
```
And my config.properties: (Also wonder if the `-O` and `-L` option could be written in the config?)
```
database.type = postgresql
database.user = digdag
database.password = <my-db-password>
database.database = digdag
database.host = localhost
database.port = 5432
```
My env:
- OS: Debian GNU/Linux 10
- Digdag: 0.10.4
- Java: 11

And I use this .dig `~/workflows/task.dig`:
```digdag=
timezone: UTC

+task:
  for_each>:
    item: [hello, world, foo, bar]
  _parallel: true
  _do:
    sh>: echo ${item}
```
Push to the digdag server by running:
```shell=
cd ~/workflows && digdag push test
```
The result:

<img width="931" alt="Screen Shot 2022-02-22 at 12 52 37 AM" src="https://user-images.githubusercontent.com/68014351/154997828-53ee3e72-98db-480e-96d3-407545d38a85.png">

The network errors:

<img width="869" alt="Screen Shot 2022-02-22 at 12 55 23 AM" src="https://user-images.githubusercontent.com/68014351/154998207-e47328f2-dfb1-4971-81af-10a88e869d84.png">

**Comment by hiroyuki-sato** [comment]
Hello, @mattp0123 

Do you use a proxy server?
If so, Could you try the below? (add `-b 0.0.0.0` option when you launch Digdag server). And don't forget to change a firewall configuration.

```
digdag server -c $HOME/digdag/config.properties \
  -O $HOME/digdag/task-log \
  -L $HOME/digdag/server.log \
  --log-level debug \
  -b 0.0.0.0 
```

And access http://youser_server:65432/

I guess you use a proxy server and the sever decode `%5E` as `^`.
Because you access http://52.79.xx.xx/. It is ordinally a web server port(TCP/80), not a Digdag port.

**Comment by mattp0123** [comment]
I use Nginx reverse proxy. After I try to make Nginx not to decode the request, all the request get 200 OK response.

Thank you so much @hiroyuki-sato!
