### ISSUE TITLE
[Question] Is there any way to balance load among digdag instances?

### ISSUE THREAD

**Issue by hiro-hori** [treasure-data/digdag#1727]
Hello. 

We are running digdag v0.10.0 on multiple Amazon EC2s.
We noticed that there is loadaverage bias among instances.
We use same instance type among instances.

Is there any option to balance load among digdag instances?

![スクリーンショット 2022-03-28 12 09 54](https://user-images.githubusercontent.com/16184010/160320441-19b1e0a9-3ccc-40fa-b5e5-40fbc6ad0704.png)

As I imagine, task fetch timing of instance causes this but I don't know cleary why.

I paste our config file below.

```
server.bind=0.0.0.0
database.type=postgresql
database.user=${db_user}
database.password=${db_password}
database.host=${db_host}
database.database=${db_database}
archive.type=s3
archive.s3.bucket=${s3_bucket}
archive.s3.path=${archive_s3_path}
log-server.type=s3
log-server.s3.bucket=${s3_bucket}
log-server.s3.path=${log_server_s3_path}
digdag.secret-encryption-key=${secret_encryption_key}
config.http.max_stored_response_content_size=131072
ecs_task.allow_auth_method_env=true
ecs_task.allow_auth_method_instance=true
executor.task_ttl=3d
api.max_archive_total_size_limit=134217728
api.max_sessions_page_size=700
api.max_attempts_page_size=700
```

And I noticed a parameter `executor.enqueue_random_fetch (enqueue ready tasks randomly. default: false)`. Is this good for us?

Any information would greatly help.

Thanks.

**Comment by komamitsu** [comment]
What's the log message in the 3 Digdag nodes like? Is there any significant differences?

As for `enqueue_random_fetch`, it's to change the order of fetched `tasks` table records on each node and I don't think it would work for this issue.

**Comment by hiro-hori** [comment]
Thank you very much for your reply. 🙏

Mmm... I have checked logs in 3 nodes. There are a lot of task logs but I could not find differences among nodes.

And also, thank you for information about `enqueue_random_fetch`.

**Comment by komamitsu** [comment]
I see.
The load average doesn't show the CPU usage of Digdag process, right? How about checking which process is busy using `top` command or something just in case?

Also, replacing the busy EC2 instance with a new one might be an option.

**Comment by hiro-hori** [comment]
Load average bias become good after recreation of all instances.

Thank you for your cooperation! 🙏
