### ISSUE TITLE
Trigger a workflow execution by requesting the REST API endpoint

### ISSUE THREAD

**Issue by mattp0123** [treasure-data/digdag#1736]
I want to trigger my workflow by requesting the REST API endpoint of my Digdag server. So I follow this docs: https://docs.digdag.io/api/
To trigger a workflow, I have to request the `PUT /api/attempts` endpoint with body like this:
```javascript=
{
  workflowId: <my_workflow_id>,
  sessionTime: <session_time>,
  params: {}
}
```

Could it be like the Digdag client mode command:
```shell=
digdag start my-project my-workflow --session now
```

Something like this?
```javascript=
{
  workflow: { name: 'my_workflow', project: 'my_project' },
  sessionTime: 'now',
  params: {}
}
```

I think the REST API docs could be more detailed BTW.

**Comment by yoyama** [comment]
You can get `<my_workflow_id>` with following APIs

1. Get project ID
   "GET /api/projects?name=my_project"
2. Get workflow ID
   "GET /api/projects/<my_project_id>/workflows/my_workflow
