### ISSUE TITLE
Digdag CLI support Backport API enhancement

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/digdag#1742]
The following commit introduced several new APIs. However, they are not supported by CLI
https://github.com/treasure-data/digdag/pull/1697

Supporting the following by CLI will help users to manage their projects effeciently.

- GET /api/workflows supports name_pattern parameter to search by workflow name. (partial match).
- GET /api/projects supports name_pattern parameter to search by project name. (partial match).
- GET /api/projects supports count and last_id to change number of return and pagination like /api/workflows.

I assign this to @o-mura

**Comment by yoyama** [comment]
The options for them has been introduced in #1778
