### ISSUE TITLE
Digdag CLI to schedule workflow session for a future date/time

### ISSUE THREAD

**Issue by surajthakur** [treasure-data/digdag#1747]
Hi Team, 

I was trying to use `digdag start --session "2022-06-10 13:00:00"` to schedule a task for a future time assuming --session was meant for giving date for future time. But the workflow ran right away (now) with attempt time as now and session time as set in the command. 

There is no schedule set in the workflow. Basically that workflow is an adhoc workflow and does not have a schedule, but when we require, we trigger it using `digdag start --session now`. But now we want to trigger it for a future time using digdag cli itself rather updating the workflow.

Is there a way to do that? 

My digdag version:
2022-06-10 12:09:47 +1000: Digdag v0.10.4
Client version: 0.10.4
Server version: 0.9.42

Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @surajthakur 

If you want to run a task at a specified time, you need to use [`schedule`](http://docs.digdag.io/scheduling_workflow.html) option.
`digdag start` doesn't support scheduling.
