### ISSUE TITLE
How do I point to the parent path?

### ISSUE THREAD

**Issue by nayee2** [treasure-data/digdag#1763]
I can use / for the child path, but I don't know how to point to the parent path.
Using ../ does not work.

**Comment by hiroyuki-sato** [comment]
Hello, @nayee2 

General operators don't allow access to the parent directory. (Except `sh>` operator).

http://docs.digdag.io/concepts.html#workspace

> Plugins will not allow access to parent directories of workspace. This is because digdag server is running on a shared environment. A project should be self-contained so that it doesn’t have to depend on external environments. Scripting operator is an exception (e.g. sh> operator). It’s recommended to run scripts using docker: option.
