### ISSUE TITLE
[feature-request] Oracle operator

### ISSUE THREAD

**Issue by doctor** [treasure-data/digdag#1764]
Hello,
Can you please implement Oracle operator?
I tried to use the digdag-plugin-myjdbc and then attempted to modify it to use for Oracle. No luck due to the ConnectionConfig not accepting jdbc url or service name for the Oracle database instead of the standard host, port, etc. I am getting Invalid URL exception from openConnection()
I am currently accomplishing the tasks using py operator... having a dedicated operator would greatly increase the productivity.
Thank you!

**Comment by hiroyuki-sato** [comment]
Hello, @doctor. it's a good chance for you to create a new plugin by yourself.
You can fork and modify [digdag-plugin-myjdbc](https://github.com/katsuyan/digdag-plugin-myjdbc).

[These plugins](http://docs.digdag.io/community_contributions.html) are developed by community contributors (not the digdag project).
