### ISSUE TITLE
Unable to kill node.js task

### ISSUE THREAD

**Issue by mattp0123** [treasure-data/digdag#1766]
If a node script ran like this:
```javascript
(function wait () {
  setTimeout(wait, 1000);
})()
```
It can't be killed (by digdag client kill command or clicking the kill button on dashboard).

**Comment by hiroyuki-sato** [comment]
Hello, @mattp0123 

`kill` command doesn't stop the task immediately.
It stops the workflow **after** current task is finished.

**Comment by mattp0123** [comment]
Thanks for your reply.
> `kill` command doesn't stop the task immediately. It stops the workflow **after** current task is finished.

So what am I supposed to do to stop the task immediately?

**Comment by hiroyuki-sato** [comment]
Hello, @mattp0123 

IIUC, you need to wait for the task completion.

For example, If you kill the BigQuery session in the `bq>` operator,
There is no guarantee to kill the session on the BigQuery side.
In that case, the query still runs on the unmanaged area.
