### ISSUE TITLE
Avoiding unexpected override of local parameters

### ISSUE THREAD

**Issue by frsyuki** [treasure-data/digdag#214]
I think that this behavior of following workflow is unexpected for most of users:

```
_export:
  schema: {test: "int"}  # I want to use this variable at a later task
  pg:
    host: mytank
    database: mydb
    user: pg
    password: password_of_pg

+load_to_tank:
  td>: load.sql
  result_url: ...

+query:
  pg>: query.sql
  #=> This operator fails because "schema" must be string but it is an object
```

A confusion is that `pg>` operator merges all export (and store) parameters with local parameters. I think users will expect that parameters only in `pg:` key are used for `pg>:` operator. But actually, top-level parameters are also used.

How about excluding top-level parameters from merging?

Related:
- https://github.com/treasure-data/digdag/pull/112#issuecomment-225278567
- https://github.com/treasure-data/digdag/pull/185

**Comment by danielnorberg** [comment]
Agreed 👍

**Comment by komamitsu** [comment]
Yeah, this issue should be addressed, I think too.

But in the following case, I noticed that parameters(`host`, `database` and `user`) defined with `pg:>` operator seem as the same scope level with top-level parameters in `request.getConfig()`.

```
timezone: "Asia/Tokyo"

_export:
  schema: {test: "int"}

+step1:
  pg>: simple.sql
  host: localhost
  database: postgres
  user: komamitsu
```

```
{"timezone":"Asia/Tokyo","session_uuid":"1f69ec16-89ec-43f9-821a-ad54d6b89552",
"session_time":"2016-09-23T20:35:23+09:00","session_date":"2016-09-23",
"session_date_compact":"20160923","session_local_time":"2016-09-23 20:35:23",
"session_tz_offset":"+0900","session_unixtime":1474630523,"project_id":1,
"schema":{"test":"int"},
"pg>":"simple.sql",
"host":"localhost","database":"postgres","user":"komamitsu","_type":"pg","_command":"simple.sql"}
```
Is there any way to distinguish parameters defined with `pg:>` operator from top-level parameters defined in `_export:`? @frsyuki @danielnorberg

**Comment by frsyuki** [comment]
@komamitsu `TaskRequest.getConfig` has all merged parameters (=revision + session + store + export + local). `TaskRequest.getLocalConfig` has only local config.

**Comment by yoyama** [comment]
@komamitsu  I will close this PR because no progress for long time. Feel free to reopen if needed.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
