### ISSUE TITLE
strftime with variable

### ISSUE THREAD

**Issue by frsyuki** [treasure-data/digdag#215]
Formatting timestamp is one of the common use cases of `${...}` expression.
Vanilla JavaScript doesn't have good support for it.
Having a strftime library such as https://github.com/samsonjs/strftime as a built-in library should be useful.

Discussions are:

* How should we recommend users to convert session_time (string) to a Date object?
* How to set default timezone? (I think users will expect that `timezone: ` parameter is used as the default timezone).

**Comment by uu59** [comment]
👍  for having it.

FWIW, let me share my case.
I need to calculate "N days ago from session_time (not last_session_time)" and format it as '%Y-%m-%d' in a workflow.
I did it by `${(d=new Date((session_time - (86400 * N)) * 1000) && [d.getFullYear(), ('0' + (d.getMonth()+1)).slice(-2), ('0' + d.getDate()).slice(-2)].join('-')}`. It worked but it has 4 complexity:
- Formatting (`[d.getFullYear(), ...].join`). strftime will solve this!
- Converting seconds to milli seconds (`new Date((session_time ...) * 1000)`)
- Calculating date. `session_time - (86400 * N)` almost work but roughly.
- Can't assign variable without hack (`(d=new Date(...)) && ....`)

Other popular time library [moment.js](http://momentjs.com/) can do converting and avoid assigning variable.
Above one liner can be rewritten with moment.js as `${moment(session_time * 1000).add(-N, 'days').format('YYYY-MM-DD')}`. It's much simpler.
Probably typical user (including me) prefer strftime for formatting, but moment.js can do more work.

**Comment by westwick** [comment]
:+1: would also like something like this

**Comment by frsyuki** [comment]
I checked several libraries:

* strftime: https://github.com/samsonjs/strftime
* Moment.JS: http://momentjs.com/
* XDate: http://arshaw.com/xdate/
  * maintenance mode: http://blog.arshaw.com/1/post/2013/03/xdate-08-and-future-development.html
* Datejs: http://www.datejs.com/
* d3-time-format: https://github.com/d3/d3-time-format

I first thought that simple `strftime` is the best. However, I found that it can't cover following common operations well:

* Reformatting `session_time`, `next_session_time`, and `last_session_time` in custom format
* Format tomorrow's time
* Adding N hours for each loop
* Using different time zones

On the other hand, Moment.JS seems quite feature complete:

```
$ jirb 
> js = Java::jdk.nashorn.api.scripting.NashornScriptEngineFactory.new.getScriptEngine("--no-java", "--no-syntax-extensions", "-timezone=Asia/Tokyo")
> js.eval(File.read('moment.js')
> js.eval(%{moment("2016-09-27T00:00:00Z").format()})
=> "2016-09-27T09:00:00+09:00"
> js.eval(%{moment("2016-09-27T00:00:00Z").format("YYYY-MM-DD HH:mm:ss Z")})
=> "2016-09-27 09:00:00 +09:00"
> js.eval(%{moment("2016-09-27T00:00:00Z").utc().format("YYYY-MM-DD HH:mm:ss Z")})
=> "2016-09-27 00:00:00 +00:00"
> js.eval(%{moment("2016-09-27T00:00:00Z").utc().add(1, 'hours').format("YYYY-MM-DD HH:mm:ss Z")})
=> "2016-09-27 01:00:00 +00:00"
```

@danielnorberg @komamitsu I think bundling Moment.js makes sense. Do you have any ideas around?

**Comment by danielnorberg** [comment]
Moment is pretty nice. We're using it in the console.
