### ISSUE TITLE
[feature-request] JSR352 aka JBatch integration (implementing Batchlet / Chunk processing operator)

### ISSUE THREAD

**Issue by nuzayats** [treasure-data/digdag#225]
I'd like to write some application logic (e.g. bulk processing against RDBMS) with Java, as an Digdag operator. in such a case, it would be nice if Digdag supports JSR352 (JSR-352 Batch Applications for the Java Platform) based code.

I think those operators would be something like:

```
+step1:
  jsr352-batchlet>:
    jar: tasks/myBatchlet.jar
    class: com.example.MyBatchlet

+step2:
  jsr352-chunk>:
    jar: tasks/myChunk.jar
    reader: com.example.MyItemReader
    processor: com.example.MyItemProcessor
    writer: com.example.MyItemWriter
```

The JSR352 spec contains many duplicated functionality against Digdag (e.g. job definition, step transition etc). so, supporting only BatchLet / Chunk processing would be sufficient and play well with DigDag.

What do you think about this?

FYI: a nice series of JSR352 introduction blog entries: http://www.radcortez.com/java-ee-7-batch-processing-and-world-of-warcraft-part-1/

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
