### ISSUE TITLE
Dividing up io.digdag.core package

### ISSUE THREAD

**Issue by frsyuki** [treasure-data/digdag#311]
This is one step to implement remote agent.
Remote agent can't access backend database directly. Instead, they access backend through REST API. To guarantee it, remote agent code shouldn't depend on backend interfaces (e.g. shouldn't use `ProjectStore` interface).
`io.digdag.core` package includes many packages that depend on each other. It is making hard to guarantee isolation of agent code. Idea here is to divide `io.digdag.core` package into backend-only stateful packages ("backend") and shared stateless packages ("core").

Project dependency:

```
core
     <- backend
     <- agent
                <- server
                          <- cli
```

(`server` depends on `agent` because server has local agent).

Plan:
- `io.digdag.backend`
  - `schedule`
  - `workflow`
  - `session`
  - `repository` rename to `project`
  - `database`
  - `Resource{NotFound,Conflict,LimitExceeded}Exception` (moved from `repository`)
- `io.digdag.core`
  - (most of packages of io.digdag.core: archive, config, crypto, notification, plugin, storage)
  - `ModelValidator` (moved from `repository`)
- `io.digdag.agent`
  - `log`
- `io.digdag.server`
  - `rs`
  - `local` (LocalAgentManager, InProcessTaskServerApi, InProcessTaskCallbackApi, etc.)
- `io.digdag.cli`
  - `client`

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
