### ISSUE TITLE
[feature-request] Launch Amazon EMR jobs (map reduce & spark)

### ISSUE THREAD

**Issue by rbparrish** [treasure-data/digdag#383]
It'd be able to create & launch Amazon EMR jobs from Digdag, for running ETL or ML jobs. Either in Spark or via Hadoop/MapReduce

The AWS services of interest:
- https://aws.amazon.com/emr/
- https://aws.amazon.com/emr/details/spark/

Some questions to discuss: 
(a) where do users store the program logic 
(b) how do users manage the dependencies required to run those programs 
(c) how we adequately define done 
(d) whether we can utilize an EMR job across multiple sequential steps, so we don't have to recreate for every task

Any ideas for a simple 1st implementation? Particularly interested in using this for Spark.

**Comment by xerial** [comment]
td-spark on EMR definitely needs this feature.

**Comment by frsyuki** [comment]
This is done. `emr` operator makes it possible: http://docs.digdag.io/operators/emr.html
