### ISSUE TITLE
gcp classes access levels 

### ISSUE THREAD

**Issue by gyamxxx** [treasure-data/digdag#389]
I'm sorry I am poor English.
I'm making [bq_wait opereator plugin](https://github.com/gyamxxx-org/digdag-bq-wait) referenced gcp_wait.
I want to use extend  theses classes in [gcp packages](https://github.com/treasure-data/digdag/tree/master/digdag-standards/src/main/java/io/digdag/standards/operator/gcp), but these classess are "package private class", so temporary I copy these classes to my project.
 - BaseBqOperator.java
 - BaseGcpClient.java
 - BaseGcpOperator.java
 - Gcp.java
 - GcpCredential.java	
 - GcpCredentialProvider.java	

Would you make it accessible(e.g. public) for making plugin upon classes?

**Comment by yoyama** [comment]
@gyamxxx It looks like the bq_wait operator plugin is not updated near to 3 years.
If you are still waiting for the request, please re-open.
