### ISSUE TITLE
Need document about secrets for local mode

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#424]
I can't find any document about the `secrets` prefix in `~/.config/digdag/config`.

For example,

```
secrets.pg.password = digdag1
```

related issues #356, #423.

**Comment by Vanuan** [comment]
Yeap, it's strange that there's [secrets section](https://docs.digdag.io/operators/pg.html) but no information on how to define those secrets.

**Comment by Vanuan** [comment]
After digging through github issues found the answer:
```
digdag secret --set pg.password --local
```

**Comment by hiroyuki-sato** [comment]
Hello, @Vanuan Thank you for your feedback.

What do you think to add this like like the below?

> When you set those parameters, use [digdag secrets command](https://docs.digdag.io/command_reference.html#secrets)

(I changed message after created image)
![スクリーンショット 2019-06-04 22 16 46](https://user-images.githubusercontent.com/767650/58882226-bc518480-8716-11e9-899c-1b62208fec8c.png)

**Comment by Vanuan** [comment]
That would be great!

I expected something like "Secrets" section in "Concepts", somewhere between parameters and operators.

**Comment by yoyama** [comment]
@hiroyuki-sato I guess we can close this issue. What do you think about it ?

**Comment by hiroyuki-sato** [comment]
@yoyama. I agree with you

> I expected something like "Secrets" section in "Concepts", somewhere between parameters and operators.

Le'ts discuss this document improvement on another issue.
