### ISSUE TITLE
virtualenv support for python scripts

### ISSUE THREAD

**Issue by vsreddy1602** [treasure-data/digdag#471]
HI,

I wanted to know how I can activate a virtualenv before a python script is executed as part of the workflow?

I tried looking at the documentation and could not find any information. Am I missing something?

Please can you help me here?

**Comment by frsyuki** [comment]
Currently, a recommended way is to use Docker as following:

```
_export:
  docker:
    image: my_python_image:tag

+task:
  py>: ...
```

http://docs.digdag.io/architecture.html?highlight=docker#running-tasks-on-docker

Related: #318

**Comment by vsreddy1602** [comment]
Thank you. This information helps.

For small projects, is it possible to have a configurable limit on the size of the archive uploaded? Currently it is 2Mb I suppose. 
This might help people who would not want to use Docker and prefer to add the packages in the project itself. Something similar to AWS Lambda.

**Comment by vsreddy1602** [comment]
Closing this issue since I have recieved the clarification.

**Comment by jo8937** [comment]
this is closed issue. but i want virtualenv for small project. not docker for my company's server policy. i want indicate python executable path.
