### ISSUE TITLE
How to use variable for "!include" file path?

### ISSUE THREAD

**Issue by kamikaseda** [treasure-data/digdag#486]
This dig file shows "no such file" error.

**dig file**

    timezone: UTC
    
    +tasks:
      for_each>:
        app: [log,log2]
      _do:
        _export:
          td:
            !include : ${app}/mini.dig

**Error message**

    error: /path/${app}/mini.dig (no such file)

How can I use variable in "!include" file path?

**Comment by frsyuki** [comment]
`!include` can't use parameters. Use `call>` operator instead.
