### ISSUE TITLE
Increasing default value of active task limit

### ISSUE THREAD

**Issue by frsyuki** [treasure-data/digdag#508]
Currently, an attempt of a workflow can't have more than 1000 active tasks. This is controlled by a system property (`io.digdag.limits.maxWorkflowTasks`) and users can't increase it per workflow even if they're certain that the workflow has more than 1000 active tasks intentionally.

Limitation of 1000 active tasks exists because database and server performance is limited. The reason why performance issue happens is described here: https://gist.github.com/frsyuki/896f0e3ef1a9a80d545fd846379bedca

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
