### ISSUE TITLE
Is there a way to force a task to run on a specified agent?

### ISSUE THREAD

**Issue by nqbao** [treasure-data/digdag#521]
I'm trying to use digdag for automating the workflow execution for deep learning use cases. However I'm facing a problem that some task needs to run on some specified node due to some constraints (such as GPU requirement). 

Is there a solution for that I can pin a specific task to a specific node?

**Comment by frsyuki** [comment]
https://github.com/treasure-data/digdag/tree/remote-agent is a branch that wants to add it but there're long way to make it done

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
