### ISSUE TITLE
Execute docker run using sudo

### ISSUE THREAD

**Issue by yteraoka** [treasure-data/digdag#523]
I want execute docker run using sudo.
Because RedHat recommended using sudo.

If docker installed from RHEL or CentOS repository then only root user and
root group are writable to docker.sock by default.

So, adding `prefix_commands` config like following.

How would you feel about adding `prefix_commands` config like below.

```
_export:
  docker:
    image: ubuntu:14.04
    prefix_commands: ["sudo"]
```

```
--- DockerCommandExecutor.java.orig     2017-03-23 16:00:43.009831468 +0900
+++ DockerCommandExecutor.java  2017-03-23 16:27:56.951204876 +0900
@@ -73,6 +73,12 @@
         }

         ImmutableList.Builder<String> command = ImmutableList.builder();
+
+        if (dockerConfig.has("prefix_commands")) {
+            List<String> prefixCommands = dockerConfig.getList("prefix_commands", String.class);
+            command.addAll(prefixCommands)
+        }
+
         command.add("docker").add("run");

         try {
```

As other method I thought, create other executable shell script file named `docker` contains just `exec sudo docker` in prior path.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
