### ISSUE TITLE
🍣 special characters are not allowed

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#524]
If you update SnakeYAML to v1.18, this issue may solve. 
https://github.com/treasure-data/digdag/blob/master/digdag-core/build.gradle#L19

See detail
https://github.com/embulk/embulk/pull/575
https://github.com/embulk/embulk/issues/574

I created a PR. but I can't build digdag on my environment. 
https://gist.github.com/hiroyuki-sato/f7e8715585b6ac09e080723ad76fcb68

That's why I create an issue. 

```
timezone: UTC

+eat_sushi:
  sh>: echo "Let's eat 🍣 "
```

```
2017-03-27 17:44:03 +0900: Digdag v0.9.7
error: Validating project failed
workflow /private/tmp/sushi/sushi.dig special characters are not allowed (model validation)
```

**Comment by yoyama** [comment]
@hiroyuki-sato Current SnakeYAML is 1.23. Can you confirm? And if fixed, please close this.

**Comment by hiroyuki-sato** [comment]
@yoyama. Thank you! LGTM

Confirmed: digdag 0.9.38

```
> 2019-07-12 14:12:04 +0900 [INFO] (0017@[0:default]+test+eat_sushi): sh>: echo "Let's eat 🍣 "
Let's eat 🍣
```
