### ISSUE TITLE
UI displays schedules in UTC

### ISSUE THREAD

**Issue by kakoni** [treasure-data/digdag#539]
My workflow's timezone is set to 
`timezone: Europe/Helsinki`

`digdag schedules` returns scheduled times correctly;
`next scheduled to run at: 2017-04-12 05:07:00 +0300 (in 16h 27m 2s)`

Where as digdag ui displays `Next Run Time` in UTC 
`2017-04-12T02:07:00Z`

Question, can UI use configurable/system timezones instead?

**Comment by frsyuki** [comment]
No, at this moment. But it is better to improve, definitely.

**Comment by szyn** [comment]
@kakoni @frsyuki 
Hi. I overlooked the issue.
It looks improved by https://github.com/treasure-data/digdag/pull/592, right?

**Comment by yoyama** [comment]
@kakoni I close this issue. But feel free to reopen or recreate the issue if you need.
