### ISSUE TITLE
!include requires whitespace before colon

### ISSUE THREAD

**Issue by mphuie** [treasure-data/digdag#548]
I'm trying to include a bunch of secret keys into my dig file.

When i do

        !include: 'secrets.dig'

It fails, but when I add the (seemingly) extra space, it works:

        !include : 'secrets.dig'

This seems to defy convention for all other examples.

**Comment by hiroyuki-sato** [comment]
Hello @mphuie 

You need extra white space like `!include :`.
http://docs.digdag.io/workflow_definition.html#include-another-file

The digdag is extending YAML syntax. And this is the current limitation. 

If you find `!include:` (no white space) in an example, it need to fix it.
Please let us know.

**Comment by frsyuki** [comment]
This is a limitation to be a valid YAML.

**Comment by muga** [comment]
@yoichi I will close this ticket since you already fixed a document about a whitespace character on https://github.com/treasure-data/digdag/pull/578 (thank you for improving!).
http://docs.digdag.io/workflow_definition.html#include-another-file
