### ISSUE TITLE
Getting a 500 when trying to set a secret

### ISSUE THREAD

**Issue by mphuie** [treasure-data/digdag#557]
`digdag secrets --project rundeck --set abcd=qwew
2017-05-10 09:54:13 -0700: Digdag v0.9.9
error: Failed to set project secret: Internal Server Error (web application)`

Serverside error:

2017-05-10 09:54:14 -0700 [ERROR] (XNIO-1 task-28): UT005023: Exception handling request to /api/projects/3/secrets/abcd
org.jboss.resteasy.spi.UnhandledException: java.lang.UnsupportedOperationException

I've verified project `rundeck` has an `id` of 3.  If this can is done via REST call, can the payload/method/etc be defined?

**Comment by mphuie** [comment]
Figured it out, `digdag.secret-encryption-key` needs to be set in the server config.

**Comment by yoyama** [comment]
It was resolved. So close.
