### ISSUE TITLE
[request] need a failed task name in the _error: directory

### ISSUE THREAD

**Issue by takkeybook** [treasure-data/digdag#569]
Suppose that there are several tasks in a workflow. When one of those tasks fails, I try to send a notification message in which the name of the failed task is written via mail or to a chat tool like as chatwork. From the digdag of v0.9.9, the built-in variable, "task_name", becomes available, but unfortunately the variable has a value +WORKFLOW_NAME^error when I refer it in the _error: directory.

I would like you to let me know how I can retrieve the failed task name in _error: directory.

**Comment by takkeybook** [comment]
Finally I've written a python script to retrieve a failed task name, thus I DID realize what I want. What I did is applicable to any case only when you do something using a python script in _error: directory.

**Comment by anilkulkarni87** [comment]
@takkeybook  Can you please share what you did to get the error task name?

**Comment by takkeybook** [comment]
@anilkulkarni87 
You can see the following code that I wrote
https://github.com/takkeybook/pydigdag/blob/6a9fbbaf4e5de140a8ef336c31b9eacf8c378023/pydigdag/control.py#L211-L225

In these years, I have no environment under which I use digdag, thus I cannot guarantee you that my code still works on the current version of digdag.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
