### ISSUE TITLE
passing arguments in digdag file

### ISSUE THREAD

**Issue by Fredehagelund92** [treasure-data/digdag#575]
i have a simple workflow python file where i want to pass a configuration file. i'm wondering is it really not possible to pass a argument like this?

```
    +GenerateSourceTables:
     py>: cheetax.generator.main --config 'config/connections.json'
```

keep getting

```
AttributeError: Module 'cheetax.generator' has no attribute 'json''
```

**Comment by takkeybook** [comment]
You cannot specify any argument in the python operator, but you can pass parameters using _export in a workflow file and receive them by arguments of methods or functions. In your case, a sample code is as follows,
**workflow.dig**
```
_export:
  config: config/connections.json

+GenerateSourceTables:
  py>: cheetax.generator.main
```
**cheetax/__init__.py**
```
import os

class generator(object):
    def main(self, config):
        print(config)
```
