### ISSUE TITLE
Content-Type is wrong about *.js

### ISSUE THREAD

**Issue by mats16** [treasure-data/digdag#580]
Content-Type of some javascript is `application/octet-stream`

Why is not `application/javascript` ?

<img width="357" alt="digdag" src="https://user-images.githubusercontent.com/5158858/27162949-30c563b6-51bf-11e7-8cc1-13ae5a55c193.png">

<img width="363" alt="digdag" src="https://user-images.githubusercontent.com/5158858/27163008-94eeec86-51bf-11e7-95eb-67a4317a05b7.png">

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
