### ISSUE TITLE
Digdag consuming free memory(Memory leak?)

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#588]
Due to Digdag consuming free memory, the user must restart digdag server. 
(The user restarts digdag server two days each)
Does someone have any idea to investigate this issue?

* OS: CentOS7
* Java: OpenJDK 1.8.0_131
* Digdag: 0.9.12
* Digdag
  * Number of projects: 17
  * Number of workflows: 100

OS free memory graph.
![](https://pbs.twimg.com/media/DEB7MUTU0AA_7eu.jpg:large)

Ref: [Twitter](https://twitter.com/kamekoopa/status/882807358174449665) Written in Japanese.

**Comment by komamitsu** [comment]
Why don't you connect to JMX and get some metrics in the Digdag JVM?

This configuration enables JMX.
```
server.jmx.port = 7199
```

Also, VisualVM or something may be able monitor those information w/o the above configuration, I think.

**Comment by hiroyuki-sato** [comment]
I close this issue. 
It seems that this issue is the plugin(digdag-slack) specific.
The plugin changed http client to okhttp from unirest.

Ref
https://github.com/szyn/digdag-slack/pull/5

Investigator tweeets. (written in Japanese)
https://twitter.com/kamekoopa/status/885407526891642880
https://twitter.com/kamekoopa/status/885408423336001536
https://twitter.com/kamekoopa/status/887146662669410304
