### ISSUE TITLE
[Q]: How can I execute a task as a different user on a specified host or farm?

### ISSUE THREAD

**Issue by rs2** [treasure-data/digdag#619]

**Comment by hiroyuki-sato** [comment]
Hello, @rs2 

Does this host running digdag?. If so how about using `sudo`?

Or do you want to execute a command via remote shell like (ssh)?

If so how about `ssh user@host command`?

I'm developing `ssh>` operator. 
It will be an operator for executing a command via ssh easily. (And next I want to develop ssh executor.)

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
