### ISSUE TITLE
Browsers do not ask entering password on login

### ISSUE THREAD

**Issue by YoshiHotta** [treasure-data/digdag#638]
I curled the latest binary as the official says and booted up a digdag server. 
In opening browser pages, it never asks me to type in password. 

```
$digdag server --bind 0.0.0 --port 65432 --config digdag.properties --log logs/server --task-log logs/tasks -o digdb
```
```
# digdag.properties
client.http.endpoint =http://xxxx:65432 # my server address
database.type=postgres
database.user=aaa
database.password=aaa
database.host=127.0.0.1
database.port=5432
database.database=digdb
```
I expected that you need to type in user: aaa, passoword: aaa but in fact browsers do not ask you to enter any password. 

Probably my setting up is wrong, but I could not find how to restrict access through the web UI. It will be helpful if you could write how to restrict access in documentation. ( and I am grateful if you can tell me how to do it)

**Comment by YoshiHotta** [comment]
Additional information. Pushing the logout button has no effect; you stay being logged in.

**Comment by hiroyuki-sato** [comment]
Hello, @YoshiHotta 

Those parameters aren't for web ui.
IIUC, that authentication doesn't implement yet.
It is better to use Reverse Proxy with nginx.

Reference (Japanese Text)

* [Qiita](http://qiita.com/hiroysato/items/fd58d8c98922e14dff97)
* [Twitter](https://twitter.com/hiroysato/status/878066976551084032)

**Comment by YoshiHotta** [comment]
@hiroyuki-sato Thank you very much. I will follow your advice.
