### ISSUE TITLE
digdag supports sub directory?

### ISSUE THREAD

**Issue by niwatolli3** [treasure-data/digdag#639]
Hi.

I love digdag as job worker.
Now, I have a question.

The digdag supports sub directory? (e.g. http://localhost/digdag)
I wanna use digdag with haproxy(using as reverse proxy).

**Comment by frsyuki** [comment]
No. An option you have is rewriting URL in the proxy server (e.g. `http://localhost/digdag/*` to `http://digdag-host/*`).
