### ISSUE TITLE
[Q] Parallel background

### ISSUE THREAD

**Issue by randyh0329** [treasure-data/digdag#641]
Following is my dig:

```
+prepare:
  +data1:
    echo>: data1

  # +data1 and +data2 run in parallel.
  +data2:
    _background: true
    echo>: data2

  # +data3 runs after +data1 and +data2.
  +data3:
    echo>: data3
```

and I get following error message, looks like the dig did running parall.
```
[ERROR] (0019@[0:default]+fail+prepare+data2): Parameter '_background' is not used at task +fail+prepare+data2.
```
I am confused it's a false alarm or my dig is wrong. Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @randyh0329 

IIUC, `echo>` operator doesn't support `_background`.

I tried `sh>` operator instead of `echo>`. It worked fine. 
And I got the same error if I change `sh>` operator to `echo>`.

https://github.com/hiroyuki-sato/digdag-support/tree/master/core_641_background_test

**Comment by frsyuki** [comment]
Currently _background works only with grouping-only tasks. you should be able to use this config instead meanwhile:
```
+prepare:
  +data1:
    echo>: data1

  # +data1 and +data2 run in parallel.
  +data2:
    _background: true
    +background_tasks:  # make the _background task grouping-only
      echo>: data2

  # +data3 runs after +data1 and +data2.
  +data3:
    echo>: data3
```

**Comment by frsyuki** [comment]
#642 fixes this issue.
