### ISSUE TITLE
Piping python script output to logs section of digdag ui

### ISSUE THREAD

**Issue by Noxeangel** [treasure-data/digdag#647]
Hello,

I'm trying to display the output of a python script in the log section of digdag ui.
Is it something easily achievable or only possible?
 
Thanks for all the insight you could have on that topic!!

**Comment by hiroyuki-sato** [comment]
Hello, @Noxeangel 

Have you ever tried `--task-log  DIR` option?

For example,

```
digdag server -m --task-log /tmp/task_log
```

![digdag](https://user-images.githubusercontent.com/767650/30679338-df091394-9ed3-11e7-93a2-1ae930130ae5.png)

Best regards.

**Comment by Noxeangel** [comment]
Hello @hiroyuki-sato ,

It's working perfectly fine!  ^^

Thanks!!
