### ISSUE TITLE
td command options are not recognized when using shell operator in server mode.

### ISSUE THREAD

**Issue by cocodrips** [treasure-data/digdag#660]
Example:

*.dig
```
+td_apikey_check:
  sh>: "td apikey"
```

Output: (server mode)
```
usage: td [options] COMMAND [args]

options:
.......

Type 'td help COMMAND' for more information on a specific command.
Error: no implicit conversion of nil into String
```

I tried following.
**Worked**
- local mode

**Does not worked**
- other options  (status, job)
- use abs path : td => /usr/bin/td
- move td commands to shell file and run it.

**Comment by cocodrips** [comment]
I found this error occurred only running digdag by systemd.

**Comment by cocodrips** [comment]
I found this is not a digdag bug.

`td` need following values but systemd don't have `HOME` .

```ruby
ENV['TREASURE_DATA_CONFIG_PATH'] || ENV['TD_CONFIG_PATH'] || File.join(ENV['HOME'], '.td', 'td.conf')
```
[Class: TreasureData::Config — Documentation for td (0.14.1)](http://www.rubydoc.info/gems/td/0.14.1/TreasureData/Config)

**Comment by toru-takahashi** [comment]
Thank you. I'll report this td command issue to our internal issue tracker
