### ISSUE TITLE
digdag-ui can't display task log if a task-log store in an S3.

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#670]
* Digdag 0.9.19

digdag-ui can't display task log if a task-log store in an S3.

digdag-ui try to fetch `%20hoge%20disp_current_date%4059df5e31090013c0.42407%40hsato-mbp13.local.log.gz`
(Decode string is ` hoge disp_current_date@59df5e31090013c0.42407@hsato-mbp13.local.log.gz`.)
This filename is wrong. It needs to replace ` `(space) to `+`.

![err1](https://user-images.githubusercontent.com/767650/31496223-7eab4f3a-af95-11e7-950b-7ba94f62cd23.png)

![err2](https://user-images.githubusercontent.com/767650/31496222-7e70c504-af95-11e7-8afd-ff923325d480.png)

 I'm not sure how to fix this yet, But the following ad-hoc patch fix this issue.

https://github.com/treasure-data/digdag/blob/2360e51f549c1bcfddece096081f49e1f0ef80a1/digdag-storage-s3/src/main/java/io/digdag/storage/s3/S3Storage.java#L198-L206

```diff
diff --git a/digdag-storage-s3/src/main/java/io/digdag/storage/s3/S3Storage.java b/digdag-storage-s3/src/main/java/io/digdag/storage/s3/S3Storage.java
index 16255a0c7..e0d0842e7 100644
--- a/digdag-storage-s3/src/main/java/io/digdag/storage/s3/S3Storage.java
+++ b/digdag-storage-s3/src/main/java/io/digdag/storage/s3/S3Storage.java
@@ -195,12 +195,19 @@ public class S3Storage
     }
 
     @Override
-    public Optional<DirectDownloadHandle> getDirectDownloadHandle(String key)
+    public Optional<DirectDownloadHandle> getDirectDownloadHandle(String key2)
     {
+        String key;
+        key = key2.replaceAll(" ","+");
         GeneratePresignedUrlRequest req = new GeneratePresignedUrlRequest(bucket, key);
         req.setExpiration(Date.from(Instant.now().plusSeconds(10*60)));
 
         String url = client.generatePresignedUrl(req).toString();
 
         return Optional.of(DirectDownloadHandle.of(url));
     }
```

```
log-server.type: s3
log-server.s3.endpoint: http://xxx.xxx.xxx.xxx:9000
log-server.s3.bucket: log
log-server.s3.credentials.access-key-id: XXXXXXXXXXXXXXXXXXXX
log-server.s3.credentials.secret-access-key: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

**Comment by frsyuki** [comment]
This problem doesn't reproduce for us. v0.9.18 and v0.9.19 have a know bug #668. But besides CORS issue, URL is formatted correctly. What is the full URL? In our environment, URL is like this:

```
https://digdag-server-staging-ec2.s3.amazonaws.com/log/2017-10-12/1.11td_op_test%4020171012T190000%2B0000/%2Btd_op_test%2Bquery%4059dfc64c378d3100.8%40ip-172-18-146-167.ec2.internal.log.gz?X-Amz-Security-Token=...
```

![eb4138ff9305ecefcd628002f10d8621](https://user-images.githubusercontent.com/40720/31517752-c31be7ea-af51-11e7-8798-733755e63e63.png)

**Comment by hiroyuki-sato** [comment]
@frsyuki Thank you very much for your confirmation.

The full URL is 
`http://127.0.0.1:9000/log/2017-10-12/0.1sample%4020171012T234605%200000/%20sample%20repeat%5Esub%20for-0%3Dorder%3D0%3Dfirst%261%3Danimal%3D0%3Ddog%4059dffec00717cbc0.1168%40hsato-mbp13.local.log.gz?X-Amz-Algorithm=...`

I don't use AWS S3. So I requested @Civitaspo this test. 

I tested this issue with minio S3 compatible system. 

## Reproduce steps

start minio server

```
mkdir -p /tmp/test/log
minio server /tmp/test
```

create config

```
log-server.type: s3
log-server.s3.endpoint: http://127.0.0.1:9000
log-server.s3.bucket: log
log-server.s3.credentials.access-key-id: XXXXXXXXXXXXXXXXXXXX
log-server.s3.credentials.secret-access-key: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

launch digdag server

```
digdag server -c test.conf
```

push workflow and start

```
digdag init -t sh sample
cd sample/
digdag push sample
digdag start sample sample --session now
```

access http://localhost:65432/attempts/1


### Environment

* minio: 2017-08-05T00:00:53Z
* Digdag: 0.9.19 and 0.9.16
* OS: macOS 10.13

**Comment by frsyuki** [comment]
Screenshot I could see:
<img width="1658" alt="2449a3b08cd6402990655a8cef24aadf" src="https://user-images.githubusercontent.com/40720/31526279-a5fbb3b0-af7a-11e7-993a-71ed71c5271d.png">

**Comment by hiroyuki-sato** [comment]
@frsyuki Thank you very much for your confirmation.

This problem was minio specific issue.

I heard some users can't show task log in digdag-ui.
I thought It caused by this issue. 
But they require [CORS](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) setting.

Ref: [Twitter](https://twitter.com/huntinggirled/status/918380671969533952) (Japanese)

**Comment by David-Development** [comment]
I'm using version 0.9.27 with Minio as a S3 Storage for logging and I can confirm this issue. Is there any way that this bug will be fixed? The workaround provided by @hiroyuki-sato works, but as far as I understand the url should contain the `+` sign instead of the whitespace anyway, right?

Or why does this incompatibility between a Minio S3 Storage and a AWS S3 Storage exist?

**Comment by hiroyuki-sato** [comment]
Hello, @David-Development .

It seems that the problem is minio only.
So If you want to use minio as S3 compatible storage server, you need to fix minio.

My plan is the following. (Not taken an action yet)

* Setup demonstrates environment. S3 and minio. (Unfortunately, I don't have AWS account yet)
* Ask minio developer why this behavior difference between S3 and minio.
* Ask minio developer how to debug minio server.
* Investigate and fix minio issue and create PR. 

What do you think?

**Comment by David-Development** [comment]
@hiroyuki-sato thank you for the quick response!

The plan sounds good, however I still have a couple of question. The name of the tasks is shown with a leading `+` sign. e.g. `+myworkflow+mytask...`. The logs are stored on the s3 storage in the same format. Why is the UI requesting the logs with whitespaces instead of the `+` sign? Isn't that true for the AWS Storage as well? (I don't have an AWS account either - so I can't verify this right now).

Or is it some kind of feature of AWS, that it converts whitespaces into `+` signs and that's why it working there and not on minio? I guess there is some magic going on in the s3 aws storage backend as described [here](https://forums.aws.amazon.com/thread.jspa?threadID=48852) and [here](https://forums.aws.amazon.com/thread.jspa?threadID=55746).
