### ISSUE TITLE
Operators built using Python

### ISSUE THREAD

**Issue by Xorso** [treasure-data/digdag#674]
Is there any way to build an operator or plugin using python instead of java?

**Comment by hiroyuki-sato** [comment]
Hello, @Xorso 

There is no operator API for Python yet. 

How about `py>` operator?, It's a scriptable
https://docs.digdag.io/python_api.html#language-api-python

**Comment by Xorso** [comment]
Yes it is working great and we are able to really implement our own operator. It would have just been nice to have the short hand for it. Thank you for the good work on DigDag. It is proving to be successful in our organization where others failed.
