### ISSUE TITLE
any screenshot for this ui?

### ISSUE THREAD

**Issue by xycloud** [treasure-data/digdag#681]
would you mind to provide any screenshot for this ui?

**Comment by frsyuki** [comment]
![e5d7dc4b61c33044f72094b3d2de9b4e](https://user-images.githubusercontent.com/40720/32684424-2e23319a-c638-11e7-9b5d-09aaa5b2b095.png)

(Note: top-left logo is a customized from the default logo)

**Comment by muga** [comment]
Keep opening to add "Admin UI" document in our homepage.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
