### ISSUE TITLE
Can i cleanup old logs?

### ISSUE THREAD

**Issue by alu** [treasure-data/digdag#692]
I want to cleanup old logs from S3.
There is option for do it? Or can I do it manually?

**Comment by hiroyuki-sato** [comment]
Hello, @alu 

I'm not sure how to do it with digdag itself. 
(IIUC, It's not implemented yet. )
An alternative idea, Have you ever tried S3 Object lifecycle management?

http://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html

Ref: [Twitter](https://twitter.com/hiroysato/status/935461543826694144) in Japanese.

**Comment by komamitsu** [comment]
Right. Old logs need to be deleted manually for now. As @hiroyuki-sato suggested, using lifecycle management would make it easy.

**Comment by alu** [comment]
@hiroyuki-sato @komamitsu 
Thank you for response.

Our storage is S3 LIKE private storage so we can't use lifecycle management because not implemented yet on the storage.
So i think delete logs from `/log/YYYY-MM-DD` after a certain period of time.

It's not problem?

Thanks.

**Comment by hiroyuki-sato** [comment]
Hello, @alu 

Another user removed old logs.
It seems work well.

The user used `log-server.type = local` and added cleanup task like the below.
`find /dir -mtime +180 -exec rm {} \; `

Ref: [Twitter](https://twitter.com/hiroysato/status/936531473011695618) (Japanese text)

**Comment by alu** [comment]
@hiroyuki-sato 

Thanks :)
