### ISSUE TITLE
ImmutableRevision.java not found? 

### ISSUE THREAD

**Issue by jo8937** [treasure-data/digdag#693]
where is io.digdag.core.repository.ImmutableRevision ?
I cannot build this project.

**Comment by hiroyuki-sato** [comment]
Hello, @jo8937 

It generates in `./digdag-core/build/generated/source/apt/main/io/digdag/core/repository/ImmutableRevision.java` during the build. 

I succeed to build latest version (5cf357243c45b8f40bb1a34bf8873b0f818bbf8f)
How did you build digdag?

```
git clone https://github.com/treasure-data/digdag
cd digdag
./gradlew cli
```

* OS: macOS 10.13.1
* Java: 1.8.0_121

**Comment by komamitsu** [comment]
Digdag uses Immutables. I hope https://immutables.github.io/apt.html would help you.

**Comment by jo8937** [comment]
@hiroyuki-sato @komamitsu Oh, thank you! now I can build source successful with gradle. I didn't know about it is generated file. My os is windows 7 and I just do auto build with eclipse IDE build.
