### ISSUE TITLE
Feature Request: S3 Wait Timeout

### ISSUE THREAD

**Issue by edreyer** [treasure-data/digdag#696]
Hi,

Is it possible to add an optional timeout to the s3_wait operator such the task fails after the timeout expires?

Thanks.

**Comment by hiroyuki-sato** [comment]
Hello, @edreyer 

Thank you for your comment.

IIUC, those options(connection and read timeout) not implemented yet. 
I heard another user want to use same options.
I think It will implement for a future release.

I'll check the code.

**Comment by yoyama** [comment]
This feature had been included in next major version (0.10.0) in #1280
