### ISSUE TITLE
project structure and workflow suffix changes

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#70]
- no `digdag.yml` project file 
- workflow file suffixes change from `.yml` to `.dig`
- all `.dig` files in project directory are picked up automatically by digdag
- digdag cli gains a `--project` option to specify the project directory
- `digdag run` `-f` option is removed
- `digdag init` creates: 
  - `.digdag` directory in project directory
  - `.digdag/config` file
- digdag cli looks for `.digdag` directory, starting in current directory and then recurses into parent directories (like git).
- `digdag push` pushes entire project (as identified by `.digdag`) in some parent dir, even if executed in a subdir.
- filenames referenced by a `.dig` file are resolved relative to the path of the `.dig` file so that given a project with:

```
.digdag/config
subdir/workflow.dig
queries/foo.sql
```

Then a user can both be in the project dir and do:

```
digdag run subdir/workflow
```

Or

```
cd subdir/
digdag run workflow
```

with the same result. The `subdir/workflow.dig` file must reference the query file as `../queries/foo.sql`.
- digdag does not change "CWD" when executing a workflow.
- `digdag run` `<workflow name>` parameter can include `.dig` suffix so that the below invocation semantics are identical:
  - `digdag run foo`
  - `digdag run foo.dig`

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
