### ISSUE TITLE
[Q] How can I set retry wait interval of _retry parameter?

### ISSUE THREAD

**Issue by jo8937** [treasure-data/digdag#709]
I want to retry after 1 hours.
How can I set this?
If this feature is not included, would it be possible to add in next release?

**Comment by hiroyuki-sato** [comment]
Hello, @jo8937 

Do you want to specify retry interval in Operator or TaskGroup?, I think It's impossible yet. 
The current implementation, a task will retry immediately until `_retry` count reach. 

Please write your use case or create PR. 

* [Twitter](https://twitter.com/seri_k/status/949252318268030976)  Japanese text.

**Comment by jo8937** [comment]
That's what I want!
but I see, it is not impossible yet. I'll try to see source code for PR.

The twitter thread very useful to know internal structure of digdag retry. Thank you!

**Comment by hiroyuki-sato** [comment]
Hello, @jo8937  `exponential` backoff introduced in v0.9.30
Could you try it?  If it works well, please close this case.
http://docs.digdag.io/workflow_definition.html#retrying-failed-tasks-automatically

**Comment by jo8937** [comment]
@hiroyuki-sato LGTM! Thank you. It is better than what I want. I've tried it and it works fine. I'll close this issue.
