### ISSUE TITLE
[Q] How can I define max-task-threads in a task with "_parallel: true" parameter?

### ISSUE THREAD

**Issue by jo8937** [treasure-data/digdag#710]
I'm running bigquery task by "for_each" and "_parallel" 
but there is so many task, and I want adjust _parallel task concurrent thread number limit to 8
( bigquery's max concurrent query is 50. and I have to use under 10 concurrent bigquery in our company )

**Comment by hiroyuki-sato** [comment]
Hello @jo8937 

Does this mean you want to limit the number of thread in `_parallel` like the below?
As far as I know, It's not implemented yet.

```yaml
_parallel: true
concurrenly: 8
```

You can limit it using `--max-task-threads N` parameter.
ex) `digdag server --max-task-threads N`  `digdag run --max-task-threads N`.

**Comment by hiroyuki-sato** [comment]
https://github.com/treasure-data/digdag/blob/8a6b676a51b0fd246ce153509f70d4b4e32c0653/digdag-standards/src/main/java/io/digdag/standards/operator/LoopOperatorFactory.java#L57-L59

https://github.com/treasure-data/digdag/blob/master/digdag-core/src/main/java/io/digdag/core/Limits.java#L5-L6

Have you ever tried `io.digdag.limits.maxWorkflowTasks` system property? 
ex) `digdag -X io.digdag.limits.maxWorkflowTasks=2 run -a fuga`?

**Comment by jo8937** [comment]
Oh, yes! I want exactly like this.

```yml
_parallel: true
concurrenly: 8
```

I didn't try to use io.digdag.limits.maxWorkflowTasks parameter.
but I think this parameter applies to whole workflow. not only apply to subtask .
(I've using digdag in server mode with 6 servers)

I hope 'concurrently' parameter implemented soon.

**Comment by yoyama** [comment]
I close this issue but feel free to reopen if you need.
