### ISSUE TITLE
require operator does not honor past session's success/failure when retrying

### ISSUE THREAD

**Issue by amogh09** [treasure-data/digdag#712]
I am using [require operator](http://docs.digdag.io/operators/require.html) to check the status of the previous session of the same workflow. The workflow should -
1. continue if the last session was successful,
2. fail if the last session failed,
3. start last session if the last session does not exist, and,
4. wait for the last session's completion if it's pending.

The above four conditions work perfectly when the session is started by the scheduler or is started using `digdag start` command without the `--retry` option. 

But when I retry a session (either successful or failed) using `digdag retry` or `digdag start --retry` or `digdag backfill`, the require operator starts the last session (condition 3 above) regardless of the status of the last session. In other words, last session is started again even if its status is successful or failed.

**Comment by amogh09** [comment]
I can see that the last session is being fetched using `retryAttemptName`. I also tested by giving same names to two different retry attempts and in that case the operator works as expected.

**Comment by amogh09** [comment]
I can also see that `digdag retry` gives the retry attempt a random name and that's why the older attempts are not found by the require operator.

**Comment by amogh09** [comment]
Okay, understood. Last sessions are fetched using `retryAttemptName` of the current session. The two names must match for the require operator to work as expected.

1. Run a sentinel workflow using `digdag start --retry retry_name`
2. Retry dependent workflows using `digdag start --retry retry_name`

**Comment by hiroyuki-sato** [comment]
Hello, @amogh09 

JFYI, I don't understand your use case entirely yet. But I think your use case seems similar #615.

**Comment by amogh09** [comment]
Scheduler runs a new session with `retryAttemptName = NULL` and then this new session won't see the past sessions which have a retry attempt name attached. 😢

**Comment by amogh09** [comment]
@hiroyuki-sato Thank you for your reply. 

To summarize my understanding, the issue is that the `require` operator and `retry` feature cannot be used together. `require` fetches a past session attempt by `retryAttemptName x session_time` and `retry` attaches a new `retryAttemptName` to the attempt making past sessions not visible.

I might be mistaken in understanding the aforementioned operator and command of course. :-)

**Comment by tony810430** [comment]
Hi all,

I have encountered this issue recently. Just as @amogh09 said, `require` operator will check session attempt by both `retryAttemptName` and `sessionTime`. That will cause the problem that when I used `retry` command those related workflows will be executed indeed.

What I expected was `retry` would only check the latest attempts of `require` operators and always retry for `call` operators.

This commit ([571cd452c](https://github.com/tony810430/digdag/commit/571cd452cb54f06f847bca97571c089b8224ff6e)) is a  workaround to me. I'm not sure if it is a good solution.

If it looks good to you, I can create a PR for it. What do you think.

Also, cc @frsyuki. Would really appreciate it if you can give me some feedback. Thank you.

**Comment by to-lz1** [comment]
Hello.

We've also encountered this problem and found this issue remains open.

@tony810430's comment and commit seems reasonable to me. Is there any update on this issue?

**Comment by hiroyuki-sato** [comment]
Hello, @to-lz1 

What digdag version do you use?

IIUC, some problem fixed between 0.9.25 ~ 0.9.37.(#738,#852,#928,#917,#1073 and #1104)
But other problems still need to fix (proposed change doesn't fix completely as I remember). 

@yoyama Do you have any comment?

**Comment by yoyama** [comment]
We are developing to enhance require> operator for internal requirements.
As described in above comments, retry CLI command generates unique retryAttemptName and it is derived to required WF. As result, the required WF is alway executed.
We will change this behavior as stop retryAttemptName derivation.
In addition, add option to require> operator to force to run the required WF regardless of attempt exists or not.

**Comment by to-lz1** [comment]
@hiroyuki-sato @yoyama 

Sorry for replying late. I'm glad to hear that you are just developing to enhance this operator!

We're using version 0.9.41(therefore, currently version up doesn't help us).
Looking forward to new release. Thank you.
