### ISSUE TITLE
Support Sentry notification

### ISSUE THREAD

**Issue by komamitsu** [treasure-data/digdag#714]
It would be great if Digdag can send an error notification via Sentry.

**Comment by y-ken** [comment]
@komamitsu What topic do you think as the benefits compared with slack notification with HTTP?
I think there are good point to have such feature in Sentry. Anything else?
* summarizable
* categorizable with tag
* customize notification

but it may contain secrets in error. that is off-topic though.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
