### ISSUE TITLE
Add namespace to tasks

### ISSUE THREAD

**Issue by cafeal** [treasure-data/digdag#727]
In the current implementation, when tasks are queued into DB, all digdag agents connected to the DB will try to execute tasks.
But sometimes we wanna specify a part of agents(worker machines) to execute some tasks because of constraints of host machines or something.
e.g.  hard computation, using GPU, separated network, etc.

If there is a namespace for each task, we can assign some processable task namespaces to each machine.

How about it?

**Comment by rikimakita** [comment]
Is there anything update? 😗

**Comment by hiroyuki-sato** [comment]
Hello @69guitar1015 and @grezar 

Does this issue the same #521?

**Comment by hiroyuki-sato** [comment]
Hello, @69guitar1015 
Thank you for the quick reply.

I've found #521 today :smile:
IMO, It is better to remain as open.
The "namespace" better keyword to find a similar issue.

Could you extend #475 to implement this feature?

**Comment by 69guitar1015** [comment]
Actually, I was tried but I couldn't. sorry :-\
I have few experience to implement in Java...

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
