### ISSUE TITLE
jar without bash

### ISSUE THREAD

**Issue by shomodj** [treasure-data/digdag#730]
Hey,

is there a pure jar to download from somewhere without selfrun.sh, it really messes up fish and python venv if you are not using bash

Thanks,
Boris

**Comment by hiroyuki-sato** [comment]
Hello, @shomodj 

Please try, https://github.com/treasure-data/digdag/issues/426#issuecomment-267206850

Homebrew (macOS package system) use the following wrapper script.
It worked well on the `fish` shell.

```bash
#!/bin/bash
exec /bin/bash "/path/to/digdag.jar" "$@"
```

https://github.com/Homebrew/homebrew-core/blob/master/Formula/digdag.rb

**Comment by shomodj** [comment]
Yay, that work, thanks :)
