### ISSUE TITLE
[Q] How can I migrate from H2 database to PostgreSQL

### ISSUE THREAD

**Issue by otashun** [treasure-data/digdag#732]
I use H2 database now. I want to migrate from H2 to PostgreSQL. How can I do?

**Comment by hiroyuki-sato** [comment]
Hello @otashun 

IIUC, H2 to PostgreSQL migration feature doesn't implement yet. 

What do you think to download all of latest projects with the following command?
(It expect that all of the projects named with alphanumeric characters.) 

```
for i in `digdag workflow 2> /dev/null | awk '/^  [a-zA-Z][A-Za-z0-9]*$/{ print $1 }' ` ; do digdag download $i ; done
```



After that, you can push those project with `digdag push`.

**Comment by otashun** [comment]
@hiroyuki-sato Thank you!
