### ISSUE TITLE
[feature request] digdag attempts returns unconfigurable size of attempts

### ISSUE THREAD

**Issue by JunpeiAnzai** [treasure-data/digdag#741]
Hi.
I'm using `digdag server`, and monitoring how many number of attempts running by `digdag attempts | grep running | wc -l`.
Recently, I changed `io.digdag.limits.maxAttempts` from 100(default) to 150.
But I noticed `digdag attempts` returns only 100 attempts and unconfigurable.
https://github.com/treasure-data/digdag/blob/d90168019dabe700c77635a888ac2d36f71b4885/digdag-server/src/main/java/io/digdag/server/rs/AttemptResource.java#L103

So, it would be nice if `digdag attempts` returns configurable number of attempts via commandline argument
```
digdag attempts -l 150
```
or same size of system property `io.digdag.limits.maxAttempts`

**Comment by muga** [comment]
related to https://github.com/treasure-data/digdag/issues/857
