### ISSUE TITLE
[Q] How to set up task_ttl in workflow?

### ISSUE THREAD

**Issue by tony810430** [treasure-data/digdag#746]
Hi all,

I know there is a configuration `executor.task_ttl` when deploy digdag server.
However, I was wondering if there is any way to set up `task_ttl` in particular workflow independently.
So that I can make any operator failed when it took more than its expected execution time.

For example:
```
timezone: UTC

+step1:
  sh>: tasks/task1.sh
  _task_ttl: 5.sec

+step2:
  sh>: tasks/task2.sh
  _task_ttl: 1.min
```
Many Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @tony810430 

Have you ever tried `sla` option? I suppose it is a similar feature.
But I think It does not allow each task.


```yaml
timezone: UTC

sla:
  duration: 00:00:05
  fail: true
  alert: false
  +notice:
    echo>: sla alert!!


+test:
  sh>: ./hoge.sh
```


```bash
#!/bin/sh

sleep 6

echo "test"
```

```
2018-04-02 19:30:20 +0900: Digdag v0.9.24
2018-04-02 19:30:22 +0900 [WARN] (main): Using a new session time 2018-04-02T00:00:00+00:00.
2018-04-02 19:30:22 +0900 [INFO] (main): Using session /path/to/digdag-support/core_746_ttl/.digdag/status/20180402T000000+0000.
2018-04-02 19:30:22 +0900 [INFO] (main): Starting a new session project id=1 workflow name=mydig session_time=2018-04-02T00:00:00+00:00
2018-04-02 19:30:23 +0900 [INFO] (0017@[0:default]+mydig+test): sh>: ./hoge.sh
2018-04-02 19:30:29 +0900 [INFO] (0022@[0:default]+mydig^sla+notice): echo>: sla alert!!
sla alert!!
2018-04-02 19:30:29 +0900 [INFO] (0021@[0:default]+mydig^sla^fail): type: fail
2018-04-02 19:30:29 +0900 [ERROR] (0021@[0:default]+mydig^sla^fail): Task +mydig^sla^fail failed.
SLA violation
test
2018-04-02 19:30:29 +0900 [INFO] (0017@[0:default]+mydig^failure-alert): type: notify
error:
  * +mydig^sla^fail:
    SLA violation

Task state is saved at /Users/hsato/OpenProjects/digdag/digdag-support/core_746_ttl/.digdag/status/20180402T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

Rerference. https://github.com/hiroyuki-sato/digdag-support/tree/master/core_746_ttl

**Comment by tony810430** [comment]
Hi @hiroyuki-sato 
Yes, I have already known `sla` option, but I didn't know the config `fail:` and `alert:` since I didn't find them in document.
It is helpful to me currently if `sla` option could make the workflow failed, but it is still better to allow each task to have this feature.
Could you please provide more explanations for these two configurations? Thanks.

**Comment by tony810430** [comment]
I have seen the document in [0.8.1release note](https://github.com/treasure-data/digdag/blob/5d235dc9d281d2d50f6a2193ad2a312ec51d18ca/digdag-docs/src/releases/release-0.8.1.rst). Thank you.

**Comment by hiroyuki-sato** [comment]
Hello, @tony810430 

I wanted to tell you same page. I think that description needs on document pages.

**Comment by tony810430** [comment]
Hi @hiroyuki-sato 

I have tried `sla` option and I found that `sla` would make attempt failed but executor still processed the whole workflow.
Is that an expected behavior? In my option, I would like to make the attempt failed and stop it as well when it met the `sla` criteria.

**Comment by hiroyuki-sato** [comment]
Hello, @tony810430 

I think The `sla` operator purpose is just to notify an alert to the administrator. In other words, It's not the operator for stop the task.

For example, `bq` query run until those query finish even you kill that session with `digdag kill`. some tasks are difficult to stop immediately. 

This is the topic of the current implementation. 

Please feel free your requirements for future development.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
