### ISSUE TITLE
Can't set socket_timeout option of redshfit operator

### ISSUE THREAD

**Issue by e-mon** [treasure-data/digdag#747]
in digdag (documents) [https://docs.digdag.io/operators/redshift.html],

>The timeout value used for socket read operations. If reading from the server takes longer than this value, the connection is closed. Default: 1800.

but, following configuration does not work.

```
redshift:
  socket_timeout: 1800
```

Error:

```
2018-04-03 19:20:13 +0900 [ERROR] (0019@[0:default]+task): Configuration error at task +task: Expected class io.digdag.util.DurationParam for key 'socket_timeout' but got 1800 (number) (config)
> Can not instantiate value of type [simple type, class io.digdag.util.DurationParam] from Integral number (1800); no single-int-arg constructor/factory method
 at [Source: N/A; line: -1, column: -1] (json mapping)
```

**Comment by hiroyuki-sato** [comment]
Hello, @e-mon 

It seems document typo. Can you try `secket_timeout: 1800s`?
The `s` is seconds.
