### ISSUE TITLE
[Q] How can I change parameters for each environment?

### ISSUE THREAD

**Issue by rikimakita** [treasure-data/digdag#749]
I wanna change parameters that pass to workflows for each environment in server mode.

I tried below but `!include` doesn't expand variable so it does'nt work.

start digdag server with `-p environment=staging`
```
_export:
  !include : config/${environment}.yml
```

Is there a way to change parameter for each environment?

**Comment by rikimakita** [comment]
Hi, @hiroyuki-sato 
Thanks for your reply.
In that way, using same params file in all digdag project?
I suppose that each project use different parameter and if all parameters write into same file(like dev.yml), it seems to be hard to manage.
I hate that params file will become bigger in proportion to the increase of the project.
How do you think about such a problem?

**Comment by hiroyuki-sato** [comment]
Hello, @rikimakita 

I introduced a solution in the current.
Some tools e.g. [YamlMaster](https://github.com/joker1007/yaml_master) generate configuration from single master file.

I think your idea is very useful. However, It seems that somebody needs to implement that feature.

**Comment by rikimakita** [comment]
@hiroyuki-sato 
Thanks for very useful information!
I'l l try your solution.
