### ISSUE TITLE
Crash by "RESTEASY003770: Response is committed" when using h2 database

### ISSUE THREAD

**Issue by takanamito** [treasure-data/digdag#756]
digdag crashed and cannot restart process only executing `# systemctl restart digdag`

/var/log/digdag/digdag-error.log
```
General error: "java.lang.NullPointerException" [50000-192]
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at io.digdag.core.database.DataSourceProvider.createSimpleDataSource(DataSourceProvider.java:70
...
Caused by: org.h2.jdbc.JdbcSQLException: 一般エラー: "java.lang.NullPointerException"
```

It fixes with command below.

```
$ sudo systemctl stop digdag
$ sudo mv /var/digdag/database /tmp
$ sudo systemctl restart digdag
```

I guess this crash caused by resteasy-client bug.

https://issues.jboss.org/browse/RESTEASY-1238

and the bug fixed by this PR which released in [3.0.23.Final](https://issues.jboss.org/browse/RESTEASY-1238?jql=project%20%3D%20RESTEASY%20AND%20fixVersion%20%3D%203.0.23.Final)

https://github.com/resteasy/Resteasy/pull/1169

My envirtonment
- OS: ubuntu 16.04.2 LTS
- digdag version: 0.9.12
  - database.type=h2
- java: 

```
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

- - -

So I bumped up resteasy-client in this PR. https://github.com/treasure-data/digdag/pull/754

But CI failed with executing webpack which mentioned to my another issue. https://github.com/treasure-data/digdag/issues/753

**Comment by muga** [comment]
@takanamito thank you for reporting and suggesting. To take a look this issue, can you tell us 1) Your full stacktrace if you can. 2) How to reproduce this issue I'm still not sure why this error happened.

**Comment by muga** [comment]
@takanamito thank you for sharing. let me take a look.

**Comment by muga** [comment]
@takanamito roughly checked your stacktrace and https://issues.jboss.org/browse/RESTEASY-1238. I agree with you and https://github.com/resteasy/Resteasy/pull/1169 could mitigate this issue. Please re-create or re-open ticket to upgrade resteasy library?

**Comment by muga** [comment]
@takanamito if my understanding is correct, this issue was already fixed. i close this ticket but, please let me know if you have anything.
