### ISSUE TITLE
[feature request] until option for backfill

### ISSUE THREAD

**Issue by chengvt** [treasure-data/digdag#764]
As backfill automatically fill the data until current date, I think it will be convenient to also have until option but I am not sure if this feature will go against the intention of backfill. This will also help to solve the problem of hitting 100 limit on backfill batches when trying to backfill data older than 3 months.

**Comment by hiroyuki-sato** [comment]
Hello, @chengvt 

The `skip_delayed_by`(a.k.a. disable_backfill #536) option will introduce in the future release. 
It already merged into master branch(#752).
Does this option solve your issue?

**Comment by chengvt** [comment]
Thank you for the fast response.

I checked out the previous issue and seems like this was needed for the case when digdag server restarts and it tries to backfill automatically the period it failed to.

In this case, backfill is used with an intention to fill the past data (which I believe but a little unsure if this is the purpose backfill was intended to be). I am alternatively trying running `digdag start --session 'dt'` in loop to fill the past data (that go far more in the past than 100 days).

**Comment by hiroyuki-sato** [comment]
Hello, @chengvt 

Does this mean you want to create previous sessions over 100 times with `backfill` command?
What do you think `--count` option?
Or do you want to use `--until YYYY-MM-DD` instead of `--count`?

```yaml
timezone: UTC

schedule:
  daily>: 00:00:00

+setup:
  sh>: echo start ${session_time}
```

```
digdag server -m
```

You can create previous sessions over 100 days using `backfill` twice.

Today is 19/Apr/2018.

```
digdag push hoge
digdag backfill --count 100 --from '2018-01-01' hoge hoge # 11/Apr/2018 is 100 days from 1/Jan/2018.
digdag backfill --from '2018-04-11' hoge hoge
```

**Comment by chengvt** [comment]
@hiroyuki-sato 
That works wonderfully! I thought `--count` was to be used by itself. 

Thank you for your time and clarification on the matter.
