### ISSUE TITLE
Runtime error(Illegal AccessError) in using AbstractJdbcXxx classes in plugin

### ISSUE THREAD

**Issue by onunu** [treasure-data/digdag#767]
Hi team.
I'm trying to create `mysql` operator as a plugin like `pg` operator.
I created  `MysqlOperator` class that inherits `AbstractJdbcJobOperator` class with using `PgOperator` class as a reference.

Although compiling succeed, the `IllegalAccessError` is occured with executing.
I suppose the reason of error is a class loaders for plugins that are probably in these codes ( https://github.com/treasure-data/digdag/tree/master/digdag-core/src/main/java/io/digdag/core/plugin)
The error logs for detail of them is in a issue page of my plugin repo.
Please read following link.
https://github.com/onunu/digdag-plugin-mysql/issues/1

If this issue is resolved, we can create some plugins using JDBC.
I hope some communications to resolve this issue, do that I can as far as possible.

Thanks.

**Comment by hiroyuki-sato** [comment]
Hello, @onunu 

JFYI
My `mysql>` operator worked digdag until 0.9.17.
After update 0.9.18, I encountered the same error.
https://github.com/hiroyuki-sato/digdag-plugin-mysql

**Comment by onunu** [comment]
Tank you @hiroyuki-sato . (include [communications on twitter](https://twitter.com/hiroysato/status/988734021231304704))
I understanded the problems and could resolve them.

I close this issue. Thank you for teaching!
