### ISSUE TITLE
Supporting no_proxy

### ISSUE THREAD

**Issue by grezar** [treasure-data/digdag#810]
Hi there.
Although digdag currently supports http_proxy and https_proxy, no_proxy hasn't supported yet.
In my case, digdag is runnning on aws and using s3 as a log storage.
So far I have been set http proxy for each http client so digdag doesn't use proxy and communicated to s3 through vpc endpoint .
But this time, I try to use a [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) which only supports proxy setting by environment varialbes.
To use it, I have to set http_proxy environment variables.
As you know, digdag, especially communication to s3 will get to work with http proxy and can't use vpc endpoint.
To avoid this, digdag will support no_proxy or amazon-ecr-credential-helper has to support another way to set http proxy.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
