### ISSUE TITLE
How about add a link to docs.digdag.io to README

### ISSUE THREAD

**Issue by ichihara-3** [treasure-data/digdag#811]
I tried to search the way installing digdag on Windows10 around https://github.com/treasure-data/digdag and could not find the way for a while.
I think that the link to www.digdag.io in https://github.com/treasure-data/digdag#Documentation is ambiguous if you are beginner and you want to install digdag first time.
To link docs.digdag.io directly will make the instruction more clear.

**Comment by hiroyuki-sato** [comment]
Hello, @ichihara-3 

Thank you for your feedback.

The Documentation text is the link for that document.
Is it hard to find?



![digdag](https://user-images.githubusercontent.com/767650/41825866-b3310086-785f-11e8-9a20-3c44cce782d0.png)

**Comment by ichihara-3** [comment]
Hi, @hiroyuki-sato 

Thank you for your instruction!
Only to find the link is not so hard, I think.
But the title "Documentation" refers different urls than that's contents and it may cause a problem.  
I misunderstood the link in "Please check digdag.io for installation & user manual." refers the same url with its title.
And link to www.link.io in the sentence is somehow unhelpful when you just look for installation or user manual because there are too much information than you need.
