### ISSUE TITLE
Multiple passwords for connecting two PostgreSQL database in a project.

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#836]
Some users want to connect multiple PostgreSQL database in the same project.
It uses a different password in each database.

Due to the Digdag use single password in a single project,
It's can't create a task for connecting multiple databases. 

@muga 
What do you think to add an option for specifying connection password like the below?

```yaml
pg>: test.sql
password: pg.devevelopment.password
```

[Current implementation](https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/java/io/digdag/standards/operator/pg/PgConnectionConfig.java#L21-L27)

Proposed modification.

```java
secrets.getSecretOptional("password").or(() -> {
 String passSecName =  params.get("dev_password", String.class);
  secrets.get(passSecName);
})
```

## References.

* [Twitter](https://twitter.com/takashima0411/status/1025268527073177600) (Japanese)

**Comment by muga** [comment]
Thank you for suggesting. and got your point. I don't have good idea so much to solve this for now. Let me think about it. @frsyuki do you have any ideas?

**Comment by komamitsu** [comment]
I'm taking care of this feature at https://github.com/treasure-data/digdag/pull/839

**Comment by muga** [comment]
#839 is good idea. thank you! @komamitsu
