### ISSUE TITLE
Project-level Parameters

### ISSUE THREAD

**Issue by friendofasquid** [treasure-data/digdag#847]
Hi, I wondering about the role of parameters and Digdag, using the CLI.

On the one hand, we can set parameters when the server starts as *server level parameters* shared across projects and workflows using `digdag server --param …`. On the other hand, it seems we can set *workflow level parameters* with `digdag start … --param  …`. 

What I'm thinking is that I was to be able to set properties for projects and workflows per project, and for the life of the project (not for a single session as, if I understand correctly, with `digdag start`. 

Wondering if support `--param` makes sense with `digdag push …` to set project level params, either one at a time or with a config file just like with the `server` command. That would allow me to change params when changing the project files, or possibly to _only_ change params using `digdag push`. 

Hope this makes sense. I guess my ask then is:

- what is the best way to alter parameters per project?
- is it possible to allow for `push` to set project level params?

Thanks!

**Comment by hiroyuki-sato** [comment]
Hello, @friendofasquid 

What do you think the following idea?

* `work1.dig` and `work2.dig` is in the same project.
* `common/param.dig` is project wide parameter file.


```
.
|-- common
|   `-- param.dig
|-- work1.dig
`-- work2.dig
```

### work1.dig

```yaml
_export:
  local1: test1
  !include : common/param.dig

+task:
  echo>: workflow1 ${local1} ${param1} ${param2}
```

### work2.dig

```yaml
_export:
  local2: test2
  !include : common/param.dig

+task:
  echo>: workflow2 ${local2} ${param1} ${param2}
```

### common/param.dig

```
param1: foo
param2: bar
```

### execution results

```
2018-08-24 18:27:38 +0900 [INFO] (0032@[0:test]+work1+task): echo>: workflow1 test1 foo bar
workflow1 test1 foo bar
2018-08-24 18:27:45 +0900 [INFO] (XNIO-1 task-12): Starting a new session project id=1 workflow name=work2 session_time=2018-08-24T09:27:44+00:00
2018-08-24 18:27:45 +0900 [INFO] (0032@[0:test]+work2+task): echo>: workflow2 test2 foo bar
workflow2 test2 foo bar
```


Ref: https://github.com/hiroyuki-sato/digdag-support/tree/master/core_847_projparam

**Comment by hiroyuki-sato** [comment]
Hello, @friendofasquid 

I'm not a core developer, so I don't comment new feature direction.
@muga Could you comment about this issue?

Maybe you know this way require a Digdag server if you change a parameter.
But I think you will use different digdag server for production, test, and development.
So, It may be helpful a partial.
(I wrote a sample in ruby. I can't write python by the way.)

```
cat digdag_env_test.yml
digdag_env: test
```

```
digdag server -m -P digdag_env_test.yml
```

```yaml
_export:
  rb:
    require: scripts/load_params

+load_parameters:
  rb>: LoadParams.load

+task:
  echo>: workflow1 ${digdag_env} ${foo}
```

scripts/load_params.rb

```ruby
require 'yaml'
require 'pp'
class LoadParams
  def load
    conf = YAML.load_file("env_params.yml")
    conf[Digdag.env.params["digdag_env"]].each do |k,v|
      Digdag.env.store[k] = v
    end
  end

end
```

env_params.yml

```yaml
test:
  foo: bar
production:
  foo: baz
```

```
digdag start foo work3 --session now
...
2018-08-27 13:24:04 +0900 [INFO] (0032@[0:foo]+work3+task): echo>: workflow1 test bar
workflow1 test bar
```


Ref: https://github.com/hiroyuki-sato/digdag-support/tree/master/core_847_projparam#work3dig

**Comment by muga** [comment]
@friendofasquid @hiroyuki-sato Sorry for my delayed response. I believe that https://github.com/treasure-data/digdag/pull/845 could solve your issue. https://github.com/treasure-data/digdag/pull/845 enables storing parameter values generated by the current workflow session then, they could be accessed by the next session or other workflows. Please take a look and if you have any questions and suggestions, please feel free to comment on it.

**Comment by friendofasquid** [comment]
#845 Looks like addresses this exact issue. Thanks.

**Comment by nickhall** [comment]
@friendofasquid How did you end up using the parameter store in practice? I've got a similar issue but I'm wondering how you went about initializing the parameters.

**Comment by friendofasquid** [comment]
@nickhall I never did get what I needed into production, but the `param_get` and `param_set` features look like they'd do what we need. See: https://docs.digdag.io/operators/param_get.html

It's not 100% obvious how we'd set different values depending on what environment we're running the code in without restarting the server. One way would be to store that information in a database table and use a digdag operator to query and store. In this case, you'd store your config as a table instead of as a YAML file.
