### ISSUE TITLE
digdag push not works by nginx basic auth.

### ISSUE THREAD

**Issue by toyama0919** [treasure-data/digdag#848]
Hi.

digdag push not works digdag server is basic auth by Nginx.

access route is here.
client => ELB => Nginx:80 => digdag:65432

occured this error(digdag-v0.9.27).

```
digdag push ai --project ai -e 'http://user:password@domain.ap-northeast-1.elb.amazonaws.com/' -l debug
2018-08-24 16:54:00 +0900: Digdag v0.9.27
Creating .digdag/tmp/archive-9044667705279783852.tar.gz...
  Archiving ai.dig
  Archiving common/deploy.dig
  Archiving deploy.dig
Workflows:
  ai.dig
  deploy.dig
error: For input string: "password@domain.ap-northeast-1.elb.amazonaws.com/" (number format)
java.lang.NumberFormatException: For input string: "password@domain.ap-northeast-1.elb.amazonaws.com"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:201)
	at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:112)
	at io.digdag.cli.client.ClientCommand.buildClient(ClientCommand.java:94)
	at io.digdag.cli.client.Push.push(Push.java:119)
	at io.digdag.cli.client.Push.mainWithClientException(Push.java:53)
	at io.digdag.cli.client.ClientCommand.main(ClientCommand.java:64)
	at io.digdag.cli.Main.cli(Main.java:187)
	at io.digdag.cli.Main.main(Main.java:82)
```

**Comment by serihiro** [comment]
@toyama0919 
Digdag implements own url parser and it does not support a URL which includes basic auth id and password. 

https://github.com/treasure-data/digdag/blob/cb983f4e724c0db41b7abe1eb89744c5500b46d0/digdag-cli/src/main/java/io/digdag/cli/client/ClientCommand.java#L174-L202

As a workaround, Digdag cli can be taken http header options from option or SystemConfig file.

For example, you can set arbitrary http request headers with `-H` option.

```sh
$ digdag attempts -H Authorization="Basic aWQ6cGFzc3dvcmQ="
```

Also,  you can set `Authorization` header by adding the following line in your SystemConfig file and specifying it with option `-c` .

```
client.http.headers.Authorization="Basic aWQ6cGFzc3dvcmQ="
```

```sh
$ digdag attempts -c cli.properties
```

Environment variable `DIGDAG_CONFIG` is also can be used

```sh
$ export DIGDAG_CONFIG=client.http.headers.Authorization="Basic aWQ6cGFzc3dvcmQ="
$ digdag attempts
```

For more detail, please see [the reference of CLI](http://docs.digdag.io/command_reference.html#client-mode-commands)

**Comment by hiroyuki-sato** [comment]
@serihiro 

Thank you for telling us workaround.

As far as I remember his requirement is that restrict access to digdag-ui
with Basic authentication too.
As you know, digdag-ui doesn't support authentication mechanism yet.

Do you have any good idea for that?
(Pelase let me know if I need to create another issue)

Best regards.

**Comment by serihiro** [comment]
@hiroyuki-sato 

> Do you have any good idea for that?

Sorry but I have no any good idea about it.
Digdag server uses [Undertow](http://undertow.io/index.html) for WebServer, and as far as I know, Undertow supports BasicAuth like [this sample](https://github.com/undertow-io/undertow/blob/master/examples/src/main/java/io/undertow/examples/security/basic/BasicAuthServer.java).  But I do not know about Digdag security strategy, so I cannot answer something.

If you have a good concrete idea or a security-needed use-case, I think you should to create an other issue and discuss about it there.

**Comment by hiroyuki-sato** [comment]
Hello, @yoyama and @serihiro 

I think this issue already resolved. (I can't close the issue)
A user succeed a basic authentication with IIS

Ref

* [digdag basic auth](https://gist.github.com/hiroyuki-sato/229302a1867025876de7fd1d8ffa2bf1)
* [digdag serverへのブラウザアクセス時に認証を設定する](https://www.capybara-engineer.com/entry/2020/11/20/144252) [Digdag basic authentication with IIS](https://translate.google.com/translate?sl=ja&tl=en&u=https://www.capybara-engineer.com/entry/2020/11/20/144252) (Google translates)

**Comment by yoyama** [comment]
@hiroyuki-sato Thank you for your notification. I will close it.
