### ISSUE TITLE
pushing dig project to server should verify digs

### ISSUE THREAD

**Issue by yanivyalda** [treasure-data/digdag#859]
I pushed a couple of dig files to the server today without checking locally. The incremented version was displayed but the old code still ran. It would be great to verify the uploaded dig's 

Have I missed something?

**Comment by hiroyuki-sato** [comment]
Hello, @yanivyalda 

Digdag doesn't stop running workflow when you push new revision.
Could you tell us what is "should verify" mean?

For example,
Does this mean Digdag should reject push command when an old revision is running?

**Comment by yanivyalda** [comment]
Hi @hiroyuki-sato 

With Verify. I mean it should check the syntax of the dig before pushing. What happens I think is the version number updates but the code still stays the same. I'm going to run a few more tests today to get the correct steps to replicate.

Rejecting push command when old revision is running is a good feature but I have not encountered this.

**Comment by yanivyalda** [comment]
I have tested the following today and here are the steps

**Syntax checking works**
+test1:
sh>: echo 'I should fail'

digdag push track --project -r 0.0.0.1 -endpoint XXXX
_2018-09-07 09:24:05 +1000: Digdag v0.9.27
Creating .digdag/tmp/archive-3086874888794404513.tar.gz...
error: Validating project failed_

**Syntax checking fails**
+test2:
&nbsp;&nbsp;&nbsp;&nbsp;inner_test:
&nbsp;&nbsp;&nbsp;&nbsp;sh>: echo 'I should fail'

digdag push track --project -r 0.0.0.1 -endpoint XXXX
2018-09-07 09:24:21 +1000: Digdag v0.9.27
Creating .digdag/tmp/archive-7202906967196748735.tar.gz...
.
.
.
Use `digdag workflows` to show all workflows.

**Comment by hiroyuki-sato** [comment]
Hello, @yanivyalda 

Thank you for investigating.

The `inner_test:` is valid syntax in Digdag.
`sh>` operator just ignore `inner_test` value.

Digdag uses those values as parameter.
For example, `mail>:` and `sh>:`

```yaml
+step1:
  mail>: body.txt
  subject: workflow started
  to: [me@example.com]
```

```yaml
+sample:
  sh>: set
  shell: [/bin/zsh]
```

**Comment by yanivyalda** [comment]
hi @hiroyuki-sato that was a markdown typo
it should have been
+inner_test:

I also noticed this, the console updated the revision
  revision: 0.0.35
but the ui still kept the old version.

**Comment by hiroyuki-sato** [comment]
Hello, @yanivyalda 

Thank you for replying. 

I succeed to reproduce your issue in my environment.
I also want to know an error during push command

```yaml
timezone: UTC

+test2:
    +inner_test:
    sh>: echo 'I should fail'
```

digdag push succeed... but,

```
digdag push test
2018-09-07 14:01:50 +0900: Digdag v0.9.27
Creating .digdag/tmp/archive-464841680752755551.tar.gz...
  Archiving invalid.dig
Workflows:
  invalid.dig
Uploaded:
  id: 1
  name: test
  revision: c6d330b2-b356-4d5d-9ce5-ee79155b2557
  archive type: db
  project created at: 2018-09-07T05:01:52Z
  revision updated at: 2018-09-07T05:01:52Z

Use `digdag workflows` to show all workflows.
```


`digdag start` failed.

```
digdag start test invalid --session now
2018-09-07 14:02:12 +0900: Digdag v0.9.27
error: Status code 400: {"message":"Parameter '+inner_test' must be an object or array of objects","status":400}
```

**Comment by hiroyuki-sato** [comment]
Hello, @yanivyalda 

Could you try the folllowing command as workaround?
You can use `digdag check` command before the push.

```
digdag check
2018-09-07 14:42:31 +0900: Digdag v0.9.27
  System default timezone: Asia/Tokyo

error: Parameter '+inner_test' must be an object or array of objects (config)
```

Best regards.

**Comment by yanivyalda** [comment]
hi @hiroyuki-sato digdag check works for now.

**Comment by muga** [comment]
It'd better for digdag-server to verify .dig files when they are pushed and sessions are triggered.

**Comment by yoyama** [comment]
@hiroyuki-sato #1026 fix this issue? If so I would like to close this issue.

**Comment by yoyama** [comment]
Close this issue but feel free to reopen if need.
