### ISSUE TITLE
[Testing] We need to write more api e2e tests for Digdag server

### ISSUE THREAD

**Issue by serihiro** [treasure-data/digdag#888]
# What is this issue ?
- Digdag server has many api endpoints, on the other hand, the e2e test coverage for them is very low.
- So I felt that it is difficult to modify existing api endpoints for now
- In order to make development of Digdag server more safer, I think we need to write more e2e test for api endpoints.

# How to do it ?
- I think the following test is good example to write e2e tests for Digdag server
- So it seems good to write e2e tests for other endpoints with reference to this.

https://github.com/treasure-data/digdag/blob/97cfae11c3d531975a3becef06cea9a63029a885/digdag-tests/src/test/java/acceptance/ServerErrorStatusCodeIT.java#L89-L100

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
