### ISSUE TITLE
High CPU usage in webUI

### ISSUE THREAD

**Issue by mjtice** [treasure-data/digdag#889]
I've noticed that when I live the webUI open the CPU on my 2018 Macbook Pro goes crazy (upwards of 70% cpu usage or more).

I was peeking through the source code when I saw this:
https://github.com/treasure-data/digdag/blob/3cac10b2bacb8e47a424cd7bbd11b6a6d1d6f272/digdag-ui/console.jsx#L1555

Looking at the stackoverflow accepted answer it looks like skyline3000 updated their answer in 2017.  They say:
>According to this question, some people have found better performance across all browsers, especially Chrome, with `transform: rotateZ(360deg)`.

I was wondering if any testing has been done using that transformation?

**Comment by hiroyuki-sato** [comment]
Hello, @mjtice 
Thank you for reporting the issue.

Could you tell me the following?
I can't reproduce your issue in my environment.

* OS version:
* Digdag version:
* Browser version:
* Java Version:
* Reproduce steps:

My test environment.

* OS version: 10.13.6
* Digdag version: 0.9.30
* Browser version: Safari 12(13606.2.11)
* Java Version: 1.8.0_121
* Test steps: 
  * `digdag server -m`
  * access `http://localhost:65432`

It seems that the StackOverflow page is here
[CSS keyframe animation CPU usage is high, should it be this way?](https://stackoverflow.com/questions/13176746/)

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
