### ISSUE TITLE
Any plans to support specifying SLA using both "time" and "duration" options?

### ISSUE THREAD

**Issue by ryysud** [treasure-data/digdag#891]
I want to apply workflow to execute tasks both when the execution time exceeds the threshold and when it exceeds a specific time, but it is an error.

For example, Use Digdag v0.9.27.

1. Create example.dig
```yaml
timezone: UTC

sla:
  duration: 00:00:10
  +duration-notice:
    echo>: 'sla duration!'
  time: 12:00:00
  +time-notice:
    echo>: 'sla time!'

+task:
  echo>: sleep 3600
```

2. Run example.dig

example.dig failed with `error: SLA must be specified using either the 'time' or 'duration' option (config)` error.

```bash
$ docker run -it --rm -v `pwd`:/src szyn/docker-digdag:latest run -a example.dig
2018-10-03 11:15:18 +0000: Digdag v0.9.27
2018-10-03 11:15:21 +0000 [WARN] (main): Using a new session time 2018-10-03T00:00:00+09:00.
2018-10-03 11:15:21 +0000 [INFO] (main): Using session /src/.digdag/status/20181003T000000+0900.
error: SLA must be specified using either the 'time' or 'duration' option (config)
```

Do you any plans to support specifying SLA using both "time" and "duration" options?

**Comment by yoyama** [comment]
If there is no additional comment I will close it later.

**Comment by ryysud** [comment]
@yoyama Sorry for the delay in my reply.

@muga Thank you for your suggestion. I will try it!
> May you want to setup sla option for each task instead of workflow (attempt) correct? Can task_ttl help your case?
