### ISSUE TITLE
Unable to build digdag by gradle

### ISSUE THREAD

**Issue by yuvrajbset** [treasure-data/digdag#893]
I was tying to build the digdag using gradlew build but was unable to do it. As I was receiveing the below mentioned error message.
$ ./gradlew build

> Configure project :
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-cli
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-client
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-core
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-docs
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-guice-rs
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-guice-rs-server
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-guice-rs-server-undertow
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-plugin-utils
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-server
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-spi
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-standards
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-storage-s3
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-tests
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Configure project :digdag-ui
Publication mavenJava not found in project :.
Publication mavenJava not found in project :digdag-docs.

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :digdag-client:compileJava UP-TO-DATE
> Task :digdag-client:processResources UP-TO-DATE
> Task :digdag-client:classes UP-TO-DATE
> Task :digdag-client:jar UP-TO-DATE
> Task :digdag-guice-rs-server:compileJava UP-TO-DATE
> Task :digdag-guice-rs-server:processResources NO-SOURCE
> Task :digdag-guice-rs-server:classes UP-TO-DATE
> Task :digdag-guice-rs-server:jar UP-TO-DATE
> Task :digdag-spi:compileJava UP-TO-DATE
> Task :digdag-spi:processResources NO-SOURCE
> Task :digdag-spi:classes UP-TO-DATE
> Task :digdag-spi:jar UP-TO-DATE
> Task :digdag-plugin-utils:compileJava UP-TO-DATE
> Task :digdag-plugin-utils:processResources NO-SOURCE
> Task :digdag-plugin-utils:classes UP-TO-DATE
> Task :digdag-plugin-utils:jar UP-TO-DATE
> Task :digdag-core:compileJava UP-TO-DATE
> Task :digdag-core:processResources UP-TO-DATE
> Task :digdag-core:classes UP-TO-DATE
> Task :digdag-core:jar UP-TO-DATE
> Task :digdag-guice-rs:compileJava UP-TO-DATE
> Task :digdag-guice-rs:processResources NO-SOURCE
> Task :digdag-guice-rs:classes UP-TO-DATE
> Task :digdag-guice-rs:jar UP-TO-DATE
> Task :digdag-guice-rs-server-undertow:compileJava UP-TO-DATE
> Task :digdag-guice-rs-server-undertow:processResources NO-SOURCE
> Task :digdag-guice-rs-server-undertow:classes UP-TO-DATE
> Task :digdag-guice-rs-server-undertow:jar UP-TO-DATE
> Task :digdag-server:compileJava UP-TO-DATE
> Task :digdag-server:processResources NO-SOURCE
> Task :digdag-server:classes UP-TO-DATE
> Task :digdag-server:jar UP-TO-DATE
> Task :digdag-standards:compileJava UP-TO-DATE
> Task :digdag-standards:processResources UP-TO-DATE
> Task :digdag-standards:classes UP-TO-DATE
> Task :digdag-standards:jar UP-TO-DATE
> Task :digdag-storage-s3:compileJava UP-TO-DATE
> Task :digdag-storage-s3:processResources UP-TO-DATE
> Task :digdag-storage-s3:classes UP-TO-DATE
> Task :digdag-storage-s3:jar UP-TO-DATE
> Task :digdag-ui:compileJava NO-SOURCE
> Task :digdag-ui:buildUi FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':digdag-ui:buildUi'.
> A problem occurred starting process 'command 'npm''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 30s
26 actionable tasks: 1 executed, 25 up-to-date

Thanks in advance

**Comment by muga** [comment]
```
> Task :digdag-ui:buildUi FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':digdag-ui:buildUi'.
> A problem occurred starting process 'command 'npm''
```
looks like npm command failed as far as I know from your build log messages. Can you give me your Node version and Npm version? Node v8 is prerequired as you might know.

**Comment by yuvrajbset** [comment]
I installed the node js setup of version 8.x but when  i checked the npm version it was 6.4.1 can u please share the link for node js 8.x which has npm version of 8.x. It would be a great help. Thanks in advance for ur help

**Comment by hiroyuki-sato** [comment]
Hello, @yuvrajbset 

Could you tell us your build environment?
I succeed to build Digdag in the following environment.

* OS(sw_vers): macOS 10.13.6
* Java(java -version): 1.8.0_121
* nodejs(node --version): v8.11.3
* npm(npm --version): 5.6.0 
* Digdag Source(git log | head -1): 90b7a163f2290b1592e08e9ef026aab3243b9543

**Comment by yuvrajbset** [comment]
Please find the build environment below:
OS(sw_vers): Windows 10 Pro 10.0.17134 Build 17134
Java(java -version): 1.8.0_121
nodejs(node --version): v8.12.0
npm(npm --version): 6.4.1
Digdag Source(git log | head -1): 0.9.31--current version

**Comment by yuvrajbset** [comment]
I have tried building with Node 8.11.4 and npm 5.6.0 but still I am receiving the same message in the environment mentioned me. It would be great help if you let me know if I am missing something. Thanks for all your help.

Thanks,
yuvrajbset

**Comment by szyn** [comment]
Hello, @yuvrajbset. 

> I have tried building with Node 8.11.4 and npm 5.6.0 but still I am receiving the same message in the environment mentioned me.

It looks like it might have something to do with the remaining `node_modules` from the previous build. 
Could you delete `node_modules` the following and retry to build?

```
### Change dir to digdag root
$ cd path/to/digdag
### Change dir to digdag-ui
$ cd digdag-ui
### Delete node_modules
$ rm -rf node_modules/
```

**Comment by yoyama** [comment]
I will close it because no response, but feel free to re-open if the issue is still continuing.
