### ISSUE TITLE
[Q] How can I loop through the files in a directory?

### ISSUE THREAD

**Issue by kulmam92** [treasure-data/digdag#894]
One of the typical workflow is to get the list of files in a directory(local or nfs) and process it one by one. Is there a predefined operator to get that list from a directory? If not, can you post an implementation example?

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

The following ways may help for your use case.
Could you try it?

* Use builtin `py>`(Python) or `rb>`(Ruby) operator.
  * [Python operator](http://docs.digdag.io/python_api.html)
  * [Ruby operator](http://docs.digdag.io/ruby_api.html#defining-variables)
* Use 3rd party plugin (ie. [digdag-plugin-shresult](https://github.com/takemikami/digdag-plugin-shresult))

**Comment by muga** [comment]
@kulmam92 @hiroyuki-sato I guess that you've used Digdag by `local` mode but, `server` mode doesn't guarantee that tasks will run on same instance where files listed by previous task exist. If you use NFS or S3, one task can list files on it, store the list on store param and next tasks can see each file path from the store param. 

It sounds reasonable to use command based operators like `py`, `rb` or `sh` that @hiroyuki-sato mentioned to execute entire of your tasks or parts of your tasks.

**Comment by kulmam92** [comment]
Hi @hiroyuki-sato and @muga 

Thank you for replying my question. 
I was able to implement it using Python operator

`from __future__ import print_function
import digdag
import os, re, time
from datetime import datetime

def get_file_name(file_path, file_pattern):
    file_list = []
    file_pattern = re.compile(file_pattern)
    directory = os.listdir(file_path)

    for files in directory:
        if re.match(file_pattern, files):
            full_path = os.path.join(file_path, files)
            m_date = datetime.fromtimestamp(os.path.getmtime(full_path)).strftime('%Y-%m-%d')
            print(m_date)
            file_list.append([files, m_date])
    digdag.env.store({"file_list": file_list})`

`timezone: UTC

+filelist:
  py>: get_file_from_path.get_file_name
  file_path: '/fileshare/test'
  file_pattern: 'myfile\_.*\.xlsx$'

+execute:
  +step1:
    loop>: ${file_list.length}
    _do:
      +step_1_echo:
        sh>: echo ${file_list[i]}`

One more question. 
If I test get_file_from_path.py from python terminal, I got below error.
AttributeError: module 'digdag' has no attribute 'env'

Is there a way to resolve this error?

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

Digdag call this [script](https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/resources/digdag/standards/py/runner.py) before run your Phthon script. That's why you can't call your script from python terminal.

It may need mock script for testing it.

**Comment by kulmam92** [comment]
Hi @hiroyuki-sato

Thank you for clear explanation.

**Comment by doctor** [comment]
Hello @hiroyuki-sato 
I followed the same steps. Thanks for the explanation. However my array size is 2161 and running into an error with limit being 1000. Is there a configuration parameter I can set to allow more than 1000 values?

**Log message:**
2022-05-24 16:39:46 -0700 [INFO] (main): Starting a new session project id=1 workflow name=python_array session_time=2022-05-22T00:00:00+00:00
2022-05-24 16:39:47 -0700 [INFO] (0018@[0:default]+python_array+python_task+set_var): py>: tasks.MyWorkflow.get_dealers
2022-05-24 16:39:47 -0700 [INFO] (0018@[0:default]+python_array+python_task+print_var): **loop>: 2161**
2022-05-24 16:39:47 -0700 [ERROR] (0018@[0:default]+python_array+python_task+print_var): **Configuration error at task +python_array+python_task+print_var: Too many loop subtasks. Limit: 1000 (config)**
2022-05-24 16:39:47 -0700 [INFO] (0018@[0:default]+python_array^failure-alert): type: notify
error: 
  * **+python_array+python_task+print_var:
    Too many loop subtasks. Limit: 1000 (config)**

**Comment by hiroyuki-sato** [comment]
Hello, @doctor.

Maybe, you can use `io.digdag.limits.maxWorkflowTasks=3000`

Write this value to your configuration file or use `-X` option.

`digdag -X io.digdag.limits.maxWorkflowTasks=3000 run`..

**Comment by doctor** [comment]
Thanks @hiroyuki-sato 
-X option works fine. I am able to test I can execute with the array (2161 elements) without issues.
When I tried to put this in a properties file, I am not able to get digdag run. Can you please suggest?

**Error message: error: Is a directory (io)**

**Properties file:**
```
~/.config/digdag/config
base ❯ ls     
client.properties

~/.config/digdag/config
base ❯ cat client.properties 
io.digdag.limits.maxWorkflowTasks=3000
```

**Error:**
```
base ❯ digdag run python_array.dig --rerun
2022-05-25 10:46:25 -0700: Digdag v0.10.4
error: Is a directory (io)
```

**Comment by hiroyuki-sato** [comment]
Hello, @doctor. The `~/.config/digdag/config` is the configuration file. not directory.

**Comment by doctor** [comment]
Thanks @hiroyuki-sato
I tried that but the value is not getting picked up.
```
~/.config/digdag
base ❯ cat config          
io.digdag.limits.maxWorkflowTasks=3000
```

**Error:**
`digdag run python_array.dig --rerun`
```
2022-05-25 20:57:33 -0700 [ERROR] (0018@[0:default]+python_array+python_task+print_var): Configuration error at task +python_array+python_task+print_var: Too many for_each subtasks. Limit: 1000 (config)
2022-05-25 20:57:33 -0700 [INFO] (0018@[0:default]+python_array^failure-alert): type: notify
error: 
  * +python_array+python_task+print_var:
    Too many for_each subtasks. Limit: 1000 (config)
```

**Comment by hiroyuki-sato** [comment]
Hello, @doctor 
Could you try `executor.task_max_run = 3000` instead of `io.digdag.limits.maxWorkflowTasks`?

**Comment by doctor** [comment]
Thank you @hiroyuki-sato `executor.task_max_run = 3000` works!
