### ISSUE TITLE
[feature-request] mssql operator

### ISSUE THREAD

**Issue by kulmam92** [treasure-data/digdag#897]
Is there a plan to implement mssql operator?
If I need to run mssql script, what will be the good option?

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

As far as I know, Microsoft SQL Server operator doesn't exist yet.
Probably, you can connect it with `py>` operator.
Otherwise, it's a good chance for you to create a new plugin by yourself.

**Comment by kulmam92** [comment]
Hi @hiroyuki-sato

It will be better, if digdag has jdbc operator at least. JDBC driver exists in airlfow and it’s easier to run simple sql script even though there’s no specific operator.
https://github.com/apache/incubator-airflow/blob/master/airflow/operators/jdbc_operator.py

I will see if I can create mssql plugin.
