### ISSUE TITLE
[feature-request] snowflake operator

### ISSUE THREAD

**Issue by kulmam92** [treasure-data/digdag#898]
snowflake is getting popular these days.
Can someone implement snowflake operator?
What should I do to run snowflake query? snowflake provides jdbc driver.

Including link to airflow's snowflake operator
https://github.com/apache/incubator-airflow/blob/master/airflow/contrib/operators/snowflake_operator.py

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

As far as I know, that plugin doesn't exist yet.
It's a good time for developing new plugin :-)

Current 3rd party plugins may help for developing new operator.

This is a plugin example.
* [digdag-plugin-example](https://github.com/myui/digdag-plugin-example/)

And 3rd party plugins.
* [digdag-slack](https://github.com/szyn/digdag-slack/commits/master)
* [retz-digdag-plugin](https://github.com/retz/retz-digdag-plugin)
* [digdag-plugin-ssh](https://github.com/hiroyuki-sato/digdag-plugin-ssh)
* [digdag-hangouts-chat](https://github.com/tamanyan/digdag-hangouts-chat)
* [digdag-plugin-mysql](https://github.com/hiroyuki-sato/digdag-plugin-mysql)
* [digdag-plugin-dfs_wait](https://github.com/kimutansk/digdag-plugin-dfs_wait)
* [k8s_job](https://github.com/septeni-original/k8s_job)
* [digdag-operator-emr_fleet](https://github.com/civitaspo/digdag-operator-emr_fleet)
* [digdag-operator-athena](https://github.com/civitaspo/digdag-operator-athena)
* [digdag-plugin-shresult](https://github.com/takemikami/digdag-plugin-shresult)
* [digdag-operator-cost_explorer](https://github.com/civitaspo/digdag-operator-cost_explorer)
* [digdag-operator-param](https://github.com/civitaspo/digdag-operator-param)

**Comment by muga** [comment]
As commented on https://github.com/treasure-data/digdag/issues/897, jdbc operator might be good.

**Comment by pakye11** [comment]
Now, it looks like the plugin already exists.

https://github.com/flinters/digdag_operator_snowflake
