### ISSUE TITLE
[feature-request] Use Custom CommandExecutors

### ISSUE THREAD

**Issue by muga** [treasure-data/digdag#901]
Some users request the option for using their custom CommandExecutor to execute command operator e.g. `py>`, `rb>`. They want to execute the operators on different place from Digdag where are running. Currently we don't have any extension point to load custom CommandExecutor and specify it for command operators.

**Comment by civitaspo** [comment]
I wrote Scripting Operators without custom CommandExecutors. > https://github.com/civitaspo/digdag-operator-ecs_task#experimental-scripting-operators
This is what I wanted to do. When the CommandExecutor can be implemented, we will reimplement these Scripting Operators.
