### ISSUE TITLE
Large Long value in variable is populated incorrectly

### ISSUE THREAD

**Issue by kamikaseda** [treasure-data/digdag#916]
## Problem Description
Digdag expands variable incorrectly in case of large long value.

## Reproduction
Following workflow expands `${num}` variable as `23843037174560268`. But expected value is `23843037174560269`.

```
_export:
  num: 23843037174560269

+task1:
  echo>: ${num}
```

```
io.digdag.core.agent.OperatorManager: echo>: 23843037174560268
```

## Request
Digdag can use correct value.

**Comment by hiroyuki-sato** [comment]
@kamikaseda reported value larger than Number.MAX_SAFE_INTEGER. Please take a look when you have time.

**Comment by kamikaseda** [comment]
@hiroyuki-sato I see. So, the workaround is to use STR.

```
_export:
  num: 23843037174560269
  str: "23843037174560269"

+task1:
  echo>: ${num}

+task2:
  echo>: ${str}
```

```
2019-02-25 10:31:58 +0900 [INFO] (0018@[0:default]+large_num+task1): echo>: 23843037174560268
23843037174560268
2019-02-25 10:31:58 +0900 [INFO] (0018@[0:default]+large_num+task2): echo>: 23843037174560269
23843037174560269
```
