### ISSUE TITLE
General Questions?

### ISSUE THREAD

**Issue by jaymed** [treasure-data/digdag#924]
Does this project have a Gitter or chat messaging room?

**Comment by yanivyalda** [comment]
I would love this. Discourse and slack work well in most products I use.

**Comment by hiroyuki-sato** [comment]
Hello, @jaymed and @yanivyalda 

No. There is no message room (Slack, IRC ..) for Digdag yet.
If you have any question, could you use this issue page?

Best regards.

**Comment by yoyama** [comment]
I close this but feel free to reopen if you need. Thanks!
