### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by jaymed** [treasure-data/digdag#925]
I'd like to understand what approach others are taking in order to enhance the operators available to DigDag. The workflow management part of this tool is great. The downside is that it lacks an extensive list of operators and/or plugins to integrate it with other tools and services. From what I understand, you can add operators using dynamic plugins written in java. I also understand that an alternative might be to use the py operator to run custom python module code to interact with tools and services. One limitation with this approach is that you can't make the python task code common across your projects and you don't have access to secrets like you do by writing a java plugin. It'd be great to get opinions from others about this. A common contrib project for plugins might also be a good idea so that folks can help grow the list of available operators. I would appreciate your help and guidance.

**Comment by hiroyuki-sato** [comment]
Hello, @jaymed 

Maybe I don't understand your questions completely,
But I try to answer.

This is the new operator example.
* [digdag-plugin-example](https://github.com/myui/digdag-plugin-example/) 

The following lists are 3rd party plugins.

* [digdag-slack](https://github.com/szyn/digdag-slack/commits/master)
* [retz-digdag-plugin](https://github.com/retz/retz-digdag-plugin)
* [digdag-plugin-ssh](https://github.com/hiroyuki-sato/digdag-plugin-ssh)
* [digdag-hangouts-chat](https://github.com/tamanyan/digdag-hangouts-chat)
* [digdag-plugin-mysql](https://github.com/hiroyuki-sato/digdag-plugin-mysql)
* [digdag-plugin-dfs_wait](https://github.com/kimutansk/digdag-plugin-dfs_wait)
* [k8s_job](https://github.com/septeni-original/k8s_job)
* [digdag-operator-emr_fleet](https://github.com/civitaspo/digdag-operator-emr_fleet)
* [digdag-operator-athena](https://github.com/civitaspo/digdag-operator-athena)
* [digdag-plugin-shresult](https://github.com/takemikami/digdag-plugin-shresult)
* [digdag-operator-cost_explorer](https://github.com/civitaspo/digdag-operator-cost_explorer)
* [digdag-operator-param](https://github.com/civitaspo/digdag-operator-param)
* [digdag-operator-ecs_task](https://github.com/civitaspo/digdag-operator-ecs_task) 
* [digdag-plugin-azure](https://github.com/kencharos/digdag-plugin-azure)
* [digdag-plugin-mssql](https://github.com/kulmam92/digdag-plugin-mssql)

You can use secret value in Python script.

```
digdag secret --local --set secret_key=secret_value
```

```yaml
+e:
  py>: python_args.env_argument
  _env:
    required1: ${secret:secret_key}
```

```pytyon
def env_argument():
    print("arg1 = " + str(os.environ.get('required1')))
```

* Ref: [Complete example](https://github.com/hiroyuki-sato/digdag-support/tree/master/core_925_python_secrets)

Please feel free if you have additional questions.

**Comment by jaymed** [comment]
This is great information. Thanks for pointing out the availability of secrets within .dig files. I appreciate that.

**Comment by yoyama** [comment]
@hiroyuki-sato 3rd party operator list may be useful information for document.

**Comment by hiroyuki-sato** [comment]
Check this document.
https://dev.to/hiroysato/digdag-workflow-engine-link-collection-13hf
