### ISSUE TITLE
server side workflow log filtering

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#93]
It would be useful for users to be able to filter logs from workflows executed on the server.

Currently all output from workflow and its tasks, both stdout/err as well as java log messages are concatenated into a single log file. Thus it's not easy to reliably filter out only e.g. stdout or on java logging level.

I propose changing the digdag log file format to be a structured stream of messages (e.g. msgpack) that combines the raw log message with metadata like timestamp and whether the message is from stdout/err or java logging and then the logging level. 

I.e. something like:

``` json
// ...
{
  "ts": 1463387968,
  "stream": "OUT",
  "message": "hello world",
},
{
  "ts": 1463388012,
  "stream": "LOG",
  "level": "WARN",
  "message": "the foo failed to bar the baz because quux",
},
{
  "ts": 1463388153,
  "stream": "ERR",
  "message": "The quick brown fox jumps over the lazy dog",
},
{
  "ts": 1463388265,
  "stream": "LOG",
  "level": "DEBUG",
  "message": "...",
},
// ...
```

We could then have server the expose a rest api endpoint for querying this stream or have the client fetch all log entries and perform the filtering client-side.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
