### ISSUE TITLE
Use Environment credentials for AWS Operators

### ISSUE THREAD

**Issue by friendofasquid** [treasure-data/digdag#934]
We are trying to use the `emr` operator, but it seems that the code will not check the environment for AWS credentials, and that these must be set in Digdag secrets. Just want to double-check this isn't possible and to request this enhancement.

See: https://github.com/treasure-data/digdag/blob/6547542a274ac1a30c88c82e509ac0742d6d872e/digdag-standards/src/main/java/io/digdag/standards/operator/aws/EmrOperatorFactory.java#L280

**Comment by hiroyuki-sato** [comment]
Hello, @friendofasquid 

I'm not familiar EMR. but it may needs implement like the following.

https://github.com/treasure-data/digdag/blob/master/digdag-storage-s3/src/main/java/io/digdag/storage/s3/S3StorageFactory.java#L52-L79

BTW, Just FYI.
`emr>` operator has known issue #632.

**Comment by friendofasquid** [comment]
It looks like EMR doesn't support using environment variables for authentication. That's a shame, as Digdag should probably rely on that convention for all AWS operators, using the environment variables when available.
