### ISSUE TITLE
[Q] Production Server Spec

### ISSUE THREAD

**Issue by kulmam92** [treasure-data/digdag#945]
Hi

If there's anyone who deployed digdag with HA configuration, what's your server spec?
I'd like to get an idea on what others are using.

**Comment by hiroyuki-sato** [comment]
Hello, @kulmam92 

What is Server Spec mean?

You can deploy digdag HA cluster with `--disable-executor-loop` and `--disable-local-agent` options. Could you read the following documents?

Please let me know if you want to need more information. I'll try to translate some documents.

* [API server, agent, workflow executor, and schedule executor](http://docs.digdag.io/internal.html?highlight=disable%20executor%20loop#api-server-agent-workflow-executor-and-schedule-executor)
* [Server-mode commands](http://docs.digdag.io/command_reference.html?highlight=disable%20executor%20loop#server-mode-commands)

Some Japanese documents are available..(It use google translate.)

https://translate.google.com/translate?sl=ja&tl=en&u=https%3A%2F%2Ftechblog.zozo.com%2Fentry%2Fdigdag_ha

This site use pgpool-II for building redundant PostgreSQL.
https://speakerdeck.com/dmmlabo/digdagheri-ci-batutiwoyi-xing-sitexing-seninaruohua?slide=24

Using Digdag and Docker for job execution
https://translate.google.com/translate?sl=ja&tl=en&u=https%3A%2F%2Fdevelopers.microad.co.jp%2Fentry%2F2018%2F05%2F24%2F131136

**Comment by sonots** [comment]
My company deploys didgag with HA.

1. 2 instances for `digdag server --disable-executor-loop and --disable-local-agent` for Web UI and API. We call them as digdag masters. The spec is very poor.
2. 2 instances for `digdag server` with no disable options. We do not use web ui and api on them. We call them as digdag agents. The spec depends on our workflows.

We also mount NFS (Amazon EFS) for them.

The article for more details is at https://techblog.zozo.com/entry/digdag_ha (But, written in Japanese...)

**Comment by kulmam92** [comment]
Hi Hiroyuki

Thank you for the reply.
I meant core, disk and memory.
I don’t think I can use docker since I need to connect sql server using
windows authentication.

Best,
Yong

**Comment by kulmam92** [comment]
@sonots I read that article and was really helpful. Google translator works quite well.

**Comment by hiroyuki-sato** [comment]
@sonots, Thank you for replying.
The first link which I introduced was your site page. 😄 
Could you tell us server spec (number of a CPU core, memory, etc.) in your Digdag environment?

**Comment by sonots** [comment]
I don’t think the information is helpful because required spec depends on the workload.

**Comment by kulmam92** [comment]
I have one more question about HA configuration. In case of airflow you can’t have multiple schedulers running at the same time.

Problems with the Typical Apache Airflow Cluster
The problem with the traditional Airflow Cluster setup is that there can’t be any redundancy in the Scheduler daemon. If you were to have multiple Scheduler instances running you could have multiple instances of a single task be scheduled to be executed.
Quoted from http://site.clairvoyantsoft.com/making-apache-airflow-highly-available/

Do you know why it’s okay for digdag to have multiple schedule executor running at the sane time?

**Comment by sonots** [comment]
Digdag manages such data on postgresql. Digdag server can control not to run scheduled tasks duplicatedly.

**Comment by kulmam92** [comment]
@sonots 
I have some questions when setting up HA.

1. digdag server option for Agent + Workflow executor + Schedule executor
Did you add for this server or you didn't use any disable option?
--disable-*
2. log location
When you mount NFS for logging did you point all server to the same folder or did you create individual folder for each server? If you point all four servers to the same folder isn't there some kind of contention?

**Comment by kulmam92** [comment]
I'm leaving comment to clear my question about the log location

[I tried making Digaag an HA configuration](https://techblog.zozo.com/entry/digdag_ha)
> About the task execution log location
> When using digdag server with only one server, I think that it is often that task execution log (contents written by task to standard output) is stored in local storage on the server. However, when taking the configuration as introduced above, it is necessary to place the execution log in a place where all servers can read and write. One way to do this is to share the same directory with all Digdags in the network using a method such as NFS.

I ended up using UNC path to make all the digdag servers to be pointed to the same tasklog location like below. I wasn't able to check the log from UI, when I pointed tasklog location to a local directory. 
I'm running digdag on windows.
```
-O //mypath.file.core.windows.net/digdag/digdag/logs/tasklogs
-A //mypath.file.core.windows.net/digdag/digdag/logs/vmdda1/accesslogs
-L //mypath.file.core.windows.net/digdag/digdag/logs/vmdda1/server.log
```

**Comment by kulmam92** [comment]
@sonots 
Have you checked the following link?
[Digdag server workflow executor · agent](https://qiita.com/pilot/items/69cbae56d85a443fb623)

> How to use these options
> During actual operation, it seems to be used to divide roles among multiple servers as follows
> 
> API Reception & workflow executor server
> Two units for redundancy, there is no need to increase it anymore
> It is assumed that there is no load enough to make API reception and workflow executor separate machines
> Do not open the API entrance to the internet (as it may be subject to massive attacks)
> Specify bind address 0.0.0.0
> disable-local-agent specification
> agent
> At least two more for redundancy, further increase according to the weight / amount of task
> Bind address not specified (API not accepted from other machine)
> disable-executor-loop specification
> By doing this, even if the task becomes heavy / the quantity increases, API acceptance / queuing / scheduling should be possible
> 
> agent machine want to not run the scheduler, but now it seems impossible to specify such

It seems to more reasonable to divide servers like above. What do you think?

**Comment by sonots** [comment]
Do we have some places about discussing how to use digdag? I think that GitHub issue is not right place to do this. GitHub issue should be used to file bugs or feature requests.

**Comment by yanivyalda** [comment]
hi @sonots we have a very similar setup to your's with 'digdag masters' and 'digdag agents'. Only issue is that logs are **only showing on the agents** and not on the masters which we use for the UI. 

We've configured log-server.type to s3 but this url is not shared across. So when you look at session results the request to **api/logs/xxx/files** is empty on masters and only available on the agent. 

Do you have a similar issue?
