### ISSUE TITLE
[question] Why not loading system plugins on server mode?

### ISSUE THREAD

**Issue by takashima0411** [treasure-data/digdag#949]
[`loadSystemPlugins`](https://github.com/treasure-data/digdag/blob/master/digdag-cli/src/main/java/io/digdag/cli/Command.java#L103) method defined In `Command.java` , and used in [`ClientCommand.java`](https://github.com/treasure-data/digdag/blob/master/digdag-cli/src/main/java/io/digdag/cli/client/ClientCommand.java#L103) and [`Run.java`](https://github.com/treasure-data/digdag/blob/master/digdag-cli/src/main/java/io/digdag/cli/Run.java#L239) .
But, this method don't used in [`Server.java`](https://github.com/treasure-data/digdag/blob/master/digdag-cli/src/main/java/io/digdag/cli/Server.java). (maybe same other path on server mode)
Why?  SystemPlugin not Support on Server mode?

**Comment by hiroyuki-sato** [comment]
Hello, @takashima0411 

IIUC, If it is useful for Server, It is just still implementing.

BTW, Do you know what feature system-plugin.repositories use in ClientCommand and Run?

I've heard Digdag will support various plugins like authentication, logging so on.
Do you think it uses for that?

I tried to implement it once, but It couldn't load the plugin.

**Comment by muga** [comment]
Hi @takashima0411, we're probably OK to enable the system plugins loading on server. But before that, can you share your use care that you want to use system plugins? that's same questions as @hiroyuki-sato commented above though.

**Comment by takashima0411** [comment]
Hi @hiroyuki-sato and @muga. thank you your response.
The use of the system plugin has not been decided yet.
Because I noticed this while reading the source code.

**Comment by hiroyuki-sato** [comment]
Hello, @takashima0411 

Thank you for your reply.

I think In most case, Current active members don't develop Digdag from the first. So, it is hard to answer "Why .." question.
If a new feature requires system plugin in Server mode, It needs to enable it.

**Comment by muga** [comment]
Thank you for clarifying. Since I think that we already has enough information to close this ticket, I'm going to close it. but please feel free to reopen if need.
