### ISSUE TITLE
[issue] digdag possibly fails silently

### ISSUE THREAD

**Issue by sonots-zozo** [treasure-data/digdag#950]
I encountered a situation that the digdag failed, but no error message is shown on digdag Web UI.
It is probably because this log is with trace level.

https://github.com/treasure-data/digdag/blob/c51f2040b2eeeffad6e77a7ba435746c2e255619/digdag-core/src/main/java/io/digdag/core/workflow/WorkflowExecutor.java#L1116-L1117

This article (Japanese) http://labs.septeni.co.jp/entry/2018/05/18/205544 also says that he encountered a situation that he could not find the reason without --log-level trace.

```
2018-04-27 04:41:10 +0000 [TRACE]
...
io.digdag.core.workflow.WorkflowExecutor: Task failed with error {"message":"Too many tasks. Limit: 1000, Current: 999, Adding: 4 (task limit exceeded)"
```

This log is about failure of digdag, so I feel the log level should be ERROR level rather than TRACE. 
Any reasons that the level is TRACE? Any plans to change the log level?

**Comment by muga** [comment]
Let me take a look. If trace log level only can show the error message, that's not good.

**Comment by muga** [comment]
closing it. #951 will mitigate this issue.

**Comment by sonots** [comment]
#951 looks that it is only for task limit errors.
I doubt that my error might be not related to the task limit errors. 

How about changing this line to ERROR level?
