### ISSUE TITLE
Mysql Database type in digdag

### ISSUE THREAD

**Issue by nyerramaneni** [treasure-data/digdag#963]
Hi I want to use mysql as backend database instead of postgresql. I tried by changing 
database.type = mysql in config file but it is not working .How can I use mysql as backend database for Digdag. Can you please  let me know is there any possibility to use other SQL / NoSQL Databases instead of postgresql .

**Comment by nyerramaneni** [comment]
Hi @hiroyuki-sato thanks for responding.

We are using Digdag to orchestrate our pipelines. We are using backend MongoDB to maintain data.So at finally we want to maintain same data storage for whole project. According to Digdag documentation it supports SQL database(Postgresql) , so for that reason I asked whether MySQL is compatibility for Digdag. Is there any option to maintain MongoDB as database for Digdag .

**Comment by hiroyuki-sato** [comment]
Hello, @nyerramaneni 

I don't see your point. Especially MongoDB and MySQL relationship. 

If you need MySQL operator,  [digdag-plugin-mysql](https://github.com/hiroyuki-sato/digdag-plugin-mysql) may help.
As far as I know, nobody develops an operator for MongoDB. 
Fortunately, Digdag supports a plugin system, someone can develop it.

About backend, I think they will not develop another backend for a while.

**Comment by yoyama** [comment]
I would like to close it.
We don't have any plan to support another DB.
