### ISSUE TITLE
Escape dollar sign in .dig file

### ISSUE THREAD

**Issue by jaymed** [treasure-data/digdag#975]
I'd like to pass the literal string of `${HOME}` as a parameter value. Is it possible to escape the dollar sign in a .dig file? It's usually possible to use a $$ (double-dollar sign) when a configuration needs a literal dollar sign.

The following **does not** work and results in a reference error.
```
+setup:
  py>: tasks.MyWorkflow.step1
  arg1: $${HOME}
```

**Comment by chezou** [comment]
Also, it'd be nice if we have curry braces escape as well with doubling them to write complex JS.

**Comment by yoyama** [comment]
Thanks for your report.
I will investigate something workaround or be able to implement this feature.

**Comment by yoyama** [comment]
@jaymed You can write **$** as follows:

```
+t2:
  py>: tasks.MyWorkflow.step1
  arg1: ${'$'}{HOME}
```

Thanks to @frsyuki

**Comment by yoyama** [comment]
@chezou Unfortunately it looks like no way to escape it.

**Comment by jaymed** [comment]
@yoyama Thank you.
