### ISSUE TITLE
Unable to combine if loop and export

### ISSUE THREAD

**Issue by quenchua** [treasure-data/digdag#990]
Version: 0.9.32

I'm trying to assign the value to a variable based on the environment using an If loop.

```
+set_stg_nodes:  
  if>: ${ENV == "stg"}
  _do:
    _export:
      nodes: 'blahblahblah001:9200,blahblahblah002:9200'
+set_prod_nodes:  
  if>: ${ENV == "prod"}
  _do:
    _export:
      nodes: 'blahblahblahPROD001:9200,blahblahblahPROD002:9200'
+echo_task:
  echo>: ${nodes}
```

When I run this, I get an error that ${nodes} is not defined.

Am I doing something wrong?
Can you think of any other way to set the value of a variable based on a condition?

Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @quenchua 

This issue may help 
https://github.com/treasure-data/digdag/issues/847#issuecomment-416110707

And what do you think `param_{set|get}>` operator?
http://docs.digdag.io/operators/param.html

**Comment by quenchua** [comment]
Hello @hiroyuki-sato,

If I set params, I'll still need to set different params based on the Environment.

**Comment by hiroyuki-sato** [comment]
Hello, @quenchua 

I translate the Digdag article.(except pros/cons).
And I think [`param_set`](http://docs.digdag.io/operators/param.html) is No.7

Those ways are just about current implementation.

The author thinks No.5 is good and No. 6 also is good for secrets.

## Six-way to set parameters for each environment in Digdag server mode.

### 1. Use `--param` option with digdag start.

```
$ digdag start --param environment=development --param endpoint=http://localhost:5432 ...
```

### 2.  Use `--param-file` options with digdag start

```yaml
environment: development
endpoint: http://localhost:5432
```

```
$ digdag start --param-file=development.yml ....
```

### 3. Use `--param` option with digdag server

```
$ digdag server --param environment=development --param endpoint=http://localhost:65432
```

### 4. Use `--parm-file` option with digdag server

```yaml
environment: development
endpoint: http://localhost:5432
```

```
$ digdag server —-param-file development.yml
```

### 5. Use Python/Ruby API 

Run Digdag server with the `environment=env_name` parameter

```
$ digdag server —-param environment=development ...
```

create `environment.yml` and run `digdag push`.

```yaml
defaults: &defaults
  slack_username: digdag
production:
  <<: *defaults
  endpoint: https://production.example.com
development:
  <<: *defaults
  endpoint: http://localhost:5432
```

Load environment variable with Python(Ruby) API.

```python
#!/usr/bin/env python

import digdag
import yaml

class PrepareEnviroments(object):
    def set_parameters(self):
        environment = digdag.env.params.get("environment", "development")
        params = {}
        with open("environment.yml", "r") as f:
            data = yaml.load(f)
            params = data[environment]
        digdag.env.store(params)

```

### 6. Use digdag secrets

```
digdag secrets --param environment=development --param endpoint=http://localhost:65432 ...
```

in `.dig` file

```yaml
${secret:environment}
```

```
_env:
  environment: ${secret:environment}
  endpoint: ${secret:endpoint}
```

Ref: [Digdagのserverモードで環境毎に設定値を変える６つの方法](https://qiita.com/sonots/items/4cd45edef2b35421c8a0)

**Comment by hiroyuki-sato** [comment]
Hello, @quenchua 

It may impossible to set a variable with `_export` in `if>` operator.


env.yml

```yaml
development: true
production: false
```

```yaml
+task1:
  if>: ${development}
  _do:
    _export:
      node: "development node"
    echo>: ${node}

+task2:
  if>: ${production}
  _do:
    _export:
      node: "prodction node"
    echo>: ${node}

+task3:
  echo>: ${node}
```


```
digdag run -a --params-file env.yml digdag.dig
2019-02-14 18:21:38 +0900: Digdag v0.9.32
2019-02-14 18:21:40 +0900 [WARN] (main): Reusing the last session time 2019-02-14T00:00:00+00:00.
2019-02-14 18:21:40 +0900 [INFO] (main): Using session /private/tmp/hoge/.digdag/status/20190214T000000+0000.
2019-02-14 18:21:40 +0900 [INFO] (main): Starting a new session project id=1 workflow name=digdag session_time=2019-02-14T00:00:00+00:00
2019-02-14 18:21:41 +0900 [INFO] (0017@[0:default]+digdag+task1): if>: true
2019-02-14 18:21:41 +0900 [INFO] (0017@[0:default]+digdag+task1^sub): echo>: development node
development node
2019-02-14 18:21:41 +0900 [INFO] (0017@[0:default]+digdag+task2): if>: false
2019-02-14 18:21:42 +0900 [ERROR] (0017@[0:default]+digdag+task3): Configuration error at task +digdag+task3: Failed to evaluate a variable ${node} (ReferenceError: "node" is not defined) (config)
2019-02-14 18:21:42 +0900 [INFO] (0017@[0:default]+digdag^failure-alert): type: notify
error:
  * +digdag+task3:
    Failed to evaluate a variable ${node} (ReferenceError: "node" is not defined) (config)

Task state is saved at /private/tmp/hoge/.digdag/status/20190214T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

**Comment by quenchua** [comment]
Hello @hiroyuki-sato, thanks so much for all the effort.

We ended up doing something like this:

`  +load_data_to_prod:
    if>: ${ENV == "pro"}
    _do:
      _export:
        es_nodes: 'server_name_1:9200,server_name_2:9200'
      call>: run.dig
  +load_data_to_stg:
    if>: ${ENV == "stg"}
    _do:
      _export:
        es_nodes: 'server_name_1:9200,server_name_2:9200'
      call>: run.dig`

It works for setting the variables at task level.

Thanks!

**Comment by yoyama** [comment]
Close because the issue has been resolved.
