### ISSUE TITLE
steaming log output [question]

### ISSUE THREAD

**Issue by jaymed** [treasure-data/digdag#992]
Is there a way to stream the log output of a long running task to the workflow/tasks UI section?

The only way to do this currently is to tail `/var/log/messages` which may contain a mix of all tasks and system events.

We are storing our task logs in s3.

**Comment by hiroyuki-sato** [comment]
Hello, @jaymed 

Maybe, The feature which you ask is discussing in #700.
What operator are you use for long running tasks?

**Comment by yoyama** [comment]
Close this issue by #1209. 
Configure log-server.local.split_size to be small enough, you can get task log by 'digdag log -f'

**Comment by sasamuku** [comment]
Hello, @yoyama 
Thank you for allowing us to split logs.
Would you mind if I propose one additional feature?

As you mentioned in https://github.com/treasure-data/digdag/pull/1209, it would be great that `UPLOAD_THRESHOLD` of BufferedRemoteTaskLogger could be configurable. 

In our situation, 'digdag log -f' is not enough, only users who have permission to get into server can run 'digdag' command.

How do you think? 
Thank you.
