### ISSUE TITLE
[feature request] Last attempt with yyyy-MM-dd HH:mm:ss format on Digdag Web UI

### ISSUE THREAD

**Issue by sonots-zozo** [treasure-data/digdag#997]
Currently, on digdag UI, we can see session time and last attempt as:

![image](https://user-images.githubusercontent.com/46368492/53058560-e334d380-34f6-11e9-904f-ff5aad090e8b.png)

The session time does not always express the time starting.
So, I want to look the exact attempt time, but it is formatted like "2 days ago".
I want to see the exact time.

**Comment by sonots-zozo** [comment]
BTW, in the case of github, If you move your mouse over the xx minutes|hours\... ago label, a tooltip will be displayed showing the UTC time the commit was created at.

**Comment by muga** [comment]
Would we like to have a button to change some formats around the following?
https://github.com/treasure-data/digdag/blob/master/digdag-ui/console.jsx#L481

@szyn Do you have any suggestions?
